# -*- coding: utf-8 -*-
"""compare_policies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lb4d7hMZ8TCQyKbPsoUMf-Guq8LsoB3d
"""

!pip install -q stable-baselines3 gymnasium

from __future__ import annotations
import csv
import json
import subprocess
import sys
from dataclasses import asdict, dataclass
from math import gamma
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# =============================================================================
# 0. Colab dependency bootstrap
# =============================================================================

def _install_if_missing() -> None:
    try:
        import gymnasium  # noqa: F401
        import stable_baselines3  # noqa: F401
        import scipy  # noqa: F401
    except ImportError:
        subprocess.check_call(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "-q",
                "stable-baselines3>=2.3,<3",
                "gymnasium>=0.29,<2",
                "scipy>=1.10",
            ]
        )


_install_if_missing()

import gymnasium as gym
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
from gymnasium import spaces
from scipy.optimize import lsq_linear
from scipy import sparse
from stable_baselines3 import PPO
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

# Large, thesis-readable typography.  These values also propagate to colorbar
# labels and 3D-axis labels, which are easy to miss when figures are reduced.
plt.rcParams.update(
    {
        "font.size": 18,
        "axes.titlesize": 20,
        "axes.labelsize": 18,
        "xtick.labelsize": 16,
        "ytick.labelsize": 16,
        "legend.fontsize": 17,
        "figure.titlesize": 22,
    }
)


# =============================================================================
# 1. User settings
# =============================================================================

# Change only these paths if your Drive layout differs.
MODEL_PATH = Path("/content/drive/MyDrive/thesis/checkpoint/best_model_13.zip")
VECNORMALIZE_PATH = Path(
    "/content/drive/MyDrive/thesis/checkpoint/best_model_13_vecnormalize.pkl"
)
OUTPUT_DIR = Path("/content/print_2d_layer_by_layer_best_model_13")

N_LAYERS = 10
LAYER_THICKNESS = 0.02
FINAL_MAX_HEIGHT = N_LAYERS * LAYER_THICKNESS

# Run all four agreed shapes.  You may keep only one name for a quick test.
SHAPES_TO_RUN = [
    "full_rectangle",
    "full_cylinder",
    "four_gaussian_bumps",
    "edge_bump",
]

DETERMINISTIC_ACTION = True
SHOW_FIGURES_IN_COLAB = True
RANDOM_SEED = 141


@dataclass
class Config:
    # Must match best_model_13 training.
    grid_n: int = 32
    spacing_px: int = 2
    ds: float = 0.05

    sigma: float = 0.05
    beta: float = 1.0
    eta: float = 0.4
    rho_m: float = 6500.0
    samples_per_pixel: float = 1.0
    A_amp: float = 1.0
    feed_rate: float = 2.0

    use_geometry_dependent_kernel: bool = True
    geometry_kernel_p: float = 1.0
    slope_smoothing_window: int = 9

    v_max: float = 1.5
    v_min: float = 0.01
    base_v: float = 0.5
    delta_v_max: float = 1.0
    off_max: float = 0.05
    offset_limit: float = 0.10

    # Adaptive nominal slicer settings.
    n_offset_lanes: int = 7
    lambda_mass: float = 1e-5
    lambda_step_smooth: float = 1e-3
    lambda_lane_smooth: float = 5e-4
    positive_target_weight: float = 2.5
    slicer_max_iter: int = 200


CFG = Config()


# =============================================================================
# 2. Exact custom feature extractor used by best_model_13
# =============================================================================

class ColdSpray2DMultiInputExtractor(BaseFeaturesExtractor):
    def __init__(
        self,
        observation_space: spaces.Dict,
        cnn_output_dim: int = 128,
        state_output_dim: int = 32,
    ) -> None:
        super().__init__(
            observation_space,
            features_dim=cnn_output_dim + state_output_dim,
        )
        map_space = observation_space["map"]
        state_space = observation_space["state"]
        n_map_channels = int(map_space.shape[0])
        n_state = int(state_space.shape[0])

        self.map_cnn = nn.Sequential(
            nn.Conv2d(n_map_channels, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
        )
        with torch.no_grad():
            sample_map = torch.as_tensor(map_space.sample()[None]).float()
            n_flatten = int(self.map_cnn(sample_map).shape[1])

        self.map_head = nn.Sequential(
            nn.Linear(n_flatten, cnn_output_dim),
            nn.ReLU(),
        )
        self.state_mlp = nn.Sequential(
            nn.Linear(n_state, 64),
            nn.ReLU(),
            nn.Linear(64, state_output_dim),
            nn.ReLU(),
        )

    def forward(self, observations: Dict[str, torch.Tensor]) -> torch.Tensor:
        map_features = self.map_head(self.map_cnn(observations["map"].float()))
        state_features = self.state_mlp(observations["state"].float())
        return torch.cat([map_features, state_features], dim=1)


class DummyDictEnv(gym.Env):
    """Only supplies the spaces needed to restore VecNormalize."""

    def __init__(self, cfg: Config):
        super().__init__()
        self.observation_space = spaces.Dict(
            {
                "map": spaces.Box(
                    -np.inf,
                    np.inf,
                    shape=(2, cfg.grid_n, cfg.grid_n),
                    dtype=np.float32,
                ),
                "state": spaces.Box(
                    -np.inf,
                    np.inf,
                    shape=(5,),
                    dtype=np.float32,
                ),
            }
        )
        self.action_space = spaces.Box(-1.0, 1.0, shape=(2,), dtype=np.float32)

    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)
        return {
            "map": np.zeros((2, CFG.grid_n, CFG.grid_n), np.float32),
            "state": np.zeros(5, np.float32),
        }, {}

    def step(self, action):
        obs, _ = self.reset()
        return obs, 0.0, False, True, {}


def load_agent(cfg: Config) -> Tuple[PPO, VecNormalize]:
    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Model not found: {MODEL_PATH}\n"
            "Edit MODEL_PATH at the top of this script."
        )
    if not VECNORMALIZE_PATH.exists():
        raise FileNotFoundError(
            f"VecNormalize not found: {VECNORMALIZE_PATH}\n"
            "best_model_13 must be used with its matching VecNormalize file."
        )

    dummy = DummyVecEnv([lambda: DummyDictEnv(cfg)])
    vecnorm = VecNormalize.load(str(VECNORMALIZE_PATH), dummy)
    vecnorm.training = False
    vecnorm.norm_reward = False

    device = "cuda" if torch.cuda.is_available() else "cpu"

    # IMPORTANT:
    # Some best_model_13 checkpoints do not restore the serialized custom
    # extractor entry in policy_kwargs.  In that case SB3 silently constructs
    # its default CombinedExtractor, which flattens this observation to
    # 2*32*32 + 5 = 2053 features.  The saved actor/critic weights, however,
    # were trained with ColdSpray2DMultiInputExtractor and therefore expect
    # 128 + 32 = 160 features.  Supplying policy_kwargs via custom_objects
    # forces SB3 to reconstruct the exact training architecture before loading
    # the state_dict.
    exact_policy_kwargs = {
        "log_std_init": -4.0,
        "features_extractor_class": ColdSpray2DMultiInputExtractor,
        "features_extractor_kwargs": {
            "cnn_output_dim": 128,
            "state_output_dim": 32,
        },
    }
    model = PPO.load(
        str(MODEL_PATH),
        env=vecnorm,
        device=device,
        custom_objects={"policy_kwargs": exact_policy_kwargs},
    )

    # Fail immediately with a useful message if a different checkpoint is
    # accidentally selected, rather than waiting for the first rollout.
    extractor = model.policy.features_extractor
    if not isinstance(extractor, ColdSpray2DMultiInputExtractor):
        raise RuntimeError(
            "Wrong policy architecture after loading: expected "
            "ColdSpray2DMultiInputExtractor, got "
            f"{type(extractor).__name__}."
        )
    if int(extractor.features_dim) != 160:
        raise RuntimeError(
            "Wrong extractor output size: expected 160 "
            f"(128 CNN + 32 state), got {extractor.features_dim}."
        )
    if model.observation_space != dummy.observation_space:
        raise RuntimeError(
            "Checkpoint observation space does not match best_model_13: "
            f"checkpoint={model.observation_space}, expected={dummy.observation_space}."
        )

    print(f"[OK] Loaded model: {MODEL_PATH}")
    print(f"[OK] Loaded VecNormalize: {VECNORMALIZE_PATH}")
    print("[OK] Policy architecture: custom CNN+MLP extractor (160 features)")
    print(f"[OK] Inference device: {device}")
    return model, vecnorm


# =============================================================================
# 3. Snake path and deposition model
# =============================================================================

class SnakePath2D:
    def __init__(self, cfg: Config):
        self.cfg = cfg

    @staticmethod
    def _cumlen(points: np.ndarray) -> np.ndarray:
        d = points[1:] - points[:-1]
        return np.r_[0.0, np.cumsum(np.linalg.norm(d, axis=1))]

    def polyline(self) -> Tuple[np.ndarray, np.ndarray]:
        n = self.cfg.grid_n
        points: List[List[float]] = []
        direction = 1
        py = 0
        while py <= n - 1:
            px0, px1 = (0, n - 1) if direction == 1 else (n - 1, 0)
            p0 = [(px0 + 0.5) / n, (py + 0.5) / n]
            p1 = [(px1 + 0.5) / n, (py + 0.5) / n]
            if not points or not np.allclose(points[-1], p0):
                points.append(p0)
            points.append(p1)
            py_next = py + self.cfg.spacing_px
            if py_next <= n - 1:
                points.append([(px1 + 0.5) / n, (py_next + 0.5) / n])
            direction *= -1
            py = py_next
        pts = np.asarray(points, dtype=np.float64)
        return pts, self._cumlen(pts)

    @staticmethod
    def pose_at_s(
        pts: np.ndarray,
        cumlen: np.ndarray,
        s: float,
    ) -> Tuple[float, float, float, float]:
        s = float(np.clip(s, 0.0, cumlen[-1]))
        i = int(np.clip(np.searchsorted(cumlen, s, side="right") - 1, 0, len(cumlen) - 2))
        denom = max(float(cumlen[i + 1] - cumlen[i]), 1e-12)
        a = (s - float(cumlen[i])) / denom
        p = (1.0 - a) * pts[i] + a * pts[i + 1]
        d = pts[i + 1] - pts[i]
        d /= max(float(np.linalg.norm(d)), 1e-12)
        return float(p[0]), float(p[1]), float(d[0]), float(d[1])

    def steps(self) -> List[dict]:
        pts, cumlen = self.polyline()
        total = float(cumlen[-1])
        s_values = np.arange(0.0, total, self.cfg.ds, dtype=np.float64)
        if len(s_values) == 0 or s_values[-1] < total:
            s_values = np.r_[s_values, total]

        out = []
        for s0, s1 in zip(s_values[:-1], s_values[1:]):
            x0, y0, tx0, ty0 = self.pose_at_s(pts, cumlen, float(s0))
            x1, y1, tx1, ty1 = self.pose_at_s(pts, cumlen, float(s1))
            tx, ty = 0.5 * (tx0 + tx1), 0.5 * (ty0 + ty1)
            norm = max(float(np.hypot(tx, ty)), 1e-12)
            tx, ty = tx / norm, ty / norm
            out.append(
                dict(
                    x0=x0, y0=y0, x1=x1, y1=y1,
                    tx=tx, ty=ty, nx=-ty, ny=tx,
                    length=max(float(s1 - s0), 1e-8),
                )
            )
        return out


def _smooth_2d_reflect(height: np.ndarray, window: int) -> np.ndarray:
    window = int(window)
    if window <= 1:
        return height.astype(np.float32, copy=True)
    if window % 2 == 0:
        window += 1
    pad = window // 2
    h = np.pad(height.astype(np.float64), ((pad, pad), (pad, pad)), mode="reflect")
    kernel = np.ones(window, dtype=np.float64) / window
    tmp = np.apply_along_axis(lambda row: np.convolve(row, kernel, mode="valid"), 1, h)
    out = np.apply_along_axis(lambda col: np.convolve(col, kernel, mode="valid"), 0, tmp)
    return out.astype(np.float32)


class DepositionModel2D:
    def __init__(self, cfg: Config):
        self.cfg = cfg
        n = cfg.grid_n
        self.pix_area = (1.0 / n) ** 2
        self.C = cfg.beta * self.pix_area / (
            2.0 * np.pi * cfg.sigma**2 * gamma(2.0 / cfg.beta)
        )
        grid = (np.arange(n, dtype=np.float64) + 0.5) / n
        self.Y, self.X = np.meshgrid(grid, grid, indexing="ij")

    def _kernel(self, r: np.ndarray) -> np.ndarray:
        c = self.cfg
        return c.A_amp * self.C * np.exp(-((r / c.sigma) ** c.beta))

    def basis_for_segment(
        self,
        x0: float,
        y0: float,
        x1: float,
        y1: float,
        height_for_geometry: Optional[np.ndarray] = None,
        modified: bool = False,
    ) -> np.ndarray:
        c = self.cfg
        dx, dy = x1 - x0, y1 - y0
        length = float(np.hypot(dx, dy))
        samples = max(
            1,
            int(np.ceil(length / ((1.0 / c.grid_n) / max(c.samples_per_pixel, 1e-6)))),
        )
        s = (np.arange(samples) + 0.5) / samples
        acc = np.zeros((c.grid_n, c.grid_n), dtype=np.float64)
        for a in s:
            x, y = x0 + a * dx, y0 + a * dy
            acc += self._kernel(np.hypot(self.X - x, self.Y - y))
        basis = (c.eta / (c.rho_m * self.pix_area)) * acc / samples

        if modified and height_for_geometry is not None:
            hs = _smooth_2d_reflect(height_for_geometry, c.slope_smoothing_window)
            dh_dy, dh_dx = np.gradient(hs.astype(np.float64), 1.0 / c.grid_n)
            grad = np.sqrt(dh_dx**2 + dh_dy**2)
            eta_geom = (1.0 + grad**2) ** (-0.5 * c.geometry_kernel_p)
            basis *= eta_geom
        return basis.astype(np.float32)


def clipped_shifted_segment(st: dict, offset: float) -> Tuple[float, float, float, float]:
    return tuple(
        float(np.clip(v, 0.0, 1.0))
        for v in (
            st["x0"] + offset * st["nx"],
            st["y0"] + offset * st["ny"],
            st["x1"] + offset * st["nx"],
            st["y1"] + offset * st["ny"],
        )
    )


# =============================================================================
# 4. Deterministic final targets
# =============================================================================

def make_final_target(shape_name: str, cfg: Config) -> np.ndarray:
    grid = (np.arange(cfg.grid_n, dtype=np.float64) + 0.5) / cfg.grid_n
    Y, X = np.meshgrid(grid, grid, indexing="ij")

    if shape_name == "full_rectangle":
        target = np.full_like(X, FINAL_MAX_HEIGHT)

    elif shape_name == "full_cylinder":
        radius = 0.5
        target = FINAL_MAX_HEIGHT * (
            (X - 0.5) ** 2 + (Y - 0.5) ** 2 <= radius**2
        )

    elif shape_name == "four_gaussian_bumps":
        # Use a dedicated seeded generator so this target is reproducible and
        # does not depend on any random numbers consumed elsewhere.  Rejection
        # sampling keeps the randomly positioned bumps visibly separated.
        rng = np.random.default_rng(RANDOM_SEED + 4004)
        centers: List[Tuple[float, float]] = []
        while len(centers) < 4:
            candidate = tuple(rng.uniform(0.16, 0.84, size=2))
            if all(
                np.hypot(candidate[0] - cx, candidate[1] - cy) >= 0.24
                for cx, cy in centers
            ):
                centers.append(candidate)

        # Different amplitudes and widths make the four bumps unequal in both
        # peak height and footprint while retaining the 0.10 m base slab.
        amplitudes = rng.uniform(0.050, 0.100, size=4)
        sigmas = rng.uniform(0.060, 0.095, size=4)
        target = np.full_like(X, 0.10)
        for (cx, cy), amplitude, sigma in zip(centers, amplitudes, sigmas):
            target += amplitude * np.exp(
                -((X - cx) ** 2 + (Y - cy) ** 2) / (2.0 * sigma**2)
            )
        target = np.minimum(target, FINAL_MAX_HEIGHT)
        print("[INFO] Random four-bump target (fixed seed):")
        for idx, ((cx, cy), amplitude, sigma) in enumerate(
            zip(centers, amplitudes, sigmas),
            start=1,
        ):
            print(
                f"       bump {idx}: center=({cx:.3f}, {cy:.3f}), "
                f"amplitude={amplitude:.3f}, sigma={sigma:.3f}"
            )

    elif shape_name == "edge_bump":
        target = 0.10 + 0.10 * np.exp(
            -((X - 0.08) ** 2 + (Y - 0.50) ** 2) / (2.0 * 0.08**2)
        )
        target = np.minimum(target, FINAL_MAX_HEIGHT)

    else:
        raise ValueError(f"Unknown shape: {shape_name}")

    return target.astype(np.float32)


# =============================================================================
# 5. Adaptive nominal slicer
# =============================================================================

class AdaptiveSlicer:
    """
    Same LSQ slicer formulation as sb3_cold_spray_generalized_gaussian_ppo_13:
    the nonnegative variables are mass(step, offset_lane), with mass, step and
    lane smoothness regularization.  The solution is collapsed to one velocity
    and one baseline offset per snake step.

    Slicer planning always uses the original nominal Gaussian kernel.
    """

    def __init__(self, cfg: Config, steps: List[dict], deposition: DepositionModel2D):
        self.cfg = cfg
        self.steps = steps
        print("[INFO] Building nominal slicer basis once ...")
        self.offset_lanes = np.linspace(
            -cfg.off_max, cfg.off_max, cfg.n_offset_lanes, dtype=np.float64
        )
        columns = []
        for st in steps:
            for lane_off in self.offset_lanes:
                x0, y0, x1, y1 = clipped_shifted_segment(st, float(lane_off))
                columns.append(
                    deposition.basis_for_segment(
                        x0, y0, x1, y1, modified=False
                    ).reshape(-1)
                )
        self.B = np.stack(columns, axis=1).astype(np.float64)

        n_steps = len(steps)
        n_lanes = cfg.n_offset_lanes
        d_step = sparse.diags(
            [np.ones(n_steps - 1), -np.ones(n_steps - 1)],
            [0, 1],
            shape=(n_steps - 1, n_steps),
            format="csr",
        )
        d_lane = sparse.diags(
            [np.ones(n_lanes - 1), -np.ones(n_lanes - 1)],
            [0, 1],
            shape=(n_lanes - 1, n_lanes),
            format="csr",
        )
        self.D_step = sparse.kron(d_step, sparse.eye(n_lanes), format="csr")
        self.D_lane = sparse.kron(sparse.eye(n_steps), d_lane, format="csr")
        print(f"[OK] Nominal basis shape: {self.B.shape}")

    def plan(
        self, desired_increment: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray, Dict[str, float]]:
        c = self.cfg
        target = np.maximum(desired_increment, 0.0).astype(np.float64).reshape(-1)
        pixel_w = np.ones_like(target)
        pixel_w[target > 1e-12] = c.positive_target_weight
        sqrt_w = np.sqrt(pixel_w)

        A_data = sparse.csr_matrix(self.B * sqrt_w[:, None])
        b_data = target * sqrt_w
        blocks = [A_data]
        rhs = [b_data]
        n_vars = self.B.shape[1]

        if c.lambda_mass > 0:
            blocks.append(np.sqrt(c.lambda_mass) * sparse.eye(n_vars, format="csr"))
            rhs.append(np.zeros(n_vars))
        if c.lambda_step_smooth > 0:
            blocks.append(np.sqrt(c.lambda_step_smooth) * self.D_step)
            rhs.append(np.zeros(self.D_step.shape[0]))
        if c.lambda_lane_smooth > 0:
            blocks.append(np.sqrt(c.lambda_lane_smooth) * self.D_lane)
            rhs.append(np.zeros(self.D_lane.shape[0]))

        sol = lsq_linear(
            sparse.vstack(blocks, format="csr"),
            np.concatenate(rhs),
            bounds=(0.0, np.inf),
            method="trf",
            lsmr_tol="auto",
            max_iter=c.slicer_max_iter,
        )
        mass = sol.x.reshape(len(self.steps), c.n_offset_lanes)
        mass_per_step = np.sum(mass, axis=1)
        v_base = np.empty(len(self.steps), dtype=np.float32)
        offset_base = np.empty(len(self.steps), dtype=np.float32)
        for i, st in enumerate(self.steps):
            if mass_per_step[i] <= 1e-12:
                v_base[i] = c.v_max
                offset_base[i] = 0.0
            else:
                dt = mass_per_step[i] / max(c.feed_rate, 1e-12)
                v_base[i] = np.clip(st["length"] / max(dt, 1e-12), c.v_min, c.v_max)
                # Match the SB3 reference code: select the lane with maximum mass.
                offset_base[i] = self.offset_lanes[int(np.argmax(mass[i]))]

        reconstruction = (self.B @ mass.reshape(-1)).reshape(c.grid_n, c.grid_n)
        info = {
            "lsq_cost": float(sol.cost),
            "lsq_success": bool(sol.success),
            "slicer_reconstruction_mse": float(
                np.mean((reconstruction - desired_increment) ** 2)
            ),
        }
        return v_base, offset_base, info


# =============================================================================
# 6. Metrics and rollout
# =============================================================================

def surface_metrics(height: np.ndarray, target: np.ndarray) -> Dict[str, float]:
    h = height.astype(np.float64)
    t = target.astype(np.float64)
    err = h - t
    mse = float(np.mean(err**2))
    mae = float(np.mean(np.abs(err)))
    mean_t = float(np.mean(t))
    active = t > 1e-9
    active_mse = float(np.mean(err[active] ** 2)) if np.any(active) else float("nan")
    overshoot = np.maximum(err, 0.0)
    undershoot = np.maximum(-err, 0.0)
    target_volume = float(np.sum(t))
    volume_error = float(abs(np.sum(h) - target_volume) / max(target_volume, 1e-12))
    return {
        "mse": mse,
        "relative_mse": mse / max(mean_t**2, 1e-12),
        "mae": mae,
        "active_mse": active_mse,
        "max_abs_error": float(np.max(np.abs(err))),
        "max_overshoot": float(np.max(overshoot)),
        "mean_overshoot": float(np.mean(overshoot)),
        "max_undershoot": float(np.max(undershoot)),
        "volume_error": volume_error,
        "mean_height": float(np.mean(h)),
        "mean_target": mean_t,
    }


def normalize_observation(
    obs: Dict[str, np.ndarray],
    vecnorm: VecNormalize,
) -> Dict[str, np.ndarray]:
    batched = {key: value[None, ...] for key, value in obs.items()}
    return vecnorm.normalize_obs(batched)


def run_case(
    shape_name: str,
    case_name: str,
    cfg: Config,
    model: Optional[PPO],
    vecnorm: Optional[VecNormalize],
    steps: List[dict],
    deposition: DepositionModel2D,
    slicer: AdaptiveSlicer,
    *,
    use_rl: bool,
    execution_modified: bool,
) -> Dict[str, Any]:
    """
    Run one of the three policy/kernel combinations used in the thesis:

      - Slicer/original: slicer only, original kernel at execution.
      - Slicer/modified: slicer only, modified kernel at execution.
      - RL/modified:     residual RL policy, modified kernel at execution.

    In all cases the nominal slicer plans with the original Gaussian basis.
    """
    if use_rl and (model is None or vecnorm is None):
        raise ValueError("RL execution requires both model and vecnorm.")

    final_target = make_final_target(shape_name, cfg)
    height = np.zeros_like(final_target)

    heights, targets, increments = [], [], []
    metrics, velocities, base_velocities, dvs, offsets = [], [], [], [], []
    slicer_info = []

    for layer in range(1, N_LAYERS + 1):
        h_start = height.copy()
        target_after_layer = (layer / N_LAYERS) * final_target
        desired_increment = np.maximum(target_after_layer - h_start, 0.0).astype(np.float32)
        v_base_vec, offset_base_vec, plan_info = slicer.plan(desired_increment)

        layer_v, layer_vbase, layer_dv, layer_off = [], [], [], []
        previous_velocity = float(v_base_vec[0])
        previous_offset = 0.0

        for step_idx, st in enumerate(steps):
            local_base_v = float(v_base_vec[step_idx])
            local_base_off = float(offset_base_vec[step_idx])
            if use_rl:
                layer_height = (height - h_start).astype(np.float32)
                progress = np.float32(step_idx / max(len(steps), 1))
                obs = {
                    "map": np.stack(
                        [layer_height, layer_height - desired_increment],
                        axis=0,
                    ).astype(np.float32),
                    "state": np.array(
                        [
                            progress,
                            np.float32(1.0 - progress),
                            np.float32(previous_velocity),
                            np.float32(local_base_v),
                            np.float32(previous_offset),
                        ],
                        dtype=np.float32,
                    ),
                }
                obs_norm = normalize_observation(obs, vecnorm)
                action, _ = model.predict(
                    obs_norm,
                    deterministic=DETERMINISTIC_ACTION,
                )
                action = np.asarray(action).reshape(-1)
                dv = float(np.clip(action[0], -1.0, 1.0)) * cfg.delta_v_max
                # best_model_13 was trained with a zero offset baseline; its
                # second action is therefore still a direct residual around 0.
                off = float(np.clip(action[1], -1.0, 1.0)) * cfg.off_max
                off = float(np.clip(off, -cfg.offset_limit, cfg.offset_limit))
            else:
                # Pure slicer executes the baseline velocity and lane selected
                # by the LSQ slicer, with no RL residual.
                dv = 0.0
                off = local_base_off
            velocity = float(np.clip(local_base_v + dv, cfg.v_min, cfg.v_max))

            x0, y0, x1, y1 = clipped_shifted_segment(st, off)
            basis = deposition.basis_for_segment(
                x0, y0, x1, y1,
                height_for_geometry=height.copy(),
                modified=execution_modified,
            )
            dt = float(st["length"]) / max(velocity, 1e-12)
            mass = cfg.feed_rate * dt
            height = (height + mass * basis).astype(np.float32)

            previous_velocity = velocity
            previous_offset = off
            layer_v.append(velocity)
            layer_vbase.append(local_base_v)
            layer_dv.append(dv)
            layer_off.append(off)

        layer_metric = surface_metrics(height, target_after_layer)
        heights.append(height.copy())
        targets.append(target_after_layer.copy())
        increments.append(desired_increment.copy())
        metrics.append(layer_metric)
        velocities.append(layer_v)
        base_velocities.append(layer_vbase)
        dvs.append(layer_dv)
        offsets.append(layer_off)
        slicer_info.append(plan_info)

        print(
            f"[{shape_name} | {case_name}] layer {layer:02d}/{N_LAYERS} | "
            f"RelMSE={layer_metric['relative_mse']:.6e} | "
            f"maxOv={layer_metric['max_overshoot']:.6e} | "
            f"volumeErr={layer_metric['volume_error']:.3%}"
        )

    return {
        "shape_name": shape_name,
        "case_name": case_name,
        "use_rl": use_rl,
        "execution_modified": execution_modified,
        "final_target": final_target,
        "layer_heights": np.stack(heights),
        "layer_targets": np.stack(targets),
        "desired_increments": np.stack(increments),
        "metrics": metrics,
        "velocities": np.asarray(velocities, np.float32),
        "base_velocities": np.asarray(base_velocities, np.float32),
        "dvs": np.asarray(dvs, np.float32),
        "offsets": np.asarray(offsets, np.float32),
        "slicer_info": slicer_info,
        "final_height": heights[-1],
        "final_metrics": metrics[-1],
    }


# =============================================================================
# 7. Figures and machine-readable exports
# =============================================================================

def _finish_figure(fig: plt.Figure, path: Path) -> None:
    fig.savefig(path, dpi=250, bbox_inches="tight", facecolor="white")
    if SHOW_FIGURES_IN_COLAB:
        plt.show()
    plt.close(fig)


def _metric_text(metric: Dict[str, float]) -> str:
    """Format only the three metrics reported in the thesis figure."""
    return (
        rf"relMSE = {metric['relative_mse']:.3e}"
        rf"        maxOv = {metric['max_overshoot']:.3e}"
        rf"        rel. volume error = {metric['volume_error']:.2%}"
    )


def plot_final_target_and_selected_layers(
    result: Dict[str, Any],
    out_dir: Path,
) -> None:
    """One figure: final target preview plus selected cumulative 3D layers."""
    target = result["final_target"]
    selected = [0, 4, 9]
    n = target.shape[0]
    grid = (np.arange(n) + 0.5) / n
    X, Y = np.meshgrid(grid, grid)

    fig = plt.figure(figsize=(24, 17))
    gs = fig.add_gridspec(
        3,
        6,
        height_ratios=[1.08, 1.0, 1.0],
        hspace=0.38,
        wspace=0.42,
    )

    ax_map = fig.add_subplot(gs[0, 0:3])
    ax_surface = fig.add_subplot(gs[0, 3:6], projection="3d")
    im = ax_map.imshow(
        target,
        origin="lower",
        extent=[0, 1, 0, 1],
        cmap="viridis",
    )
    ax_map.set(title="Final target height map", xlabel="x", ylabel="y")
    fig.colorbar(im, ax=ax_map, label="height")
    ax_surface.plot_surface(X, Y, target, cmap="viridis", linewidth=0)
    ax_surface.set(
        title="Final target surface",
        xlabel="x",
        ylabel="y",
        zlabel="height",
    )
    ax_surface.set_zlim(0, FINAL_MAX_HEIGHT * 1.20)

    for col, idx in enumerate(selected):
        panels = [
            (result["layer_targets"][idx], "Cumulative target"),
            (result["layer_heights"][idx], "Printed surface"),
        ]
        for row, (surface, title) in enumerate(panels, start=1):
            ax = fig.add_subplot(
                gs[row, 2 * col:2 * col + 2],
                projection="3d",
            )
            ax.plot_surface(X, Y, surface, cmap="viridis", linewidth=0)
            ax.set(
                title=f"Layer {idx + 1}/{N_LAYERS}: {title}",
                xlabel="x",
                ylabel="y",
                zlabel="height",
            )
            ax.set_zlim(0, FINAL_MAX_HEIGHT * 1.20)

    fig.suptitle(
        f"Final target and selected cumulative layers — {result['shape_name']}",
        fontsize=26,
        y=0.995,
    )
    _finish_figure(fig, out_dir / "01_final_target_and_selected_layers.png")


def plot_selected_policy_comparison(
    case_results: Dict[str, Dict[str, Any]],
    out_dir: Path,
) -> None:
    """
    Compare the three execution cases at layers 1, 5, and 10.

    Columns are execution cases and rows are selected cumulative layers.
    Every map has its own relMSE, maximum overshoot, and relative volume error
    directly underneath it.
    """
    selected = [0, 4, 9]
    case_order = ["Slicer/original", "Slicer/modified", "RL/modified"]
    missing = [name for name in case_order if name not in case_results]
    if missing:
        raise KeyError(f"Missing comparison cases: {missing}")

    shape_name = case_results[case_order[0]]["shape_name"]
    fig = plt.figure(figsize=(24, 23))
    gs = fig.add_gridspec(
        6,
        3,
        height_ratios=[1.0, 0.19, 1.0, 0.19, 1.0, 0.19],
        hspace=0.31,
        wspace=0.28,
    )

    for row, idx in enumerate(selected):
        map_row = 2 * row
        metric_row = map_row + 1
        layer_target = case_results[case_order[0]]["layer_targets"][idx]
        all_heights = [
            case_results[name]["layer_heights"][idx] for name in case_order
        ]
        common_min = float(min(np.min(layer_target), *(np.min(h) for h in all_heights)))
        common_max = float(max(np.max(layer_target), *(np.max(h) for h in all_heights)))

        for col, case_name in enumerate(case_order):
            result = case_results[case_name]
            ax = fig.add_subplot(gs[map_row, col])
            image = ax.imshow(
                result["layer_heights"][idx],
                origin="lower",
                extent=[0, 1, 0, 1],
                cmap="viridis",
                vmin=common_min,
                vmax=common_max,
            )
            ax.set(
                title=f"{case_name}\nLayer {idx + 1}/{N_LAYERS}",
                xlabel="x",
                ylabel="y",
            )
            fig.colorbar(image, ax=ax, label="printed height")

            metric_ax = fig.add_subplot(gs[metric_row, col])
            metric_ax.set_axis_off()
            metric_ax.text(
                0.5,
                0.55,
                _metric_text(result["metrics"][idx]),
                ha="center",
                va="center",
                fontsize=15,
                fontweight="bold",
                transform=metric_ax.transAxes,
                bbox={
                    "boxstyle": "round,pad=0.38",
                    "facecolor": "#f4f4f4",
                    "edgecolor": "#555555",
                    "linewidth": 1.1,
                },
            )

    fig.suptitle(
        f"Layer-by-layer policy comparison — {shape_name}",
        fontsize=26,
        y=0.995,
    )
    _finish_figure(fig, out_dir / "02_processing_layers_01_05_10.png")


def export_result(result: Dict[str, Any], out_dir: Path) -> None:
    np.savez_compressed(
        out_dir / "layer_by_layer_arrays.npz",
        final_target=result["final_target"],
        final_height=result["final_height"],
        layer_targets=result["layer_targets"],
        layer_heights=result["layer_heights"],
        desired_increments=result["desired_increments"],
        velocities=result["velocities"],
        base_velocities=result["base_velocities"],
        dvs=result["dvs"],
        offsets=result["offsets"],
    )

    metric_fields = ["layer"] + list(result["metrics"][0].keys())
    with open(out_dir / "layer_metrics.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=metric_fields)
        writer.writeheader()
        for idx, metric in enumerate(result["metrics"], start=1):
            writer.writerow({"layer": idx, **metric})

    with open(out_dir / "final_metrics.json", "w", encoding="utf-8") as f:
        json.dump(result["final_metrics"], f, indent=2)

    with open(out_dir / "run_config.json", "w", encoding="utf-8") as f:
        json.dump(
            {
                **asdict(CFG),
                "n_layers": N_LAYERS,
                "layer_thickness": LAYER_THICKNESS,
                "model_path": str(MODEL_PATH),
                "vecnormalize_path": str(VECNORMALIZE_PATH),
                "deterministic_action": DETERMINISTIC_ACTION,
                "shape_name": result["shape_name"],
                "case_name": result["case_name"],
                "use_rl": result["use_rl"],
                "execution_modified": result["execution_modified"],
            },
            f,
            indent=2,
        )


def save_all_outputs(case_results: Dict[str, Dict[str, Any]]) -> None:
    first_result = next(iter(case_results.values()))
    out_dir = OUTPUT_DIR / first_result["shape_name"]
    out_dir.mkdir(parents=True, exist_ok=True)
    # Remove figures from earlier runs so that each shape directory contains
    # exactly the two thesis figures generated below.
    for old_figure in out_dir.glob("*.png"):
        old_figure.unlink()
    for case_name, result in case_results.items():
        case_dir = out_dir / case_name.replace("/", "_")
        case_dir.mkdir(parents=True, exist_ok=True)
        export_result(result, case_dir)

    # Figure 1 retains the detailed RL/modified target/surface visualization.
    plot_final_target_and_selected_layers(case_results["RL/modified"], out_dir)
    # Figure 2 is the requested three-case, three-layer comparison.
    plot_selected_policy_comparison(case_results, out_dir)


def print_final_table(results: List[Dict[str, Any]]) -> None:
    print("\n" + "=" * 105)
    print(
        f"{'shape / case':38s} {'RelMSE':>12s} {'MSE':>12s} {'maxOv':>12s} "
        f"{'maxUnder':>12s} {'volumeErr':>12s}"
    )
    print("-" * 105)
    for result in results:
        m = result["final_metrics"]
        label = f"{result['shape_name']} | {result['case_name']}"
        print(
            f"{label:38s} "
            f"{m['relative_mse']:12.4e} {m['mse']:12.4e} "
            f"{m['max_overshoot']:12.4e} {m['max_undershoot']:12.4e} "
            f"{m['volume_error']:12.3%}"
        )
    print("=" * 105)


# =============================================================================
# 8. Main
# =============================================================================

def main() -> None:
    np.random.seed(RANDOM_SEED)
    torch.manual_seed(RANDOM_SEED)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("2D layer-by-layer print with best_model_13")
    print(f"layers={N_LAYERS}, max thickness/layer={LAYER_THICKNESS}")
    print(f"outputs={OUTPUT_DIR}")

    model, vecnorm = load_agent(CFG)
    steps = SnakePath2D(CFG).steps()
    deposition = DepositionModel2D(CFG)
    slicer = AdaptiveSlicer(CFG, steps, deposition)
    print(f"[OK] Snake path has {len(steps)} RL steps per layer")

    all_case_results = []
    for shape_name in SHAPES_TO_RUN:
        print("\n" + "#" * 80)
        print(f"RUNNING SHAPE: {shape_name}")
        cases = {
            "Slicer/original": run_case(
                shape_name, "Slicer/original", CFG, None, None,
                steps, deposition, slicer,
                use_rl=False, execution_modified=False,
            ),
            "Slicer/modified": run_case(
                shape_name, "Slicer/modified", CFG, None, None,
                steps, deposition, slicer,
                use_rl=False, execution_modified=True,
            ),
            "RL/modified": run_case(
                shape_name, "RL/modified", CFG, model, vecnorm,
                steps, deposition, slicer,
                use_rl=True, execution_modified=True,
            ),
        }
        save_all_outputs(cases)
        all_case_results.extend(cases.values())

    print_final_table(all_case_results)
    print(f"\n[DONE] All files saved under: {OUTPUT_DIR}")


if __name__ == "__main__":
    main()