# -*- coding: utf-8 -*-
"""draft.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hroFVIwlGG0e4ROtDRAMrvdsx1AhKdVl
"""

!pip install "stable-baselines3[extra]" torch gymnasium

from dataclasses import dataclass
from math import sqrt
from pathlib import Path
from typing import Optional, Dict, Any, List, Tuple

import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import torch

from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

try:
    from IPython.display import display
except Exception:
    display = print


# ============================================================
# 2. USER SETTINGS
# ============================================================

# Change this path if your checkpoints are elsewhere.
CHECKPOINT_DIR = Path("/content/drive/MyDrive/thesis/checkpoint")

OUT_DIR = Path("/content/thesis_eval_outputs")
OUT_DIR.mkdir(parents=True, exist_ok=True)

# IMPORTANT:
# best_model_3 uses the 5 original tests.
# If you really want 9.4% instead of 2.1% for the last best_model_3 case,
# change 0.021 below to 0.094.
TEST_GROUPS = [
    {
        "model_prefix": "best_model_3",
        "checkpoint_label": "best_model_3",
        "h0_amplitudes": [0.030, 0.065, 0.076, 0.089, 0.021],
        "seeds": [1103, 2206, 3307, 4408, 5502],
    },
    {
        "model_prefix": "best_model_2",
        "checkpoint_label": "best_model_2",
        "h0_amplitudes": [0.000, 0.002, 0.020, 0.050, 0.100],
        "seeds": [6603, 7704, 8805, 4934, 11107],
    },
]

# Save separate 4-panel figures for every test as well.
SAVE_INDIVIDUAL_TEST_FIGURES = True

# Figure quality. Use 300 for faster saving, 400 for final thesis export.
FIG_DPI = 400

# Reproducibility for stochastic policy sampling.
GLOBAL_TORCH_SEED = 20260630
np.random.seed(GLOBAL_TORCH_SEED)
torch.manual_seed(GLOBAL_TORCH_SEED)


# ============================================================
# 3. CONFIG: must match training-time environment dimensions
# ============================================================

@dataclass
class ColdSpray1DConfig:
    n_bins: int = 256
    x_max: float = 1.0

    v_max: float = 1.5
    v_min: float = 1e-2
    base_v: float = 0.5
    delta_v_max: float = 1.0

    feed_rate: float = 2.0
    sigma: float = 0.02

    use_geometry_dependent_kernel: bool = True
    geometry_kernel_p: float = 1.0
    slope_smoothing_window: int = 9

    n_steps: int = 64

    v_base_gp_amplitude: float = 0.05
    gp_std: float = 1.0
    gp_lengthscale: float = 0.25
    gp_jitter: float = 1e-8

    action_penalty: float = 0.1
    smoothness_penalty: float = 10.0
    overshoot_weight: float = 10.0
    reward_scale: float = 10.0


cfg = ColdSpray1DConfig()


# ============================================================
# 4. Utility functions
# ============================================================

def kernel_gaussian(x_grid: np.ndarray, x0: float, sigma: float, dx: float) -> np.ndarray:
    z = (x_grid - x0) / sigma
    w = np.exp(-0.5 * z * z) / (sigma * sqrt(2.0 * np.pi))
    return (w * dx).astype(np.float32)


def smooth_1d_reflect(y: np.ndarray, window: int) -> np.ndarray:
    window = int(window)
    if window <= 1:
        return y.astype(np.float32, copy=True)
    if window % 2 == 0:
        window += 1
    pad = window // 2
    y_pad = np.pad(y.astype(np.float64), pad_width=pad, mode="reflect")
    ker = np.ones(window, dtype=np.float64) / float(window)
    return np.convolve(y_pad, ker, mode="valid").astype(np.float32)


def surface_slope(height: np.ndarray, dx: float, smoothing_window: int) -> np.ndarray:
    h_smooth = smooth_1d_reflect(height, smoothing_window)
    return np.gradient(h_smooth.astype(np.float64), float(dx)).astype(np.float32)


def geometry_efficiency_from_slope(slope: np.ndarray, p: float) -> np.ndarray:
    m = slope.astype(np.float64)
    eta = np.power(1.0 + m * m, -0.5 * float(p))
    return eta.astype(np.float32)


def rbf_covariance(x: np.ndarray, std: float, lengthscale: float, jitter: float) -> np.ndarray:
    x = x.astype(np.float64)
    diff = x[:, None] - x[None, :]
    K = (std ** 2) * np.exp(-0.5 * (diff / max(lengthscale, 1e-12)) ** 2)
    K += jitter * np.eye(len(x), dtype=np.float64)
    return K


def sample_zero_mean_gp(
    rng: np.random.Generator,
    x_grid: np.ndarray,
    std: float,
    lengthscale: float,
    jitter: float,
) -> np.ndarray:
    K = rbf_covariance(x_grid, std, lengthscale, jitter)
    L = np.linalg.cholesky(K)
    z = rng.standard_normal(len(x_grid))
    gp = L @ z
    gp = gp - np.mean(gp)
    return gp.astype(np.float32)


def compute_relative_mse_mean_target(
    final_height: np.ndarray,
    target: np.ndarray,
    eps: float = 1e-12,
) -> float:
    err = final_height.astype(np.float64) - target.astype(np.float64)
    mse = float(np.mean(err ** 2))
    mean_target = float(np.mean(target.astype(np.float64)))
    return mse / max(mean_target * mean_target, eps)


def compute_max_overshoot(final_height: np.ndarray, target: np.ndarray) -> float:
    return float(np.max(np.maximum(final_height - target, 0.0)))


def compute_mean_abs_error(final_height: np.ndarray, target: np.ndarray) -> float:
    return float(np.mean(np.abs(final_height.astype(np.float64) - target.astype(np.float64))))


def safe_percent_for_filename(value_percent: float) -> str:
    return f"{value_percent:.1f}".replace(".", "p")


# ============================================================
# 5. Fixed-amplitude GP profile builder
# ============================================================

@dataclass
class GPProfiles:
    x_grid: np.ndarray
    v_base_vec: np.ndarray
    target_base: np.ndarray
    target: np.ndarray
    h0_modification: np.ndarray
    baseline_deposition: np.ndarray
    g_base: np.ndarray
    g_h0: np.ndarray
    sampled_h0_mod_relative_amplitude: float


def build_fixed_h0_gp_profiles(
    cfg: ColdSpray1DConfig,
    rng: np.random.Generator,
    h0_relative_amplitude: float,
) -> GPProfiles:
    x_grid = np.linspace(0.0, cfg.x_max, cfg.n_bins, dtype=np.float32)
    dx = float(x_grid[1] - x_grid[0])

    # GP for nominal base velocity
    g_base = sample_zero_mean_gp(
        rng=rng,
        x_grid=x_grid,
        std=cfg.gp_std,
        lengthscale=cfg.gp_lengthscale,
        jitter=cfg.gp_jitter,
    )

    v_base_raw = float(cfg.base_v) + float(cfg.v_base_gp_amplitude) * g_base.astype(np.float64)
    v_base_vec = np.clip(v_base_raw, cfg.v_min, cfg.v_max).astype(np.float32)

    # Nominal Gaussian slicer target from flat h0
    baseline_deposition = (
        cfg.feed_rate * dx / np.maximum(v_base_vec, 1e-12)
    ).astype(np.float32)

    target_base = baseline_deposition.copy()
    target = np.maximum(target_base, 0.0).astype(np.float32)

    # GP for initial surface h0
    g_h0 = sample_zero_mean_gp(
        rng=rng,
        x_grid=x_grid,
        std=cfg.gp_std,
        lengthscale=cfg.gp_lengthscale,
        jitter=cfg.gp_jitter,
    )

    h0_modification = (
        float(h0_relative_amplitude)
        * float(np.mean(baseline_deposition.astype(np.float64)))
        * g_h0.astype(np.float64)
    ).astype(np.float32)

    h0_modification = (h0_modification - np.mean(h0_modification)).astype(np.float32)

    return GPProfiles(
        x_grid=x_grid.copy(),
        v_base_vec=v_base_vec.copy(),
        target_base=target_base.copy(),
        target=target.copy(),
        h0_modification=h0_modification.copy(),
        baseline_deposition=baseline_deposition.copy(),
        g_base=g_base.copy(),
        g_h0=g_h0.copy(),
        sampled_h0_mod_relative_amplitude=float(h0_relative_amplitude),
    )


# ============================================================
# 6. Self-contained evaluation environment
# ============================================================

class ColdSpray1DTestEnv(gym.Env):
    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        cfg: ColdSpray1DConfig,
        h0_relative_amplitude: float = 0.03,
        env_seed: int = 0,
    ):
        super().__init__()

        self.cfg = cfg
        self.h0_relative_amplitude = float(h0_relative_amplitude)
        self._rng = np.random.default_rng(env_seed)

        self.x_grid = np.linspace(0.0, cfg.x_max, cfg.n_bins, dtype=np.float32)
        self.dx = float(self.x_grid[1] - self.x_grid[0])
        self.ds = float(cfg.x_max / cfg.n_steps)

        obs_dim = 2 * cfg.n_bins + 4
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(obs_dim,),
            dtype=np.float32,
        )

        self.action_space = spaces.Box(
            low=np.array([-1.0], dtype=np.float32),
            high=np.array([1.0], dtype=np.float32),
            dtype=np.float32,
        )

        self.height = np.zeros(cfg.n_bins, dtype=np.float32)
        self.nozzle_x = 0.0
        self.velocity = self.cfg.base_v
        self.step_count = 0
        self._prev_velocity = self.cfg.base_v
        self.profiles: Optional[GPProfiles] = None

    def _set_profiles(self) -> None:
        self.profiles = build_fixed_h0_gp_profiles(
            cfg=self.cfg,
            rng=self._rng,
            h0_relative_amplitude=self.h0_relative_amplitude,
        )

        self.v_base_vec = self.profiles.v_base_vec.copy()
        self.target_base = self.profiles.target_base.copy()
        self.target = self.profiles.target.copy()
        self.h0_modification = self.profiles.h0_modification.copy()
        self.baseline_deposition = self.profiles.baseline_deposition.copy()
        self.g_base = self.profiles.g_base.copy()
        self.g_h0 = self.profiles.g_h0.copy()

    def _x_to_idx(self, x: float) -> int:
        return int(np.clip(np.searchsorted(self.x_grid, x, side="left"), 0, self.cfg.n_bins - 1))

    def _base_velocity_at(self, x: float) -> float:
        return float(self.v_base_vec[self._x_to_idx(x)])

    def _kernel_at(self, x0: float, height_for_slope: Optional[np.ndarray] = None) -> np.ndarray:
        k_nominal = kernel_gaussian(self.x_grid, x0, self.cfg.sigma, self.dx)

        if (not self.cfg.use_geometry_dependent_kernel) or height_for_slope is None:
            return k_nominal

        slope = surface_slope(
            height=height_for_slope,
            dx=self.dx,
            smoothing_window=self.cfg.slope_smoothing_window,
        )

        eta = geometry_efficiency_from_slope(
            slope=slope,
            p=self.cfg.geometry_kernel_p,
        )

        return (eta * k_nominal).astype(np.float32)

    def _get_obs(self) -> np.ndarray:
        delta = (self.height - self.target).astype(np.float32)

        x_norm = np.float32(self.nozzle_x / self.cfg.x_max)
        remaining = np.float32(1.0 - x_norm)
        local_base_v = np.float32(self._base_velocity_at(self.nozzle_x))

        return np.concatenate(
            [
                self.height,
                delta,
                np.array([x_norm, remaining, self.velocity, local_base_v], dtype=np.float32),
            ],
            axis=0,
        ).astype(np.float32)

    def reset(self, *, seed: Optional[int] = None, options: Optional[dict] = None):
        super().reset(seed=seed)

        if seed is not None:
            self._rng = np.random.default_rng(seed)

        self._set_profiles()

        self.height = self.h0_modification.copy()
        self.nozzle_x = 0.0
        self.velocity = self._base_velocity_at(0.0)
        self.step_count = 0
        self._prev_velocity = self.velocity

        return self._get_obs(), {}

    def step(self, action: np.ndarray):
        cfg = self.cfg
        self.step_count += 1

        action = np.asarray(action, dtype=np.float32).reshape(-1)
        local_base_v = self._base_velocity_at(self.nozzle_x)

        dv = float(np.clip(action[0], -1.0, 1.0)) * cfg.delta_v_max
        v = float(np.clip(local_base_v + dv, cfg.v_min, cfg.v_max))
        self.velocity = v

        x_prev = self.nozzle_x
        ds_eff = float(min(self.ds, cfg.x_max - self.nozzle_x))
        self.nozzle_x = float(min(cfg.x_max, self.nozzle_x + ds_eff))

        dt_step = ds_eff / v if ds_eff > 0.0 else 0.0
        m_step = cfg.feed_rate * dt_step

        L = ds_eff
        n_q = max(2, int(np.ceil(L / self.dx))) if L > 0.0 else 2

        h_old_for_kernel = self.height.copy()

        k_acc = np.zeros_like(self.height)
        for j in range(n_q):
            s_j = (j + 0.5) * L / n_q
            x_j = x_prev + s_j
            k_acc += self._kernel_at(x_j, height_for_slope=h_old_for_kernel)

        k_seg = k_acc / float(n_q)
        delta_h = (m_step * k_seg).astype(np.float32)

        h_old = self.height.copy()
        h_new = h_old + delta_h
        self.height = h_new

        def_old = np.maximum(self.target - h_old, 0.0)
        def_new = np.maximum(self.target - h_new, 0.0)
        ov_old = np.maximum(h_old - self.target, 0.0)
        ov_new = np.maximum(h_new - self.target, 0.0)

        loss_old = float(np.sum(def_old) + cfg.overshoot_weight * np.sum(ov_old))
        loss_new = float(np.sum(def_new) + cfg.overshoot_weight * np.sum(ov_new))
        reward = (loss_old - loss_new) * cfg.reward_scale

        reward -= cfg.action_penalty * (dv / cfg.delta_v_max) ** 2

        dv_smooth = (v - self._prev_velocity) / (cfg.v_max + 1e-12)
        reward -= cfg.smoothness_penalty * (dv_smooth * dv_smooth)

        self._prev_velocity = v

        err = self.height - self.target
        mse = float(np.mean(err * err))
        max_overshoot = float(np.max(np.maximum(err, 0.0)))

        terminated = False
        truncated = self.step_count >= cfg.n_steps

        info = {
            "nozzle_x": float(self.nozzle_x),
            "velocity": float(self.velocity),
            "local_base_velocity": float(local_base_v),
            "dv": float(dv),
            "mse": mse,
            "max_overshoot": max_overshoot,
            "h0_relative_amplitude": float(self.h0_relative_amplitude),
        }

        return self._get_obs(), float(reward), terminated, truncated, info


# ============================================================
# 7. Load multiple PPO + VecNormalize bundles
# ============================================================

def make_base_vec_env_for_loading() -> DummyVecEnv:
    def _factory():
        env = ColdSpray1DTestEnv(
            cfg=cfg,
            h0_relative_amplitude=0.03,
            env_seed=123,
        )
        return Monitor(env)

    return DummyVecEnv([_factory])


def check_checkpoint_files(test_groups: List[Dict[str, Any]]) -> None:
    if not CHECKPOINT_DIR.exists():
        raise FileNotFoundError(
            f"CHECKPOINT_DIR does not exist: {CHECKPOINT_DIR}\n"
            "Please mount Google Drive and/or fix CHECKPOINT_DIR."
        )

    required = []
    for group in test_groups:
        prefix = group["model_prefix"]
        required.append(CHECKPOINT_DIR / f"{prefix}.zip")
        required.append(CHECKPOINT_DIR / f"{prefix}_vecnormalize.pkl")

    missing = [p for p in required if not p.exists()]
    if missing:
        available = sorted([p.name for p in CHECKPOINT_DIR.glob("*")])
        raise FileNotFoundError(
            "Missing required checkpoint files:\n"
            + "\n".join(str(p) for p in missing)
            + "\n\nAvailable files in CHECKPOINT_DIR:\n"
            + "\n".join(available[:100])
        )


def load_model_bundle(model_prefix: str) -> Tuple[PPO, VecNormalize]:
    model_path = CHECKPOINT_DIR / f"{model_prefix}.zip"
    vecnorm_path = CHECKPOINT_DIR / f"{model_prefix}_vecnormalize.pkl"

    base_venv = make_base_vec_env_for_loading()

    venv = VecNormalize.load(str(vecnorm_path), base_venv)
    venv.training = False
    venv.norm_reward = False

    device = "cuda" if torch.cuda.is_available() else "cpu"

    model = PPO.load(
        str(model_path),
        env=venv,
        device=device,
    )

    # Shape diagnostic. This catches the most common mismatch early.
    expected_obs_dim = 2 * cfg.n_bins + 4
    actual_obs_shape = venv.observation_space.shape
    if actual_obs_shape != (expected_obs_dim,):
        raise ValueError(
            f"Observation shape mismatch for {model_prefix}: "
            f"venv.observation_space.shape = {actual_obs_shape}, "
            f"expected = {(expected_obs_dim,)}. "
            "This usually means cfg.n_bins or the environment definition does not match training."
        )

    print("=" * 80)
    print(f"Loaded model:        {model_path}")
    print(f"Loaded VecNormalize: {vecnorm_path}")
    print(f"Device:              {device}")
    print(f"Observation shape:   {actual_obs_shape}")
    print("=" * 80)

    return model, venv


check_checkpoint_files(TEST_GROUPS)

MODEL_BUNDLES: Dict[str, Dict[str, Any]] = {}
for group in TEST_GROUPS:
    prefix = group["model_prefix"]
    model_i, venv_i = load_model_bundle(prefix)
    MODEL_BUNDLES[prefix] = {
        "model": model_i,
        "venv": venv_i,
    }


# ============================================================
# 8. Rollout function
# ============================================================

def rollout_one_case(
    model: PPO,
    venv: VecNormalize,
    cfg: ColdSpray1DConfig,
    h0_relative_amplitude: float,
    env_seed: int,
    deterministic: bool = True,
    stochastic_seed_offset: int = 100000,
) -> Dict[str, Any]:
    if deterministic:
        torch.manual_seed(GLOBAL_TORCH_SEED + int(env_seed))
        np.random.seed(GLOBAL_TORCH_SEED + int(env_seed))
    else:
        torch.manual_seed(GLOBAL_TORCH_SEED + int(env_seed) + stochastic_seed_offset)
        np.random.seed(GLOBAL_TORCH_SEED + int(env_seed) + stochastic_seed_offset)

    env = ColdSpray1DTestEnv(
        cfg=cfg,
        h0_relative_amplitude=h0_relative_amplitude,
        env_seed=env_seed,
    )

    obs, _ = env.reset()

    n = cfg.n_bins

    heights: List[np.ndarray] = [obs[:n].copy()]
    xs: List[float] = [0.0]
    vs: List[float] = [float(obs[2 * n + 2])]
    local_base_vs: List[float] = [float(obs[2 * n + 3])]
    dvs: List[float] = []
    rewards: List[float] = []
    actions: List[float] = []
    mses: List[float] = []
    overshoots: List[float] = []

    for _ in range(cfg.n_steps):
        obs_norm = venv.normalize_obs(obs[None, :].astype(np.float32))
        action, _ = model.predict(obs_norm, deterministic=deterministic)

        action_env = action[0]
        obs, reward, terminated, truncated, info = env.step(action_env)

        heights.append(obs[:n].copy())
        xs.append(float(info["nozzle_x"]))
        vs.append(float(info["velocity"]))
        local_base_vs.append(float(info["local_base_velocity"]))
        dvs.append(float(info["dv"]))
        rewards.append(float(reward))
        actions.append(float(np.asarray(action_env).reshape(-1)[0]))
        mses.append(float(info["mse"]))
        overshoots.append(float(info["max_overshoot"]))

        if terminated or truncated:
            break

    heights = np.stack(heights, axis=0)

    final_height = heights[-1].copy()
    target = env.target.copy()
    h0 = env.h0_modification.copy()

    relative_mse = compute_relative_mse_mean_target(final_height, target)
    mae = compute_mean_abs_error(final_height, target)
    max_overshoot = compute_max_overshoot(final_height, target)

    return {
        "x_grid": env.x_grid.copy(),
        "target": target,
        "target_base": env.target_base.copy(),
        "h0": h0,
        "final_height": final_height,
        "heights": heights,
        "v_base_vec": env.v_base_vec.copy(),
        "vs": np.array(vs, dtype=np.float32),
        "local_base_vs": np.array(local_base_vs, dtype=np.float32),
        "dvs": np.array(dvs, dtype=np.float32),
        "xs": np.array(xs, dtype=np.float32),
        "actions": np.array(actions, dtype=np.float32),
        "rewards": np.array(rewards, dtype=np.float32),
        "mses": np.array(mses, dtype=np.float32),
        "overshoots": np.array(overshoots, dtype=np.float32),
        "h0_relative_amplitude": float(h0_relative_amplitude),
        "seed": int(env_seed),
        "relative_mse": float(relative_mse),
        "mae": float(mae),
        "max_overshoot": float(max_overshoot),
        "h0_std": float(np.std(h0)),
        "target_mean": float(np.mean(target)),
    }


# ============================================================
# 9. Run 10 tests: deterministic + stochastic for each test
# ============================================================

results: List[Dict[str, Any]] = []
global_case_counter = 1

for group in TEST_GROUPS:
    model_prefix = group["model_prefix"]
    checkpoint_label = group["checkpoint_label"]
    amplitudes = group["h0_amplitudes"]
    seeds = group["seeds"]

    if len(amplitudes) != len(seeds):
        raise ValueError(
            f"For {model_prefix}, len(h0_amplitudes)={len(amplitudes)} "
            f"but len(seeds)={len(seeds)}. They must match."
        )

    model = MODEL_BUNDLES[model_prefix]["model"]
    venv = MODEL_BUNDLES[model_prefix]["venv"]

    for local_case_index, (amp, seed) in enumerate(zip(amplitudes, seeds), start=1):
        print(
            f"Running test {global_case_counter}: "
            f"{checkpoint_label}, h0 amplitude = {100.0 * amp:.2f}%, seed = {seed}"
        )

        det_data = rollout_one_case(
            model=model,
            venv=venv,
            cfg=cfg,
            h0_relative_amplitude=amp,
            env_seed=seed,
            deterministic=True,
        )

        stoch_data = rollout_one_case(
            model=model,
            venv=venv,
            cfg=cfg,
            h0_relative_amplitude=amp,
            env_seed=seed,
            deterministic=False,
        )

        results.append(
            {
                "global_case_index": int(global_case_counter),
                "local_case_index": int(local_case_index),
                "model_prefix": model_prefix,
                "checkpoint_label": checkpoint_label,
                "det": det_data,
                "stoch": stoch_data,
                "h0_relative_amplitude": float(amp),
                "seed": int(seed),
            }
        )

        global_case_counter += 1

print(f"Finished {len(results)} tests.")


# ============================================================
# 10. Save metrics table for all 10 tests
# ============================================================

metrics_df = pd.DataFrame(
    [
        {
            "global_case": item["global_case_index"],
            "local_case_within_model": item["local_case_index"],
            "checkpoint": item["checkpoint_label"],
            "h0_GP_amplitude_percent": 100.0 * item["h0_relative_amplitude"],
            "seed": item["seed"],
            "det_relative_MSE": item["det"]["relative_mse"],
            "det_MAE": item["det"]["mae"],
            "det_max_overshoot": item["det"]["max_overshoot"],
            "stoch_relative_MSE": item["stoch"]["relative_mse"],
            "stoch_MAE": item["stoch"]["mae"],
            "stoch_max_overshoot": item["stoch"]["max_overshoot"],
            "stoch_mean_abs_delta_v": float(np.mean(np.abs(item["stoch"].get("dvs", np.array([], dtype=np.float32))))),
            "stoch_max_abs_delta_v": float(np.max(np.abs(item["stoch"].get("dvs", np.array([0.0], dtype=np.float32))))),
            "h0_std": item["det"]["h0_std"],
            "target_mean": item["det"]["target_mean"],
        }
        for item in results
    ]
)

metrics_path = OUT_DIR / "ten_h0_gp_test_metrics_det_stoch.csv"
metrics_df.to_csv(metrics_path, index=False)

display(metrics_df)
print(f"Saved metrics CSV to: {metrics_path}")


# ============================================================
# 11. Visualization helpers
# ============================================================

def format_profile_box_text(
    amp_percent: float,
    rel_mse: float,
    overshoot: float,
) -> str:
    return "\n".join(
        [
            f"h0 = {amp_percent:.2f}%",
            f"relMSE = {rel_mse:.3e}",
            f"overshoot = {overshoot:.3e}",
        ]
    )


def add_annotation_box(ax, text: str, fontsize: float = 7.0, loc: str = "upper left") -> None:
    if loc == "upper left":
        x, y, ha, va = 0.02, 0.98, "left", "top"
    elif loc == "upper right":
        x, y, ha, va = 0.98, 0.98, "right", "top"
    else:
        x, y, ha, va = 0.02, 0.98, "left", "top"

    ax.text(
        x,
        y,
        text,
        transform=ax.transAxes,
        ha=ha,
        va=va,
        fontsize=fontsize,
        bbox=dict(
            boxstyle="round",
            facecolor="white",
            alpha=0.88,
            edgecolor="0.4",
        ),
    )


def set_column_headers(axes, n_cases: int) -> None:
    headers = [
        "Deterministic",
        "Stochastic",
        "Stochastic reward",
        r"Stochastic velocity / $\delta v$",
    ]
    for j, header in enumerate(headers):
        if n_cases == 1:
            axes[j].set_title(header, fontsize=12.5, fontweight="bold")
        else:
            axes[0, j].set_title(header, fontsize=12.5, fontweight="bold")


def plot_height_panel(
    ax,
    data: Dict[str, Any],
    amp_percent: float,
    add_row_label: Optional[str] = None,
    show_legend: bool = True,
) -> None:
    x = data["x_grid"]
    target = data["target"]
    target_base = data["target_base"]
    h0 = data["h0"]
    final_height = data["final_height"]

    rel_mse = float(data["relative_mse"])
    overshoot = float(data["max_overshoot"])

    ax.plot(x, final_height, linewidth=2.0, label="height")
    ax.plot(x, target, linewidth=1.8, alpha=0.80, label="target")
    ax.plot(x, target_base, linewidth=1.8, alpha=0.80, label="target_base")
    ax.plot(x, h0, linewidth=1.5, alpha=0.80, label="h0_modification")

    y_all = np.concatenate([final_height, target, target_base, h0])
    y_min = float(np.min(y_all))
    y_max = float(np.max(y_all))
    margin = 0.10 * max(y_max - y_min, 1e-6)
    ax.set_ylim(y_min - margin, y_max + margin)

    ax.set_xlabel("x")
    ax.set_ylabel("height")

    if show_legend:
        ax.legend(loc="lower right", fontsize=6.4)

    box_text = format_profile_box_text(
        amp_percent=amp_percent,
        rel_mse=rel_mse,
        overshoot=overshoot,
    )
    add_annotation_box(ax, box_text, fontsize=6.8, loc="upper left")

    if add_row_label is not None:
        ax.text(
            -0.18,
            0.5,
            add_row_label,
            transform=ax.transAxes,
            rotation=90,
            ha="center",
            va="center",
            fontsize=8.8,
            fontweight="bold",
        )


def plot_reward_panel(
    ax,
    stoch: Dict[str, Any],
    amp_percent: float,
) -> None:
    rewards = stoch["rewards"]
    if len(rewards) > 0:
        t = np.arange(len(rewards), dtype=np.float32)
        ax.plot(t, rewards, linewidth=1.8)

    ax.set_xlabel("step")
    ax.set_ylabel("reward")

    box_text = format_profile_box_text(
        amp_percent=amp_percent,
        rel_mse=float(stoch["relative_mse"]),
        overshoot=float(stoch["max_overshoot"]),
    )
    add_annotation_box(ax, box_text, fontsize=6.8, loc="upper left")


def plot_velocity_panel(
    ax,
    stoch: Dict[str, Any],
    amp_percent: float,
) -> None:
    """Show the executed stochastic velocity and the learned residual correction delta_v.

    The environment applies

        v = clip(v_base(x) + delta_v, v_min, v_max),

    where delta_v is the residual action produced by the RL policy after scaling.
    Showing v_base, v, and delta_v makes the learned correction visible.
    """
    vs = stoch["vs"]
    local_base_vs = stoch.get("local_base_vs", np.array([], dtype=np.float32))
    dvs = stoch.get("dvs", np.array([], dtype=np.float32))

    if len(dvs) > 0:
        t = np.arange(len(dvs), dtype=np.float32)

        # v and v_base are segment quantities. Use vs[1:] and local_base_vs[1:]
        # to align them with delta_v at each rollout step.
        v_exec = vs[1: 1 + len(dvs)]
        v_base = local_base_vs[1: 1 + len(dvs)] if len(local_base_vs) > 1 else v_exec - dvs

        ax.plot(t, v_exec, linewidth=1.8, label="v")
        ax.plot(t, v_base, linewidth=1.3, linestyle="--", label=r"$v_{base}$")
        ax.set_xlabel("step")
        ax.set_ylabel("v")
        ax.legend(loc="lower left", fontsize=6.2)

        ax_delta = ax.twinx()
        ax_delta.plot(t, dvs, linewidth=1.5, linestyle=":", label=r"$\delta v$")
        ax_delta.axhline(0.0, linewidth=0.8, linestyle="--", alpha=0.6)
        ax_delta.set_ylabel(r"$\delta v$")
        ax_delta.legend(loc="lower right", fontsize=7.0)
    else:
        # Fallback for older result dictionaries.
        if len(vs) > 0:
            tv = np.arange(len(vs), dtype=np.float32)
            ax.plot(tv, vs, linewidth=1.8, label="v")
            ax.legend(loc="lower left", fontsize=7.0)
        ax.set_xlabel("step")
        ax.set_ylabel("v")

    mean_abs_dv = float(np.mean(np.abs(dvs))) if len(dvs) > 0 else 0.0
    max_abs_dv = float(np.max(np.abs(dvs))) if len(dvs) > 0 else 0.0

    box_text = "\n".join(
        [
            fr"mean|$\delta v$| = {mean_abs_dv:.3e}",
            fr"max|$\delta v$| = {max_abs_dv:.3e}",
        ]
    )
    add_annotation_box(ax, box_text, fontsize=6.2, loc="upper left")


def plot_combined_reference_style(results: List[Dict[str, Any]], out_dir: Path):
    n_cases = len(results)

    fig, axes = plt.subplots(
        n_cases,
        4,
        figsize=(20.0, 3.10 * n_cases),
        sharex=False,
    )

    if n_cases == 1:
        axes = axes[None, :]

    set_column_headers(axes, n_cases)

    for row, item in enumerate(results):
        det = item["det"]
        stoch = item["stoch"]

        amp_percent = 100.0 * item["h0_relative_amplitude"]
        checkpoint_label = item["checkpoint_label"]
        global_case = item["global_case_index"]

        row_label = f"Val {global_case}"

        plot_height_panel(
            axes[row, 0],
            det,
                amp_percent=amp_percent,
            add_row_label=row_label,
            show_legend=True,
        )
        plot_height_panel(
            axes[row, 1],
            stoch,
                amp_percent=amp_percent,
            add_row_label=None,
            show_legend=True,
        )
        plot_reward_panel(
            axes[row, 2],
            stoch,
                amp_percent=amp_percent,
        )
        plot_velocity_panel(
            axes[row, 3],
            stoch,
                amp_percent=amp_percent,
        )

    plt.tight_layout()

    png_path = out_dir / "thesis_combined_10_tests_reference_style_v4.png"
    pdf_path = out_dir / "thesis_combined_10_tests_reference_style_v4.pdf"

    fig.savefig(png_path, dpi=FIG_DPI, bbox_inches="tight")
    fig.savefig(pdf_path, bbox_inches="tight")

    plt.show()

    print(f"Saved PNG to: {png_path}")
    print(f"Saved PDF to: {pdf_path}")

    return png_path, pdf_path


png_path, pdf_path = plot_combined_reference_style(results, OUT_DIR)

def plot_single_reference_style_case(item: Dict[str, Any], out_dir: Path):
    det = item["det"]
    stoch = item["stoch"]

    global_case = item["global_case_index"]
    checkpoint_label = item["checkpoint_label"]
    amp_percent = 100.0 * item["h0_relative_amplitude"]
    amp_safe = safe_percent_for_filename(amp_percent)

    fig, axes = plt.subplots(
        1,
        4,
        figsize=(20.0, 3.8),
        sharex=False,
    )

    set_column_headers(axes, n_cases=1)

    plot_height_panel(
        axes[0],
        det,
        amp_percent=amp_percent,
        add_row_label=f"Val {global_case}",
        show_legend=True,
    )
    plot_height_panel(
        axes[1],
        stoch,
        amp_percent=amp_percent,
        add_row_label=None,
        show_legend=True,
    )
    plot_reward_panel(
        axes[2],
        stoch,
        amp_percent=amp_percent,
    )
    plot_velocity_panel(
        axes[3],
        stoch,
        amp_percent=amp_percent,
    )

    plt.tight_layout()

    png_case_path = out_dir / (
        f"test_{global_case:02d}_{checkpoint_label}_h0_{amp_safe}_reference_style_v4.png"
    )
    pdf_case_path = out_dir / (
        f"test_{global_case:02d}_{checkpoint_label}_h0_{amp_safe}_reference_style_v4.pdf"
    )

    fig.savefig(png_case_path, dpi=FIG_DPI, bbox_inches="tight")
    fig.savefig(pdf_case_path, bbox_inches="tight")
    plt.close(fig)

    return png_case_path, pdf_case_path


if SAVE_INDIVIDUAL_TEST_FIGURES:
    single_paths = []
    for item in results:
        png_case_path, pdf_case_path = plot_single_reference_style_case(
            item=item,
            out_dir=OUT_DIR,
        )
        single_paths.append((png_case_path, pdf_case_path))

    print("Saved individual case figures:")
    for png_case_path, pdf_case_path in single_paths:
        print(png_case_path)
        print(pdf_case_path)


print("\nDONE.")
print(f"Combined PNG: {png_path}")
print(f"Combined PDF: {pdf_path}")
print(f"Metrics CSV:  {metrics_path}")