# -*- coding: utf-8 -*-
"""draft-0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQvkrn9GpHcGndIaDU0OUruqUI1j-ncj
"""

!pip install "stable-baselines3[extra]" torch gymnasium

from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
from math import gamma
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any, Dict, List, Optional, Tuple
from unittest.mock import patch
import gymnasium as gym
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import numpy as np
import torch
import torch.nn as nn
from scipy.optimize import lsq_linear
from scipy.sparse.linalg import LinearOperator
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.save_util import load_from_zip_file
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize

# ---------------------------------------------------------------------------
# COLAB SETTINGS: change only these paths after uploading the two checkpoints.
# ---------------------------------------------------------------------------
MODEL_PATHS = {
    0.00: Path("/content/drive/MyDrive/thesis/checkpoint/best_model_14.zip"),
    0.05: Path("/content/drive/MyDrive/thesis/checkpoint/best_model_13.zip"),
    0.10: Path("/content/drive/MyDrive/thesis/checkpoint/best_model_13.zip"),
}
VECNORMALIZE_PATHS = {
    0.00: Path("/content/drive/MyDrive/thesis/checkpoint/best_model_14_vecnormalize.pkl"),
    0.05: Path("/content/drive/MyDrive/thesis/checkpoint/best_model_13_vecnormalize.pkl"),
    0.10: Path("/content/drive/MyDrive/thesis/checkpoint/best_model_13_vecnormalize.pkl"),
}
MODEL_PATH = MODEL_PATHS[0.05]
VECNORMALIZE_PATH = VECNORMALIZE_PATHS[0.05]
OUTPUT_DIR = Path("/content/validation_h0_gp_2d")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
SAVE_DIR = OUTPUT_DIR

# A fixed seed makes the underlying GP realization identical at 0%, 5%, 10%.
# Only its amplitude changes, so the three rows are directly comparable.
VALIDATION_SEED = 20260725
AMPLITUDES = (0.00, 0.05, 0.10)
PATH_VISUAL_SCALE = 35.0

# Thesis-size defaults.  The output is deliberately split into figures with
# exactly three columns, so text remains readable after insertion into LaTeX.
plt.rcParams.update({
    "font.size": 21,
    "axes.titlesize": 24,
    "axes.labelsize": 22,
    "legend.fontsize": 20,
    "xtick.labelsize": 19,
    "ytick.labelsize": 19,
    "lines.linewidth": 2.8,
})

CHECKPOINT_DIR = MODEL_PATH.parent

GLOBAL_RNG = np.random.default_rng()

def sample_env_seed() -> int:
    return int(GLOBAL_RNG.integers(0, int(1e7)))

class ColdSpray2DMultiInputExtractor(BaseFeaturesExtractor):
    """
    ======== CHANGED: extractor mới cho MultiInputPolicy ========

    Ý tưởng:
    - nhánh "map": dùng CNN để đọc cấu trúc không gian 2D
        + channel 0 = height
        + channel 1 = height - target
    - nhánh "state": dùng MLP nhỏ để đọc 5 scalar global
        + progress, remaining, velocity, v_base_i, offset

    Sau đó concatenate 2 nhánh lại thành 1 feature vector chung cho actor/critic.
    Đây chính là điểm khác biệt cốt lõi so với MlpPolicy cũ.
    """

    def __init__(
        self,
        observation_space: spaces.Dict,
        cnn_output_dim: int = 128,
        state_output_dim: int = 32,) -> None:

        super().__init__(observation_space, features_dim=cnn_output_dim + state_output_dim)

        map_space = observation_space["map"]
        state_space = observation_space["state"]

        if not isinstance(map_space, spaces.Box):
            raise TypeError("observation_space['map'] must be a Box")
        if not isinstance(state_space, spaces.Box):
            raise TypeError("observation_space['state'] must be a Box")

        n_map_channels = int(map_space.shape[0])
        n_state = int(state_space.shape[0])

        # ======== CHANGED: CNN branch cho map 2D ========
        # Grid hiện tại là 16x16 nên conv stride=1 + AdaptiveAvgPool2d(1) là an toàn,
        # không phụ thuộc chặt vào đúng 16x16.
        self.map_cnn = nn.Sequential(
            nn.Conv2d(n_map_channels, 16, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
            nn.Flatten(),
        )

        # Suy ra số chiều thật của CNN branch bằng 1 forward giả.
        with torch.no_grad():
            sample_map = torch.as_tensor(map_space.sample()[None]).float()
            n_flatten = int(self.map_cnn(sample_map).shape[1])

        self.map_head = nn.Sequential(
            nn.Linear(n_flatten, cnn_output_dim),
            nn.ReLU(),
        )

        # ======== CHANGED: MLP branch cho scalar/global state ========
        self.state_mlp = nn.Sequential(
            nn.Linear(n_state, 64),
            nn.ReLU(),
            nn.Linear(64, state_output_dim),
            nn.ReLU(),
        )

    def forward(self, observations: Dict[str, torch.Tensor]) -> torch.Tensor:
        map_tensor = observations["map"].float()
        state_tensor = observations["state"].float()

        map_features = self.map_head(self.map_cnn(map_tensor))
        state_features = self.state_mlp(state_tensor)

        # ======== CHANGED: ghép CNN features + scalar features ========
        return torch.cat([map_features, state_features], dim=1)

@dataclass
class ColdSpray2DConfig:
    # -------------------------------------------------------------------------
    # 1) Grid / domain
    # -------------------------------------------------------------------------
    grid_n: int = 32
    x_max: float = 1.0
    y_max: float = 1.0
    # Snake path settings copied in spirit from trial_target_2d.py
    spacing_px: int = 2
    ds: float = 0.05  # arc-length per RL step along the snake centerline

    # -------------------------------------------------------------------------
    # 2) Deposition model
    # -------------------------------------------------------------------------
    sigma: float = 0.05
    beta: float = 1.0
    eta: float = 0.4
    rho_m: float = 6500.0
    samples_per_pixel: float = 1.0
    A_amp: float = 1.0
    feed_rate: float = 2.0

    # -------------------------------------------------------------------------
    # 2b) Geometry-dependent modified kernel: execution/training only
    # -------------------------------------------------------------------------
    # Slicer and target construction always keep the original nominal kernel.
    # During RL execution:
    #   K_exec(x,y;s,h) = eta_geom(|grad h|) * K_nominal(x,y;s)
    #   eta_geom(g) = (1 + g^2)^(-p/2)
    use_geometry_dependent_kernel: bool = True
    geometry_kernel_p: float = 1.0
    slope_smoothing_window: int = 9

    # -------------------------------------------------------------------------
    # 3) Velocity / offset constraints
    # -------------------------------------------------------------------------
    v_max: float = 1.5
    v_min: float = 1e-2
    base_v: float = 0.5
    delta_v_max: float = 1.0

    # Offset uses the same residual idea as 1D, but its baseline is fixed at 0.
    # The RL action directly produces Δoffset around 0.
    off_max: float = 0.05
    offset_limit: float = 0.10

    # -------------------------------------------------------------------------
    # 4) Target construction with 2D GPs
    # -------------------------------------------------------------------------
    # ======== CHANGED: đồng bộ với file 1D ========
    # Pipeline mới cho 2D:
    #   1) sample GP 2D zero-mean
    #   2) dựng target_base = target_base_mean + target_base_gp_amplitude * g_base
    #   3) solve least squares để recover baseline velocity theo từng snake segment
    #   4) sample GP modulation khác để tạo target cuối
    target_base_mean: float = 0.05
    target_base_gp_amplitude: float = 0.01
    target_mod_relative_amplitude_min: float = 0.00
    target_mod_relative_amplitude_max: float = 0.10
    gp_std: float = 1.0
    gp_lengthscale_x: float = 0.20
    gp_lengthscale_y: float = 0.20
    gp_jitter: float = 1e-8

    # ======== CHANGED: LSQ config đồng bộ với cold-spray-2d-random-bell ========
    n_offset_lanes: int = 7
    lambda_mass = 1e-5
    lambda_step_smooth = 1e-3
    lambda_lane_smooth = 5e-4
    positive_target_weight: float = 2.5
    chunk_cols: int = 128
    basis_dtype: str = "float32"
    scratch_dir: Optional[str] = None

    # ======== CHANGED: mode switch giống file 1D ========
    # True  -> mỗi reset()/episode sẽ sample target GP mới
    # False -> dùng đúng 1 shared target GP + shared noise GP cho tất cả episode
    gp_resample_every_reset: bool = True
    # Khi gp_resample_every_reset=False, luôn dùng đúng 1 shared bundle cố định
    # cho mọi env / mọi episode / mọi rollout diagnostic.
    shared_bundle_seed: int = 0
    n_envs: int = 8

    # ======== CHANGED: dùng trực tiếp trong công thức slide v_base = v0 + a*g_base ========
    # base_v đóng vai trò v0, còn v_base_gp_amplitude đóng vai trò a.
    v_base_gp_amplitude: float = 0.25

    action_penalty_v: float = 0.10
    action_penalty_off: float = 0.10
    smoothness_penalty_v: float = 10.0
    smoothness_penalty_off: float = 10.0
    overshoot_weight: float = 10.0
    reward_scale: float = 10.0

    ppo_n_steps: int = 1024
    ppo_batch_size: int = 64
    ppo_gamma: float = 0.99
    ppo_gae_lambda: float = 0.95
    ppo_learning_rate: float = 1e-4
    ppo_clip_range: float = 0.1
    ppo_target_kl: float = 0.2
    ppo_n_epochs: int = 4
    ppo_ent_coef: float = 0.0
    ppo_vf_coef: float = 0.5
    ppo_max_grad_norm: float = 0.5
    ppo_log_std_init: float = -4.0
    total_timesteps: int = 500000000

    resume: bool = True
    resume_model_path: str = str(MODEL_PATH)
    resume_vecnormalize_path: str = str(VECNORMALIZE_PATH)
    save_freq: int = 50000


@dataclass
class GPTarget2DBundle:
    """
    Bundle target 2D hoàn chỉnh để có thể:
    - resample mỗi episode
    - hoặc giữ cố định cho mọi episode khi debug policy
    """
    v_base_vec: np.ndarray
    offset_base_vec: np.ndarray
    target_base: np.ndarray
    lsq_reconstructed_target_base: np.ndarray
    lsq_lane_mass_matrix: np.ndarray
    lsq_lane_offsets: np.ndarray
    target: np.ndarray
    h0_modification: np.ndarray
    baseline_deposition: np.ndarray
    g_base: np.ndarray
    g_mod: np.ndarray
    g_h0: np.ndarray
    target_modulation: np.ndarray
    sampled_target_base_mean_height: float
    sampled_target_mod_relative_amplitude: float
    sampled_h0_mod_relative_amplitude: float
    lsq_cost: float
    lsq_success: bool
    lsq_status: int


# =============================================================================
# Small utilities
# =============================================================================

def _save_fig(fig, filename: str, dpi: int = 160) -> str:
    SAVE_DIR.mkdir(parents=True, exist_ok=True)
    out = SAVE_DIR / filename
    fig.savefig(out, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return str(out)


# ======== CHANGED: 2D GP helpers ========
def _rbf_covariance_1d(x: np.ndarray, std: float, lengthscale: float, jitter: float = 1e-8) -> np.ndarray:
    x = x.astype(np.float64)
    diff = x[:, None] - x[None, :]
    K = (std ** 2) * np.exp(-0.5 * (diff / max(lengthscale, 1e-12)) ** 2)
    K += jitter * np.eye(len(x), dtype=np.float64)
    return K

def _sample_zero_mean_gp_2d_separable(
    rng: np.random.Generator,
    grid_n: int,
    std: float,
    lengthscale_x: float,
    lengthscale_y: float,
    jitter: float = 1e-8,
) -> np.ndarray:
    """
    ======== CHANGED: sample GP 2D zero-mean bằng covariance tách được ========
    Nếu Z ~ N(0, I), G = Ly @ Z @ Lx^T thì vec(G) có covariance K_y ⊗ K_x.
    Cách này rẻ hơn rất nhiều so với build ma trận covariance 2D khổng lồ.
    """
    grid = (np.arange(grid_n, dtype=np.float64) + 0.5) / grid_n
    Kx = _rbf_covariance_1d(grid, std=std, lengthscale=lengthscale_x, jitter=jitter)
    Ky = _rbf_covariance_1d(grid, std=std, lengthscale=lengthscale_y, jitter=jitter)
    Lx = np.linalg.cholesky(Kx)
    Ly = np.linalg.cholesky(Ky)

    Z = rng.standard_normal((grid_n, grid_n))
    G = Ly @ Z @ Lx.T
    G = G - np.mean(G)
    return G.astype(np.float32)


# ======== CHANGED: helpers for the modified 2D execution kernel ========
def _smooth_2d_reflect(height: np.ndarray, window: int) -> np.ndarray:
    """Smooth a 2D height map before evaluating its spatial gradient."""
    window = int(window)
    if window <= 1:
        return height.astype(np.float32, copy=True)
    if window % 2 == 0:
        window += 1

    pad = window // 2
    h = np.pad(height.astype(np.float64), ((pad, pad), (pad, pad)), mode="reflect")
    kernel = np.ones(window, dtype=np.float64) / float(window)
    tmp = np.apply_along_axis(
        lambda row: np.convolve(row, kernel, mode="valid"), axis=1, arr=h
    )
    out = np.apply_along_axis(
        lambda col: np.convolve(col, kernel, mode="valid"), axis=0, arr=tmp
    )
    return out.astype(np.float32)


def _surface_gradient_magnitude_2d(
    height: np.ndarray,
    dx: float,
    smoothing_window: int,
) -> np.ndarray:
    """Compute |grad h| from the smoothed pre-deposition surface."""
    h_smooth = _smooth_2d_reflect(height, smoothing_window).astype(np.float64)
    dh_dy, dh_dx = np.gradient(h_smooth, float(dx), float(dx))
    return np.sqrt(dh_dx * dh_dx + dh_dy * dh_dy).astype(np.float32)


def _geometry_efficiency_from_gradmag_2d(
    grad_mag: np.ndarray,
    p: float,
) -> np.ndarray:
    """eta_geom(g) = (1 + g^2)^(-p/2)."""
    g = grad_mag.astype(np.float64)
    return np.power(1.0 + g * g, -0.5 * float(p)).astype(np.float32)

class DepositionModel2D:
    def __init__(
        self,
        grid_n: int,
        sigma: float,
        beta: float,
        eta: float,
        rho_m: float,
        samples_per_pixel: float,
        A_amp: float,
    ) -> None:
        self.n = int(grid_n)
        self.sigma = float(sigma)
        self.beta = float(beta)
        self.eta = float(eta)
        self.rho_m = float(rho_m)
        self.spp = float(samples_per_pixel)
        self.A_amp = float(A_amp)

        self._pix_area = (1.0 / self.n) ** 2
        self._C = self.beta * self._pix_area / (
            2.0 * np.pi * (self.sigma ** 2) * gamma(2.0 / self.beta)
        )

        grid = (np.arange(self.n, dtype=np.float64) + 0.5) / self.n
        self.Y, self.X = np.meshgrid(grid, grid, indexing="ij")

    def _kernel(self, r: np.ndarray) -> np.ndarray:
        return self.A_amp * self._C * np.exp(-((r / self.sigma) ** self.beta))

    def basis_for_segment(
        self,
        x0: float,
        y0: float,
        x1: float,
        y1: float,
        height_for_slope: Optional[np.ndarray] = None,
        use_geometry_dependent_kernel: bool = False,
        geometry_kernel_p: float = 1.0,
        slope_smoothing_window: int = 9,
    ) -> np.ndarray:
        """
        Return the original nominal basis by default. Only execution/training
        supplies height_for_slope and enables the geometry-dependent factor.
        """
        dx = float(x1 - x0)
        dy = float(y1 - y0)
        L = float(np.hypot(dx, dy))

        if L < 1e-12:
            r = np.hypot(self.X - x0, self.Y - y0)
            k = self._kernel(r)
            basis = (
                k / (self.rho_m * self._pix_area * (float(np.sum(k)) + 1e-16))
            )
        else:
            ds_target = (1.0 / self.n) / max(self.spp, 1e-6)
            S = max(1, int(np.ceil(L / ds_target)))

            s = (np.arange(S, dtype=np.float64) + 0.5) * (L / S)
            xs = x0 + (dx / L) * s
            ys = y0 + (dy / L) * s

            acc = np.zeros((self.n, self.n), dtype=np.float64)
            for k in range(S):
                r = np.hypot(self.X - xs[k], self.Y - ys[k])
                acc += self._kernel(r)

            basis = (self.eta / (self.rho_m * self._pix_area)) * acc * (1.0 / S)

        if use_geometry_dependent_kernel and height_for_slope is not None:
            grad_mag = _surface_gradient_magnitude_2d(
                height=np.asarray(height_for_slope, dtype=np.float32),
                dx=1.0 / float(self.n),
                smoothing_window=slope_smoothing_window,
            )
            eta_geom = _geometry_efficiency_from_gradmag_2d(
                grad_mag=grad_mag,
                p=geometry_kernel_p,
            )
            basis = eta_geom.astype(np.float64) * basis

        return basis.astype(np.float32, copy=False)

class SnakePath2D:
    def __init__(self, cfg: ColdSpray2DConfig, grid_shape: Tuple[int, int]) -> None:
        self.cfg = cfg
        self.grid_shape = grid_shape

    @staticmethod
    def _rebuild_cumlen(pts: np.ndarray) -> np.ndarray:
        dif = pts[1:] - pts[:-1]
        seg = np.sqrt(np.sum(dif * dif, axis=1))
        return np.concatenate([[0.0], np.cumsum(seg)]).astype(np.float64)

    def build_single_snake_polyline(self) -> Tuple[np.ndarray, np.ndarray]:
        N = self.grid_shape[0]
        ix0, ix1 = 0, N - 1
        iy0, iy1 = 0, N - 1

        def pix2xy(px: int, py: int) -> Tuple[float, float]:
            return (px + 0.5) / N, (py + 0.5) / N

        pts: List[List[float]] = []
        direction = 1
        y = iy0

        while y <= iy1:
            x_start, x_end = (ix0, ix1) if direction == 1 else (ix1, ix0)
            p0 = pix2xy(x_start, y)
            p1 = pix2xy(x_end, y)

            if not pts:
                pts.append([p0[0], p0[1]])
            elif abs(pts[-1][0] - p0[0]) > 1e-12 or abs(pts[-1][1] - p0[1]) > 1e-12:
                pts.append([p0[0], p0[1]])

            pts.append([p1[0], p1[1]])

            y_next = y + self.cfg.spacing_px
            if y_next <= iy1:
                pv0 = pix2xy(x_end, y)
                pv1 = pix2xy(x_end, y_next)
                if abs(pts[-1][0] - pv0[0]) > 1e-12 or abs(pts[-1][1] - pv0[1]) > 1e-12:
                    pts.append([pv0[0], pv0[1]])
                pts.append([pv1[0], pv1[1]])

            direction *= -1
            y = y_next

        pts_np = np.asarray(pts, dtype=np.float64)
        return pts_np, self._rebuild_cumlen(pts_np)

    @staticmethod
    def pose_at_s(pts: np.ndarray, cumlen: np.ndarray, s: float) -> Tuple[float, float, float, float]:
        s_clamped = float(np.clip(s, 0.0, float(cumlen[-1])))
        i = int(np.searchsorted(cumlen, s_clamped, side="right") - 1)
        i = int(np.clip(i, 0, len(cumlen) - 2))

        s0 = float(cumlen[i])
        s1 = float(cumlen[i + 1])
        p0 = pts[i]
        p1 = pts[i + 1]

        alpha = 0.0 if (s1 - s0) < 1e-12 else (s_clamped - s0) / (s1 - s0)
        b = (1.0 - alpha) * p0 + alpha * p1

        d = p1 - p0
        L = float(np.linalg.norm(d) + 1e-12)
        tx = float(d[0] / L)
        ty = float(d[1] / L)
        return float(b[0]), float(b[1]), tx, ty

def build_fixed_steps(cfg: ColdSpray2DConfig) -> List[dict]:
    snake = SnakePath2D(cfg, (cfg.grid_n, cfg.grid_n))
    pts, cumlen = snake.build_single_snake_polyline()
    total_len = float(cumlen[-1])

    s_values = np.arange(0.0, total_len, cfg.ds, dtype=np.float64)
    if len(s_values) == 0 or s_values[-1] < total_len:
        s_values = np.append(s_values, total_len).astype(np.float64)

    steps: List[dict] = []
    for i in range(len(s_values) - 1):
        s0 = float(s_values[i])
        s1 = float(s_values[i + 1])

        x0, y0, tx0, ty0 = SnakePath2D.pose_at_s(pts, cumlen, s0)
        x1, y1, tx1, ty1 = SnakePath2D.pose_at_s(pts, cumlen, s1)

        tx = 0.5 * (tx0 + tx1)
        ty = 0.5 * (ty0 + ty1)
        L = float(np.hypot(tx, ty) + 1e-12)
        tx, ty = tx / L, ty / L
        nx, ny = -ty, tx

        steps.append(
            {
                "s0": s0,
                "s1": s1,
                "x0": x0,
                "y0": y0,
                "x1": x1,
                "y1": y1,
                "tx": tx,
                "ty": ty,
                "nx": nx,
                "ny": ny,
                "length": max(s1 - s0, 1e-8),
            }
        )
    return steps


def _clip_segment_to_domain(x0: float, y0: float, x1: float, y1: float) -> Tuple[float, float, float, float]:
    return (
        float(np.clip(x0, 0.0, 1.0)),
        float(np.clip(y0, 0.0, 1.0)),
        float(np.clip(x1, 0.0, 1.0)),
        float(np.clip(y1, 0.0, 1.0)),
    )


def _step_local_base_velocity(v_base_vec: np.ndarray, step_idx: int) -> float:
    return float(v_base_vec[int(np.clip(step_idx, 0, len(v_base_vec) - 1))])


def _sample_map_at_xy_bilinear(field: np.ndarray, x: float, y: float) -> float:
    # Bilinear interpolation on the pixel-center grid.
    #
    # IMPORTANT CHANGE:
    # We use this to read the SPATIAL GP g_base(x, y) at the center of each
    # snake segment. That gives one local scalar g_base_i per segment without
    # reverting to an index-based GP.
    n_y, n_x = field.shape
    gx = np.clip(x * n_x - 0.5, 0.0, n_x - 1.0)
    gy = np.clip(y * n_y - 0.5, 0.0, n_y - 1.0)

    x0 = int(np.floor(gx))
    x1 = min(x0 + 1, n_x - 1)
    y0 = int(np.floor(gy))
    y1 = min(y0 + 1, n_y - 1)

    wx = float(gx - x0)
    wy = float(gy - y0)

    v00 = float(field[y0, x0])
    v01 = float(field[y0, x1])
    v10 = float(field[y1, x0])
    v11 = float(field[y1, x1])

    return (
        (1.0 - wx) * (1.0 - wy) * v00
        + wx * (1.0 - wy) * v01
        + (1.0 - wx) * wy * v10
        + wx * wy * v11)

def flatten_map(M: np.ndarray) -> np.ndarray:
    return np.asarray(M, dtype=np.float64).reshape(-1)


def make_pixel_weights(cfg: ColdSpray2DConfig, target_map: np.ndarray) -> np.ndarray:
    # ======== CHANGED: weighting giống cold-spray-2d-random-bell ========
    W = np.ones_like(target_map, dtype=np.float64)
    W[target_map > 1e-12] = float(cfg.positive_target_weight)
    return W.reshape(-1)

class BasisBankMemmap:
    def __init__(self, cfg: ColdSpray2DConfig, deposition: DepositionModel2D, meta: List[dict]) -> None:
        self.cfg = cfg
        self.deposition = deposition
        self.meta = meta
        self.n_vars = len(meta)
        self.n_pix = cfg.grid_n * cfg.grid_n
        self.dtype = np.float16 if cfg.basis_dtype == "float16" else np.float32

        if cfg.scratch_dir is None:
            self._tmpdir_ctx = TemporaryDirectory()
            self.scratch_dir = Path(self._tmpdir_ctx.name)
        else:
            self._tmpdir_ctx = None
            self.scratch_dir = Path(cfg.scratch_dir)
            self.scratch_dir.mkdir(parents=True, exist_ok=True)

        self.path = self.scratch_dir / "basis_bank.dat"
        self.mm = np.memmap(
            self.path,
            dtype=self.dtype,
            mode="w+",
            shape=(self.n_vars, self.n_pix),
        )

    def build(self) -> None:
        for j, m in enumerate(self.meta):
            # ======== CHANGED: LSQ SLICER ALWAYS USES ORIGINAL KERNEL ========
            basis = self.deposition.basis_for_segment(
                m["x0"],
                m["y0"],
                m["x1"],
                m["y1"],
                height_for_slope=None,
                use_geometry_dependent_kernel=False,
            )
            self.mm[j, :] = basis.reshape(-1).astype(self.dtype, copy=False)
        self.mm.flush()

    def get_chunk(self, j0: int, j1: int, out_dtype=np.float32) -> np.ndarray:
        return np.asarray(self.mm[j0:j1, :], dtype=out_dtype)

    def close(self) -> None:
        try:
            if hasattr(self, "mm") and self.mm is not None:
                self.mm.flush()
                del self.mm
        finally:
            if self._tmpdir_ctx is not None:
                self._tmpdir_ctx.cleanup()


class LeastSquaresSlicer2DForSB3:
    """
    ======== CHANGED: LSQ formulation giống cold-spray-2d-random-bell ========
    - biến là mass w(step, lane)
    - có pixel weighting
    - có lambda_mass, lambda_step_smooth, lambda_lane_smooth
    - solve bằng LinearOperator + chunking

    Sau khi solve xong, ta collapse nghiệm mass về:
    - v_base_vec(step)
    - offset_base_vec(step)
    để phần RL hiện có vẫn dùng được.
    """
    def __init__(self, cfg: ColdSpray2DConfig, steps: List[dict]) -> None:
        self.cfg = cfg
        self.deposition = DepositionModel2D(
            grid_n=cfg.grid_n,
            sigma=cfg.sigma,
            beta=cfg.beta,
            eta=cfg.eta,
            rho_m=cfg.rho_m,
            samples_per_pixel=cfg.samples_per_pixel,
            A_amp=cfg.A_amp,
        )
        self.steps = steps
        self.offset_lanes = np.linspace(-cfg.off_max, cfg.off_max, cfg.n_offset_lanes, dtype=np.float64)

    def build_meta(self) -> List[dict]:
        meta: List[dict] = []
        for step_idx, st in enumerate(self.steps):
            for lane_idx, lane_off in enumerate(self.offset_lanes):
                x0 = float(np.clip(st["x0"] + lane_off * st["nx"], 0.0, 1.0))
                y0 = float(np.clip(st["y0"] + lane_off * st["ny"], 0.0, 1.0))
                x1 = float(np.clip(st["x1"] + lane_off * st["nx"], 0.0, 1.0))
                y1 = float(np.clip(st["y1"] + lane_off * st["ny"], 0.0, 1.0))
                meta.append({
                    "step_idx": step_idx,
                    "lane_idx": lane_idx,
                    "lane_off": float(lane_off),
                    "x0": x0,
                    "y0": y0,
                    "x1": x1,
                    "y1": y1,
                    "length": float(st["length"]),
                })
        return meta

    def _regularization_diag_counts(self, n_steps: int, lane_count: int) -> np.ndarray:
        n_vars = n_steps * lane_count
        reg_diag = np.zeros(n_vars, dtype=np.float64)

        if self.cfg.lambda_mass > 0.0:
            reg_diag += float(self.cfg.lambda_mass)

        if self.cfg.lambda_step_smooth > 0.0:
            lam = float(self.cfg.lambda_step_smooth)
            for t in range(n_steps):
                for lane in range(lane_count):
                    j = t * lane_count + lane
                    count = 0
                    if t > 0:
                        count += 1
                    if t < n_steps - 1:
                        count += 1
                    reg_diag[j] += lam * count

        if self.cfg.lambda_lane_smooth > 0.0:
            lam = float(self.cfg.lambda_lane_smooth)
            for t in range(n_steps):
                for lane in range(lane_count):
                    j = t * lane_count + lane
                    count = 0
                    if lane > 0:
                        count += 1
                    if lane < lane_count - 1:
                        count += 1
                    reg_diag[j] += lam * count

        return reg_diag

    def _compute_data_col_sq(
        self,
        basis_bank: BasisBankMemmap,
        pix_w: np.ndarray,
        chunk_cols: int,
    ) -> np.ndarray:
        n_vars = basis_bank.n_vars
        out = np.zeros(n_vars, dtype=np.float64)
        for j0 in range(0, n_vars, chunk_cols):
            j1 = min(j0 + chunk_cols, n_vars)
            chunk = basis_bank.get_chunk(j0, j1, out_dtype=np.float32)
            weighted = chunk * pix_w[None, :]
            out[j0:j1] = np.sum(weighted.astype(np.float64) ** 2, axis=1)
        return out

    def build_operator_and_rhs(
        self,
        basis_bank: BasisBankMemmap,
        meta: List[dict],
        target_map: np.ndarray,
    ) -> tuple[LinearOperator, np.ndarray, np.ndarray]:
        lane_count = self.cfg.n_offset_lanes
        n_steps = max(m["step_idx"] for m in meta) + 1
        n_vars = basis_bank.n_vars
        n_pix = basis_bank.n_pix
        chunk_cols = max(1, int(self.cfg.chunk_cols))

        pix_w = np.sqrt(make_pixel_weights(self.cfg, target_map)).astype(np.float64)
        b = flatten_map(target_map).astype(np.float64)
        b_data = b * pix_w

        n_mass = n_vars if self.cfg.lambda_mass > 0.0 else 0
        n_step = (n_steps - 1) * lane_count if self.cfg.lambda_step_smooth > 0.0 else 0
        n_lane = n_steps * (lane_count - 1) if self.cfg.lambda_lane_smooth > 0.0 else 0
        n_total = n_pix + n_mass + n_step + n_lane

        data_col_sq = self._compute_data_col_sq(basis_bank, pix_w, chunk_cols)
        reg_diag = self._regularization_diag_counts(n_steps, lane_count)
        col_scale = np.sqrt(np.maximum(data_col_sq + reg_diag, 1e-12))

        sqrt_lm = np.sqrt(self.cfg.lambda_mass) if self.cfg.lambda_mass > 0.0 else 0.0
        sqrt_ls = np.sqrt(self.cfg.lambda_step_smooth) if self.cfg.lambda_step_smooth > 0.0 else 0.0
        sqrt_ll = np.sqrt(self.cfg.lambda_lane_smooth) if self.cfg.lambda_lane_smooth > 0.0 else 0.0

        def matvec(z: np.ndarray) -> np.ndarray:
            w = z / col_scale
            parts: List[np.ndarray] = []
            y_data = np.zeros(n_pix, dtype=np.float64)
            for j0 in range(0, n_vars, chunk_cols):
                j1 = min(j0 + chunk_cols, n_vars)
                chunk = basis_bank.get_chunk(j0, j1, out_dtype=np.float32)
                y_data += chunk.T @ w[j0:j1]
            y_data *= pix_w
            parts.append(y_data)

            if n_mass > 0:
                parts.append(sqrt_lm * w)

            if n_step > 0:
                w2 = w.reshape(n_steps, lane_count)
                step_diff = (w2[:-1, :] - w2[1:, :]).reshape(-1)
                parts.append(sqrt_ls * step_diff)

            if n_lane > 0:
                w2 = w.reshape(n_steps, lane_count)
                lane_diff = (w2[:, :-1] - w2[:, 1:]).reshape(-1)
                parts.append(sqrt_ll * lane_diff)

            return np.concatenate(parts).astype(np.float64)

        def rmatvec(y: np.ndarray) -> np.ndarray:
            out = np.zeros(n_vars, dtype=np.float64)
            pos = 0

            y_data = y[pos:pos + n_pix]
            pos += n_pix
            y_data_weighted = y_data * pix_w
            for j0 in range(0, n_vars, chunk_cols):
                j1 = min(j0 + chunk_cols, n_vars)
                chunk = basis_bank.get_chunk(j0, j1, out_dtype=np.float32)
                out[j0:j1] += chunk @ y_data_weighted

            if n_mass > 0:
                y_mass = y[pos:pos + n_mass]
                pos += n_mass
                out += sqrt_lm * y_mass

            if n_step > 0:
                y_step = y[pos:pos + n_step].reshape(n_steps - 1, lane_count)
                pos += n_step
                acc = np.zeros((n_steps, lane_count), dtype=np.float64)
                acc[:-1, :] += y_step
                acc[1:, :] -= y_step
                out += sqrt_ls * acc.reshape(-1)

            if n_lane > 0:
                y_lane = y[pos:pos + n_lane].reshape(n_steps, lane_count - 1)
                pos += n_lane
                acc = np.zeros((n_steps, lane_count), dtype=np.float64)
                acc[:, :-1] += y_lane
                acc[:, 1:] -= y_lane
                out += sqrt_ll * acc.reshape(-1)

            return out / col_scale

        Aop = LinearOperator(
            shape=(n_total, n_vars),
            matvec=matvec,
            rmatvec=rmatvec,
            dtype=np.float64,
        )

        rhs_parts = [b_data]
        if n_mass > 0:
            rhs_parts.append(np.zeros(n_mass, dtype=np.float64))
        if n_step > 0:
            rhs_parts.append(np.zeros(n_step, dtype=np.float64))
        if n_lane > 0:
            rhs_parts.append(np.zeros(n_lane, dtype=np.float64))
        b_aug = np.concatenate(rhs_parts).astype(np.float64)

        return Aop, b_aug, col_scale

    def reconstruct_height_from_weights(
        self,
        basis_bank: BasisBankMemmap,
        w: np.ndarray,
    ) -> np.ndarray:
        n_pix = basis_bank.n_pix
        n_vars = basis_bank.n_vars
        chunk_cols = max(1, int(self.cfg.chunk_cols))

        h = np.zeros(n_pix, dtype=np.float64)
        for j0 in range(0, n_vars, chunk_cols):
            j1 = min(j0 + chunk_cols, n_vars)
            chunk = basis_bank.get_chunk(j0, j1, out_dtype=np.float32)
            h += chunk.T @ w[j0:j1]
        return h.reshape((self.cfg.grid_n, self.cfg.grid_n)).astype(np.float64)

    def solve(self, target_map: np.ndarray) -> Dict[str, Any]:
        meta = self.build_meta()
        basis_bank = BasisBankMemmap(self.cfg, self.deposition, meta)
        try:
            basis_bank.build()
            Aop, b_aug, col_scale = self.build_operator_and_rhs(basis_bank, meta, target_map)
            sol = lsq_linear(
                Aop,
                b_aug,
                bounds=(0.0, np.inf),
                lsmr_tol="auto",
                method="trf",
                max_iter=200,
            )
            z = sol.x.astype(np.float64)
            w = z / col_scale
            height = self.reconstruct_height_from_weights(basis_bank, w)
        finally:
            basis_bank.close()

        return {
            "w": w,
            "meta": meta,
            "height": height,
            "lsq_cost": float(sol.cost),
            "lsq_status": int(sol.status),
            "lsq_success": bool(sol.success),
        }


def _collapse_mass_solution_to_baseline_controls(
    cfg: ColdSpray2DConfig,
    steps: List[dict],
    w: np.ndarray,
    offset_lanes: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    # ======== CHANGED: quy đổi nghiệm mass(step,lane) -> baseline controls dùng trong RL ========
    n_steps = len(steps)
    lane_count = len(offset_lanes)
    W = np.asarray(w, dtype=np.float64).reshape(n_steps, lane_count)
    lane_mass_sum = np.sum(W, axis=1)

    v_base_vec = np.zeros(n_steps, dtype=np.float32)
    offset_base_vec = np.zeros(n_steps, dtype=np.float32)

    for i, st in enumerate(steps):
        total_mass_i = float(lane_mass_sum[i])
        if total_mass_i <= 1e-12:
            v_i = float(cfg.v_max)
            off_i = 0.0
        else:
            dt_i = total_mass_i / max(float(cfg.feed_rate), 1e-12)
            v_i = float(st["length"]) / max(dt_i, 1e-12)
            best_lane = int(np.argmax(W[i]))
            off_i = float(offset_lanes[best_lane])

        v_base_vec[i] = np.float32(np.clip(v_i, cfg.v_min, cfg.v_max))
        offset_base_vec[i] = np.float32(np.clip(off_i, -cfg.off_max, cfg.off_max))

    return v_base_vec, offset_base_vec, W.astype(np.float32)


def recover_baseline_controls_from_target_base_lsq_2d(
    cfg: ColdSpray2DConfig,
    steps: List[dict],
    target_base: np.ndarray,
    h0_modification: np.ndarray,
) -> Dict[str, Any]:
    """
    Legacy inverse helper kept for compatibility only.

    The active 2D target pipeline below follows the 1D idea:
    h0 GP -> g_base -> v_base -> forward deposition -> target_base.
    It does not call this LSQ helper.
    """
    target_deficit_deposition = np.maximum(
        np.asarray(target_base, dtype=np.float64) - np.asarray(h0_modification, dtype=np.float64),
        0.0,
    )

    slicer = LeastSquaresSlicer2DForSB3(cfg=cfg, steps=steps)
    sol = slicer.solve(target_map=target_deficit_deposition)
    v_base_vec, offset_base_vec, lane_mass_matrix = _collapse_mass_solution_to_baseline_controls(
        cfg=cfg,
        steps=steps,
        w=np.asarray(sol["w"], dtype=np.float64),
        offset_lanes=slicer.offset_lanes,
    )
    return {
        "v_base_vec": v_base_vec,
        "offset_base_vec": offset_base_vec,
        "lsq_reconstructed_target_base": np.asarray(sol["height"], dtype=np.float32),
        "target_deficit_deposition": np.asarray(target_deficit_deposition, dtype=np.float32),
        "lsq_lane_mass_matrix": lane_mass_matrix,
        "lsq_lane_offsets": slicer.offset_lanes.astype(np.float32),
        "lsq_cost": float(sol["lsq_cost"]),
        "lsq_success": bool(sol["lsq_success"]),
        "lsq_status": int(sol["lsq_status"]),
    }


def generate_v_base_from_modified_h0_gp_2d(
    cfg: ColdSpray2DConfig,
    steps: List[dict],
    g_base: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Direct baseline generation following the slide idea:
        v_base(i) = v0 + a * g_base(x_i, y_i)

    Here g_base is a spatial 2D zero-mean GP. For each snake segment we sample
    the GP at the segment midpoint, then map that value to the local baseline
    velocity. No least-squares recovery is used.
    """
    v_base_vec = np.zeros(len(steps), dtype=np.float32)
    offset_base_vec = np.zeros(len(steps), dtype=np.float32)

    v0 = float(cfg.base_v)
    a = float(cfg.v_base_gp_amplitude)

    for i, st in enumerate(steps):
        xc = 0.5 * (float(st["x0"]) + float(st["x1"]))
        yc = 0.5 * (float(st["y0"]) + float(st["y1"]))
        g_i = _sample_map_at_xy_bilinear(g_base, xc, yc)
        v_i = v0 + a * g_i
        v_base_vec[i] = np.float32(np.clip(v_i, cfg.v_min, cfg.v_max))

    return v_base_vec, offset_base_vec


def simulate_target_base_from_modified_h0_2d(
    cfg: ColdSpray2DConfig,
    steps: List[dict],
    h0_modification: np.ndarray,
    v_base_vec: np.ndarray,
    offset_base_vec: np.ndarray,
) -> Dict[str, Any]:
    """
    Build target_base by simulating the nominal deposition process starting from
    the modified initial surface h0_modification, not from zero.
    """
    deposition = DepositionModel2D(
        grid_n=cfg.grid_n,
        sigma=cfg.sigma,
        beta=cfg.beta,
        eta=cfg.eta,
        rho_m=cfg.rho_m,
        samples_per_pixel=cfg.samples_per_pixel,
        A_amp=cfg.A_amp,
    )

    height = np.asarray(h0_modification, dtype=np.float32).copy()

    for i, st in enumerate(steps):
        local_base_v = float(np.clip(v_base_vec[i], cfg.v_min, cfg.v_max))
        local_base_off = float(np.clip(offset_base_vec[i], -cfg.off_max, cfg.off_max))

        x0 = st["x0"] + local_base_off * st["nx"]
        y0 = st["y0"] + local_base_off * st["ny"]
        x1 = st["x1"] + local_base_off * st["nx"]
        y1 = st["y1"] + local_base_off * st["ny"]
        x0, y0, x1, y1 = _clip_segment_to_domain(x0, y0, x1, y1)

        dt_step = float(st["length"]) / max(local_base_v, 1e-12)
        m_step = float(cfg.feed_rate) * dt_step
        # ======== CHANGED: TARGET CONSTRUCTION ALWAYS USES ORIGINAL KERNEL ========
        # Explicitly disabled so cfg.use_geometry_dependent_kernel cannot affect
        # the slicer/nominal target model.
        basis = deposition.basis_for_segment(
            x0,
            y0,
            x1,
            y1,
            height_for_slope=None,
            use_geometry_dependent_kernel=False,
        )
        height = height + (m_step * basis).astype(np.float32)

    target_base = np.asarray(height, dtype=np.float32)
    baseline_deposition = (
        target_base.astype(np.float64) - np.asarray(h0_modification, dtype=np.float64)
    ).astype(np.float32)

    return {
        "target_base": target_base,
        "baseline_deposition": baseline_deposition,
        "lsq_reconstructed_target_base": baseline_deposition.copy(),
        "lsq_lane_mass_matrix": np.zeros((len(steps), cfg.n_offset_lanes), dtype=np.float32),
        "lsq_lane_offsets": np.linspace(-cfg.off_max, cfg.off_max, cfg.n_offset_lanes, dtype=np.float32),
        "lsq_cost": 0.0,
        "lsq_success": False,
        "lsq_status": -1,
    }


def build_gp_target_2d_bundle(
    rng: np.random.Generator,
    cfg: ColdSpray2DConfig,
    steps: List[dict],
) -> GPTarget2DBundle:
    """
    New pipeline requested by the user:
        1) start from h0 = 0
        2) add zero-mean GP to get h0_modification
        3) sample another zero-mean GP g_base
        4) generate v_base directly with v_base = v0 + a * g_base
        5) simulate target_base starting from h0_modification
        6) add zero-mean GP on top of target_base to get the final RL target

    No least-squares recovery is used for v_base anymore.
    """
    # Step 1-2: modified initial surface.
    g_h0 = _sample_zero_mean_gp_2d_separable(
        rng=rng,
        grid_n=cfg.grid_n,
        std=cfg.gp_std,
        lengthscale_x=cfg.gp_lengthscale_x,
        lengthscale_y=cfg.gp_lengthscale_y,
        jitter=cfg.gp_jitter,
    )
    sampled_h0_mod_relative_amplitude = float(
        rng.uniform(
            cfg.target_mod_relative_amplitude_min,
            cfg.target_mod_relative_amplitude_max,
        )
    )

    h0_modification = (
        sampled_h0_mod_relative_amplitude
        * float(cfg.target_base_mean)
        * g_h0.astype(np.float64)
    ).astype(np.float32)
    h0_modification = (h0_modification - np.mean(h0_modification)).astype(np.float32)

    # Step 3-4: baseline GP and direct baseline velocity generation.
    g_base = _sample_zero_mean_gp_2d_separable(
        rng=rng,
        grid_n=cfg.grid_n,
        std=cfg.gp_std,
        lengthscale_x=cfg.gp_lengthscale_x,
        lengthscale_y=cfg.gp_lengthscale_y,
        jitter=cfg.gp_jitter,
    )
    v_base_vec, offset_base_vec = generate_v_base_from_modified_h0_gp_2d(
        cfg=cfg,
        steps=steps,
        g_base=g_base,
    )

    # Step 5: simulate baseline target from the modified initial surface.
    base_sol = simulate_target_base_from_modified_h0_2d(
        cfg=cfg,
        steps=steps,
        h0_modification=h0_modification,
        v_base_vec=v_base_vec,
        offset_base_vec=offset_base_vec,
    )
    target_base = base_sol["target_base"]
    sampled_target_base_mean_height = float(np.mean(target_base.astype(np.float64)))

    # Step 6: final GP modification added on top of target_base.
    g_mod = _sample_zero_mean_gp_2d_separable(
        rng=rng,
        grid_n=cfg.grid_n,
        std=cfg.gp_std,
        lengthscale_x=cfg.gp_lengthscale_x,
        lengthscale_y=cfg.gp_lengthscale_y,
        jitter=cfg.gp_jitter,
    )
    # h0-only experiment: never perturb the target after it is constructed.
    sampled_target_mod_relative_amplitude = 0.0
    target_modulation = (
        sampled_target_mod_relative_amplitude
        * target_base.astype(np.float64)
        * g_mod.astype(np.float64)
    ).astype(np.float32)
    target_modulation = (target_modulation - np.mean(target_modulation)).astype(np.float32)

    target = np.maximum(target_base + target_modulation, 0.0).astype(np.float32)

    return GPTarget2DBundle(
        v_base_vec=v_base_vec.copy(),
        offset_base_vec=offset_base_vec.copy(),
        target_base=target_base.copy(),
        lsq_reconstructed_target_base=base_sol["lsq_reconstructed_target_base"].copy(),
        lsq_lane_mass_matrix=base_sol["lsq_lane_mass_matrix"].copy(),
        lsq_lane_offsets=base_sol["lsq_lane_offsets"].copy(),
        target=target.copy(),
        h0_modification=h0_modification.copy(),
        baseline_deposition=base_sol["baseline_deposition"].copy(),
        g_base=g_base.copy(),
        g_mod=g_mod.copy(),
        g_h0=g_h0.copy(),
        target_modulation=target_modulation.copy(),
        sampled_target_base_mean_height=float(sampled_target_base_mean_height),
        sampled_target_mod_relative_amplitude=float(sampled_target_mod_relative_amplitude),
        sampled_h0_mod_relative_amplitude=float(sampled_h0_mod_relative_amplitude),
        lsq_cost=float(base_sol["lsq_cost"]),
        lsq_success=bool(base_sol["lsq_success"]),
        lsq_status=int(base_sol["lsq_status"]),
    )

def build_shared_gp_target_2d_bundle(cfg: ColdSpray2DConfig, steps: List[dict], seed: int = 0) -> GPTarget2DBundle:
    """
    ======== CHANGED: tạo đúng 1 shared 2D target bundle ========
    Chỉ dùng khi gp_resample_every_reset == False.
    """
    rng = np.random.default_rng(seed)
    return build_gp_target_2d_bundle(rng=rng, cfg=cfg, steps=steps)


def compute_relative_mse_mean_target(
    final_height: np.ndarray,
    target: np.ndarray,
    eps: float = 1e-12,
) -> float:
    """
    ======== CHANGED: relative MSE giống file 1D ========
    Robust metric dùng để save best weight:
    - chuẩn hóa MSE theo mean(target)^2
    - nhờ vậy so sánh công bằng hơn giữa các episode có mean target khác nhau
    """
    err = final_height.astype(np.float64) - target.astype(np.float64)
    mse = float(np.mean(err ** 2))
    mean_target = float(np.mean(target.astype(np.float64)))
    denom = max(mean_target * mean_target, eps)
    return float(mse / denom)


# =============================================================================
# 2D RL environment
# =============================================================================

class ColdSpray2DEnv(gym.Env):
    metadata = {"render_modes": ["human"]}

    def __init__(
        self,
        cfg: ColdSpray2DConfig,
        render_mode: Optional[str] = None,
        shared_target_bundle: Optional[GPTarget2DBundle] = None,
        env_seed: int = 0,
    ):
        super().__init__()
        self.cfg = cfg
        self.render_mode = render_mode
        self.shared_target_bundle = shared_target_bundle
        self._rng = np.random.default_rng(env_seed)

        self.deposition = DepositionModel2D(
            grid_n=cfg.grid_n,
            sigma=cfg.sigma,
            beta=cfg.beta,
            eta=cfg.eta,
            rho_m=cfg.rho_m,
            samples_per_pixel=cfg.samples_per_pixel,
            A_amp=cfg.A_amp,
        )
        self.steps = build_fixed_steps(cfg)
        self.n_steps = len(self.steps)

        if (not self.cfg.gp_resample_every_reset) and self.shared_target_bundle is None:
            raise ValueError(
                "gp_resample_every_reset=False requires shared_target_bundle. "
                "You must create one shared target bundle for all episodes."
            )

        self.height = np.zeros((cfg.grid_n, cfg.grid_n), dtype=np.float32)
        self.target = np.zeros_like(self.height)
        self.target_base = np.zeros_like(self.height)
        self.target_modulation = np.zeros_like(self.height)
        # ======== CHANGED: h0_modification là initial height GP zero-mean ========
        self.h0_modification = np.zeros_like(self.height)
        self.baseline_deposition = np.zeros_like(self.height)

        self.v_base_vec = np.full(self.n_steps, fill_value=cfg.base_v, dtype=np.float32)
        self.offset_base_vec = np.zeros(self.n_steps, dtype=np.float32)
        self.lsq_reconstructed_target_base = np.zeros_like(self.height)
        self.lsq_lane_mass_matrix = np.zeros((self.n_steps, cfg.n_offset_lanes), dtype=np.float32)
        self.lsq_lane_offsets = np.linspace(-cfg.off_max, cfg.off_max, cfg.n_offset_lanes, dtype=np.float32)
        # ======== CHANGED: g_base / g_mod là GP 2D thật của target ========
        self.g_base = np.zeros((cfg.grid_n, cfg.grid_n), dtype=np.float32)
        self.g_mod = np.zeros((cfg.grid_n, cfg.grid_n), dtype=np.float32)
        self.g_h0 = np.zeros((cfg.grid_n, cfg.grid_n), dtype=np.float32)
        self.sampled_target_base_mean_height = 0.0
        self.sampled_target_mod_relative_amplitude = 0.0
        self.sampled_h0_mod_relative_amplitude = 0.0
        self.lsq_cost = 0.0
        self.lsq_success = False
        self.lsq_status = 0
        self.episode_index = 0

        self.step_idx = 0
        self.velocity = float(cfg.base_v)
        self.offset = 0.0
        self._prev_velocity = float(cfg.base_v)
        self._prev_offset = 0.0

        # ======== CHANGED: set target bundle ngay từ lúc khởi tạo env ========
        self._set_target_bundle_for_current_episode(initial=True)

        # ======== CHANGED: đổi observation từ vector phẳng sang spaces.Dict ========
        # Trước đây MlpPolicy nhận 1 vector 1D đã flatten toàn bộ map.
        # Bây giờ ta tách rõ:
        #   - "map"  : tensor (2, H, W) cho CNN
        #       + channel 0 = height
        #       + channel 1 = height - target
        #   - "state": vector 5 chiều cho MLP nhỏ
        #       + progress, remaining, velocity, v_base_i, offset
        # Đây là format tự nhiên nhất để dùng MultiInputPolicy + CNN extractor.
        self.observation_space = spaces.Dict(
            {
                "map": spaces.Box(
                    low=-np.inf,
                    high=np.inf,
                    shape=(2, cfg.grid_n, cfg.grid_n),
                    dtype=np.float32,
                ),
                "state": spaces.Box(
                    low=-np.inf,
                    high=np.inf,
                    shape=(5,),
                    dtype=np.float32,
                ),
            }
        )

        # Action = [dv_action, offset_action]; v = v_base + Δv, offset = 0 + Δoffset
        self.action_space = spaces.Box(
            low=np.array([-1.0, -1.0], dtype=np.float32),
            high=np.array([1.0, 1.0], dtype=np.float32),
            dtype=np.float32,
        )

    def _set_target_bundle_for_current_episode(self, initial: bool = False) -> None:
        """
        ======== CHANGED: mode switch thật sự ========
        - gp_resample_every_reset=True  -> mỗi episode sample target mới
        - gp_resample_every_reset=False -> reuse đúng shared target bundle
        """
        if self.cfg.gp_resample_every_reset:
            bundle = build_gp_target_2d_bundle(self._rng, self.cfg, self.steps)
        else:
            bundle = self.shared_target_bundle
            if bundle is None:
                raise RuntimeError("shared_target_bundle is required in shared-target mode.")

        self.v_base_vec = bundle.v_base_vec.copy()
        self.offset_base_vec = bundle.offset_base_vec.copy()
        self.target_base = bundle.target_base.copy()
        self.lsq_reconstructed_target_base = bundle.lsq_reconstructed_target_base.copy()
        self.lsq_lane_mass_matrix = bundle.lsq_lane_mass_matrix.copy()
        self.lsq_lane_offsets = bundle.lsq_lane_offsets.copy()
        self.target = bundle.target.copy()
        self.h0_modification = bundle.h0_modification.copy()
        self.baseline_deposition = bundle.baseline_deposition.copy()
        self.g_base = bundle.g_base.copy()
        self.g_mod = bundle.g_mod.copy()
        self.g_h0 = bundle.g_h0.copy()
        self.target_modulation = bundle.target_modulation.copy()
        self.sampled_target_base_mean_height = float(bundle.sampled_target_base_mean_height)
        self.sampled_target_mod_relative_amplitude = float(bundle.sampled_target_mod_relative_amplitude)
        self.sampled_h0_mod_relative_amplitude = float(bundle.sampled_h0_mod_relative_amplitude)
        self.lsq_cost = float(bundle.lsq_cost)
        self.lsq_success = bool(bundle.lsq_success)
        self.lsq_status = int(bundle.lsq_status)

        if not initial:
            self.episode_index += 1

    def _current_step(self) -> dict:
        idx = int(np.clip(self.step_idx, 0, self.n_steps - 1))
        return self.steps[idx]

    def _current_base_velocity(self) -> float:
        return _step_local_base_velocity(self.v_base_vec, self.step_idx)

    def _current_base_offset(self) -> float:
        return float(self.offset_base_vec[int(np.clip(self.step_idx, 0, len(self.offset_base_vec) - 1))])

    def _get_obs(self) -> Dict[str, np.ndarray]:
        progress = np.float32(self.step_idx / max(self.n_steps, 1))
        remaining = np.float32(1.0 - progress)
        v_base_i = np.float32(self._current_base_velocity())
        total_offset = np.float32(self._current_base_offset() + self.offset)

        # ======== CHANGED: map branch cho CNN ========
        map_obs = np.stack(
            [
                self.height,
                self.height - self.target,
            ],
            axis=0,
        ).astype(np.float32)

        # ======== CHANGED: scalar branch cho MLP ========
        state_obs = np.array(
            [
                progress,
                remaining,
                np.float32(self.velocity),
                v_base_i,
                total_offset,
            ],
            dtype=np.float32,
        )

        return {
            "map": map_obs,
            "state": state_obs,
        }

    def reset(self, *, seed: Optional[int] = None, options: Optional[dict] = None):
        super().reset(seed=seed)

        if seed is not None:
            self._rng = np.random.default_rng(seed)

        # ======== CHANGED: nếu True thì resample, nếu False thì reuse shared target ========
        self._set_target_bundle_for_current_episode(initial=False)

        # ======== CHANGED: initial height bây giờ là h0_modification thay vì 0 ========
        self.height = self.h0_modification.copy()
        self.step_idx = 0
        self.velocity = self._current_base_velocity()
        self.offset = 0.0
        self._prev_velocity = self.velocity
        self._prev_offset = self.offset
        return self._get_obs(), {}

    def step(self, action: np.ndarray):
        cfg = self.cfg
        st = self._current_step()
        local_base_v = self._current_base_velocity()
        local_base_off = self._current_base_offset()

        dv = float(np.clip(action[0], -1.0, 1.0)) * cfg.delta_v_max
        off_delta = float(np.clip(action[1], -1.0, 1.0)) * cfg.off_max

        v = float(np.clip(local_base_v + dv, cfg.v_min, cfg.v_max))

        # ======== CHANGED: 2D control now matches the 1D residual idea more closely.
        # Velocity remains residual around v_base: v = v_base + Δv.
        # Offset has zero baseline, so the action directly gives Δoffset around 0.
        # No accumulated offset drift: each step can choose a fresh offset in [-off_max, off_max].
        local_base_off = 0.0
        total_off = float(np.clip(local_base_off + off_delta, -cfg.offset_limit, cfg.offset_limit))
        self.offset = total_off

        self.velocity = v

        x0 = st["x0"] + total_off * st["nx"]
        y0 = st["y0"] + total_off * st["ny"]
        x1 = st["x1"] + total_off * st["nx"]
        y1 = st["y1"] + total_off * st["ny"]
        x0, y0, x1, y1 = _clip_segment_to_domain(x0, y0, x1, y1)

        dt_step = float(st["length"]) / max(v, 1e-12)
        m_step = cfg.feed_rate * dt_step

        # ======== CHANGED: PPO TRAIN/EXECUTION USES MODIFIED KERNEL ========
        # Use h before this deposition step so the geometry factor is causal.
        h_old = self.height.copy()
        basis = self.deposition.basis_for_segment(
            x0,
            y0,
            x1,
            y1,
            height_for_slope=h_old,
            use_geometry_dependent_kernel=bool(cfg.use_geometry_dependent_kernel),
            geometry_kernel_p=float(cfg.geometry_kernel_p),
            slope_smoothing_window=int(cfg.slope_smoothing_window),
        )
        delta_h = (m_step * basis).astype(np.float32)

        h_new = h_old + delta_h
        self.height = h_new

        def_old = np.maximum(self.target - h_old, 0.0)
        def_new = np.maximum(self.target - h_new, 0.0)
        ov_old = np.maximum(h_old - self.target, 0.0)
        ov_new = np.maximum(h_new - self.target, 0.0)

        # Keep the same potential-difference reward logic as the 1D code.
        loss_old = float(np.sum(def_old) + cfg.overshoot_weight * np.sum(ov_old))
        loss_new = float(np.sum(def_new) + cfg.overshoot_weight * np.sum(ov_new))
        reward = (loss_old - loss_new) * cfg.reward_scale

        reward -= cfg.action_penalty_v * (dv / max(cfg.delta_v_max, 1e-12)) ** 2
        reward -= cfg.action_penalty_off * (off_delta / max(cfg.off_max, 1e-12)) ** 2

        dv_smooth = (v - self._prev_velocity) / max(cfg.v_max, 1e-12)
        doff_smooth = (total_off - self._prev_offset) / max(cfg.offset_limit, 1e-12)
        reward -= cfg.smoothness_penalty_v * (dv_smooth ** 2)
        reward -= cfg.smoothness_penalty_off * (doff_smooth ** 2)

        self._prev_velocity = v
        self._prev_offset = total_off

        err = self.height - self.target
        mse = float(np.mean(err * err))
        ov_max = float(np.max(np.maximum(err, 0.0)))

        self.step_idx += 1
        terminated = False
        truncated = self.step_idx >= self.n_steps

        info: Dict[str, Any] = {
            "step_idx": int(self.step_idx),
            "velocity": float(v),
            "local_base_velocity": float(local_base_v),
            "offset": float(total_off),
            "local_base_offset": float(local_base_off),
            "offset_correction": float(self.offset),
            "dv": float(dv),
            "abweichung": float(off_delta),
            "dt_step": float(dt_step),
            "step_mass": float(m_step),
            "use_geometry_dependent_kernel": bool(self.cfg.use_geometry_dependent_kernel),
            "geometry_kernel_p": float(self.cfg.geometry_kernel_p),
            "slope_smoothing_window": int(self.cfg.slope_smoothing_window),
            "kernel_mode": (
                "modified_geometry_2d"
                if self.cfg.use_geometry_dependent_kernel
                else "nominal_gaussian_2d"
            ),
            "gp_resample_every_reset": bool(self.cfg.gp_resample_every_reset),
            "episode_index": int(self.episode_index),
            "g_base_mean": float(np.mean(self.g_base)),
            "g_base_std": float(np.std(self.g_base)),
            "g_mod_mean": float(np.mean(self.g_mod)),
            "g_mod_std": float(np.std(self.g_mod)),
            "target_mod_mean": float(np.mean(self.target_modulation)),
            "target_mod_std": float(np.std(self.target_modulation)),
            "h0_mod_mean": float(np.mean(self.h0_modification)),
            "h0_mod_std": float(np.std(self.h0_modification)),
            # ======== CHANGED: log thêm mean height base + relative noise amp ========
            "sampled_target_base_mean_height": float(self.sampled_target_base_mean_height),
            "sampled_target_mod_relative_amplitude": float(self.sampled_target_mod_relative_amplitude),
            "lsq_cost": float(self.lsq_cost),
            "lsq_success": bool(self.lsq_success),
            "lsq_status": int(self.lsq_status),
            "baseline_reconstruction_mse": float(np.mean((self.lsq_reconstructed_target_base - self.baseline_deposition) ** 2)),
            "mse": float(mse),
            "max_overshoot": float(ov_max),
            "x0": float(x0),
            "y0": float(y0),
            "x1": float(x1),
            "y1": float(y1),
        }
        return self._get_obs(), float(reward), terminated, truncated, info


# =============================================================================
# SB3 helpers
# =============================================================================

def relative_mse(final_height: np.ndarray, target: np.ndarray) -> float:
    """MSE normalized by mean(target)^2, as used in the training file."""
    mse = float(np.mean((final_height.astype(np.float64) - target.astype(np.float64)) ** 2))
    scale = max(float(np.mean(target.astype(np.float64))) ** 2, 1e-12)
    return mse / scale


def make_fixed_h0_bundle(
    amplitude: float,
    cfg_template: ColdSpray2DConfig,
    seed: int,
) -> Tuple[ColdSpray2DConfig, GPTarget2DBundle]:
    """
    Build one h0-only GP case.

    Setting min=max forces the requested h0 amplitude.  The target-side GP is
    fixed to zero inside build_gp_target_2d_bundle(), matching SB3 model 13.
    """
    cfg = ColdSpray2DConfig(**vars(cfg_template))
    cfg.target_mod_relative_amplitude_min = float(amplitude)
    cfg.target_mod_relative_amplitude_max = float(amplitude)
    cfg.gp_resample_every_reset = False
    cfg.n_envs = 1
    steps = build_fixed_steps(cfg)
    bundle = build_gp_target_2d_bundle(np.random.default_rng(seed), cfg, steps)
    if not np.allclose(bundle.target_modulation, 0.0):
        raise RuntimeError("h0-only validation requires target modulation = 0.")
    if amplitude == 0.0 and not np.allclose(bundle.h0_modification, 0.0):
        raise RuntimeError("The nominal 0% case requires h0 = 0.")
    if not np.isclose(bundle.sampled_h0_mod_relative_amplitude, amplitude):
        raise RuntimeError("The generated h0 amplitude does not match the requested case.")
    return cfg, bundle


def make_normalizer(
    cfg: ColdSpray2DConfig,
    bundle: GPTarget2DBundle,
    vecnormalize_path: Path,
) -> VecNormalize:
    """Attach the saved observation statistics to a harmless one-env wrapper."""
    base = DummyVecEnv(
        [lambda: ColdSpray2DEnv(cfg, shared_target_bundle=bundle, env_seed=VALIDATION_SEED)]
    )
    normalizer = VecNormalize.load(str(vecnormalize_path), base)
    normalizer.training = False
    normalizer.norm_reward = False
    return normalizer


def load_checkpoint_compatible_model(model_path: Path) -> PPO:
    """
    Load a checkpoint with the exact feature-extractor layout in its weights.

    Some model-12 checkpoints were saved with ``share_features_extractor=False``
    even though later copies of the training script omitted that flag.  In that
    case SB3 otherwise rebuilds a parameter-free CombinedExtractor, flattens
    map+state to 2053 values, and then fails to load the 160-feature checkpoint.

    This loader inspects only the checkpoint metadata/state-dict keys.  It does
    not silently discard incompatible weights and never uses ``strict=False``.
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"
    data, params, _ = load_from_zip_file(
        str(model_path),
        device=device,
        custom_objects=None,
        print_system_info=False,
    )
    if data is None or params is None or "policy" not in params:
        raise RuntimeError(f"Invalid PPO checkpoint: {model_path}")

    policy_state = params["policy"]
    state_keys = tuple(policy_state.keys())
    has_custom_extractor_weights = any(".map_cnn." in key for key in state_keys)
    has_separate_extractors = any(
        key.startswith(("pi_features_extractor.", "vf_features_extractor."))
        for key in state_keys
    )

    saved_policy_kwargs = dict(data.get("policy_kwargs") or {})
    if has_custom_extractor_weights:
        # Preserve every other saved option (net_arch, activation_fn, etc.) and
        # repair only the extractor fields that must match the state dict.
        saved_policy_kwargs["features_extractor_class"] = ColdSpray2DMultiInputExtractor
        saved_policy_kwargs["features_extractor_kwargs"] = {
            "cnn_output_dim": 128,
            "state_output_dim": 32,
        }
        saved_policy_kwargs["share_features_extractor"] = not has_separate_extractors

    load_kwargs = {
        "env": None,
        "device": device,
        "custom_objects": {"policy_kwargs": saved_policy_kwargs},
    }

    try:
        model = PPO.load(str(model_path), **load_kwargs)
    except ValueError as exc:
        # A PPO zip also stores Adam's training-only momentum/variance buffers.
        # Reconstructing an old custom policy can legitimately change Adam's
        # parameter-group bookkeeping even when every policy tensor is an exact
        # match.  Optimizer state is never used by model.predict(), so retry the
        # inference load while suppressing only Optimizer.load_state_dict().
        #
        # Importantly, nn.Module.load_state_dict() is NOT patched: all feature
        # extractor, actor and critic weights are still checked strictly by SB3.
        optimizer_group_mismatch = (
            "loaded state dict contains a parameter group" in str(exc)
            and "optimizer's group" in str(exc)
        )
        if not optimizer_group_mismatch:
            raise
        print(
            "Checkpoint policy is compatible, but its saved Adam parameter "
            "groups are training-only and incompatible. Loading for inference "
            "without optimizer state."
        )
        with patch.object(torch.optim.Optimizer, "load_state_dict", return_value=None):
            model = PPO.load(str(model_path), **load_kwargs)
    except RuntimeError as exc:
        key_summary = (
            f"custom_extractor={has_custom_extractor_weights}, "
            f"separate_actor_critic_extractors={has_separate_extractors}"
        )
        raise RuntimeError(
            "The PPO checkpoint still does not match the reconstructed model "
            f"({key_summary}). Make sure {model_path.name} and "
            "its corresponding VecNormalize file came from the same training run. "
            "Original SB3 error follows:\n"
            f"{exc}"
        ) from exc

    expected_dim = 160
    first_pi_layer = model.policy.mlp_extractor.policy_net[0]
    first_vf_layer = model.policy.mlp_extractor.value_net[0]
    if (
        not isinstance(first_pi_layer, nn.Linear)
        or not isinstance(first_vf_layer, nn.Linear)
        or first_pi_layer.in_features != expected_dim
        or first_vf_layer.in_features != expected_dim
    ):
        raise RuntimeError(
            "Checkpoint was loaded with the wrong latent feature size: "
            f"policy={getattr(first_pi_layer, 'in_features', None)}, "
            f"value={getattr(first_vf_layer, 'in_features', None)}, "
            f"expected={expected_dim}."
        )

    print(
        "Loaded PPO checkpoint successfully: "
        f"160 features, share_features_extractor={not has_separate_extractors}"
    )
    return model


def validate_normalizer_compatibility(
    model: PPO,
    normalizer: VecNormalize,
) -> None:
    """Fail early when the model and VecNormalize files are not a matching pair."""
    model_space = model.observation_space
    norm_space = normalizer.observation_space
    if not isinstance(model_space, spaces.Dict) or not isinstance(norm_space, spaces.Dict):
        raise RuntimeError("The model requires Dict observations with keys 'map' and 'state'.")
    if set(model_space.spaces) != {"map", "state"}:
        raise RuntimeError(
            f"Unexpected model observation keys: {sorted(model_space.spaces)}"
        )
    for key in ("map", "state"):
        model_shape = model_space[key].shape
        norm_shape = norm_space[key].shape
        if model_shape != norm_shape:
            raise RuntimeError(
                f"Observation shape mismatch for '{key}': "
                f"model={model_shape}, VecNormalize={norm_shape}. "
                "Use the VecNormalize file saved together with this checkpoint."
            )


def batched(obs: Dict[str, np.ndarray]) -> Dict[str, np.ndarray]:
    return {key: value[None, ...].astype(np.float32) for key, value in obs.items()}


def run_rollout(
    cfg: ColdSpray2DConfig,
    bundle: GPTarget2DBundle,
    model: Optional[PPO],
    normalizer: Optional[VecNormalize],
    deterministic: bool = True,
    rollout_seed: int = VALIDATION_SEED,
) -> Dict[str, Any]:
    """
    model=None: nominal predefined path, actions [Delta v, Delta offset] = [0, 0].
    model=PPO : deterministic learned residual corrections.
    """
    # Fix both generators so the stochastic rollout is reproducible.
    np.random.seed(rollout_seed)
    torch.manual_seed(rollout_seed)
    env = ColdSpray2DEnv(cfg, shared_target_bundle=bundle, env_seed=rollout_seed)
    obs, _ = env.reset(seed=rollout_seed)

    heights = [env.height.copy()]
    velocities: List[float] = []
    base_velocities: List[float] = []
    delta_vs: List[float] = []
    offsets: List[float] = []
    segments: List[Tuple[float, float, float, float]] = []

    while True:
        if model is None:
            action = np.zeros(2, dtype=np.float32)
        else:
            assert normalizer is not None
            normalized = normalizer.normalize_obs(batched(obs))
            predicted, _ = model.predict(normalized, deterministic=deterministic)
            action = np.asarray(predicted[0], dtype=np.float32)

        obs, _, terminated, truncated, info = env.step(action)
        heights.append(env.height.copy())
        velocities.append(float(info["velocity"]))
        base_velocities.append(float(info["local_base_velocity"]))
        delta_vs.append(float(info["dv"]))
        offsets.append(float(info["offset"]))
        segments.append((info["x0"], info["y0"], info["x1"], info["y1"]))
        if terminated or truncated:
            break

    return {
        "target": env.target.copy(),
        "target_base": env.target_base.copy(),
        "target_modulation": env.target_modulation.copy(),
        "h0": env.h0_modification.copy(),
        "final": heights[-1],
        "heights": np.stack(heights),
        "velocity": np.asarray(velocities),
        "v_base": np.asarray(base_velocities),
        "delta_v": np.asarray(delta_vs),
        "offset": np.asarray(offsets),
        "segments": np.asarray(segments),
        "rel_mse": relative_mse(heights[-1], env.target),
    }


def draw_path_comparison(
    ax,
    nominal_segments: np.ndarray,
    executed_segments: np.ndarray,
    title: str,
    visual_scale: float = PATH_VISUAL_SCALE,
):
    """Show nominal, true executed, and visually magnified path displacement."""
    from matplotlib.collections import LineCollection

    nominal = nominal_segments.reshape(-1, 2, 2)
    executed = executed_segments.reshape(-1, 2, 2)
    magnified = nominal + visual_scale * (executed - nominal)

    ax.add_collection(LineCollection(
        nominal, colors="0.25", linewidths=2.2, linestyles="dashed",
        label="predefined snake",
    ))
    ax.add_collection(LineCollection(
        executed, colors="tab:red", linewidths=2.8,
        label="executed (true scale)",
    ))
    ax.add_collection(LineCollection(
        magnified, colors="tab:blue", linewidths=2.1, alpha=0.9,
        label=fr"executed deviation $\times${visual_scale:g}",
    ))
    ax.set_xlim(0.0, 1.0)
    ax.set_ylim(0.0, 1.0)
    ax.set_aspect("equal")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.set_title(title, fontweight="bold")


def _show_height(ax, data, title, vmin, vmax, cmap="viridis"):
    im = ax.imshow(
        data, origin="lower", extent=[0, 1, 0, 1],
        cmap=cmap, vmin=vmin, vmax=vmax,
    )
    ax.set_title(title, fontweight="bold")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)


def _show_h0_difference(ax, difference, title, abs_limit):
    """
    Show h0_after_GP - nominal_h0 with a zero-centred colour scale.

    A diverging map makes positive and negative GP perturbations visible even
    when their amplitude is tiny compared with the absolute target height.
    """
    im = ax.imshow(
        difference,
        origin="lower",
        extent=[0, 1, 0, 1],
        cmap="RdBu_r",
        vmin=-abs_limit,
        vmax=abs_limit,
    )
    ax.set_title(title, fontweight="bold")
    ax.set_xlabel("x")
    ax.set_ylabel("y")
    cbar = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    #cbar.set_label(r"$h_{\mathrm{target,GP}}-h_{\mathrm{target,nominal}}$")
    cbar.formatter.set_powerlimits((-2, 2))
    cbar.update_ticks()


def plot_controls(results: Dict[float, Dict[str, Any]]) -> Path:
    """
    Figure 1: two columns only.

    Deterministic and stochastic controls are overlaid in the same velocity
    panel and the same offset panel so the comparison stays thesis-readable.
    """
    # A larger canvas and one shared legend keep every panel readable after
    # the figure is scaled down to thesis page width.
    fig, axes = plt.subplots(3, 2, figsize=(21, 17))

    for row, amp in enumerate(AMPLITUDES):
        item = results[amp]
        det = item["deterministic"]
        sto = item["stochastic"]
        t = np.arange(len(det["velocity"]))

        ax = axes[row, 0]
        ax.plot(
            t, det["v_base"], "--", color="0.20", lw=3.4,
            label=r"predefined $v_{\mathrm{base}}$",
        )
        ax.plot(
            t, det["velocity"], color="tab:blue", lw=3.1,
            label="deterministic",
        )
        ax.plot(
            t, sto["velocity"], color="tab:orange", lw=2.8, alpha=0.90,
            label="stochastic",
        )
        ax.set_title(f"{100*amp:.0f}% GP — velocity", fontweight="bold")
        ax.set_ylabel("velocity")
        # A shared x meaning is obvious across rows; write the label only on
        # the bottom row so it cannot collide with the shared legend.
        if row == len(AMPLITUDES) - 1:
            ax.set_xlabel("deposition step", labelpad=10)
        ax.grid(alpha=0.25)

        ax = axes[row, 1]
        ax.axhline(
            0.0, color="0.20", lw=3.2, ls="--",
            label="predefined offset = 0",
        )
        ax.plot(
            t, det["offset"], color="tab:blue", lw=3.1,
            label="deterministic",
        )
        ax.plot(
            t, sto["offset"], color="tab:orange", lw=2.8, alpha=0.90,
            label="stochastic",
        )
        ax.set_title(f"{100*amp:.0f}% GP — offset", fontweight="bold")
        ax.set_ylabel(r"$\Delta$offset")
        if row == len(AMPLITUDES) - 1:
            ax.set_xlabel("deposition step", labelpad=10)
        ax.grid(alpha=0.25)

    # Write the line key once for the whole diagram.  Custom handles combine
    # the two different predefined labels into one concise reference entry.
    shared_handles = [
        plt.Line2D(
            [0], [0], color="0.20", lw=3.4, ls="--",
            label=r"predefined control ($v_{\mathrm{base}}$, offset = 0)",
        ),
        plt.Line2D(
            [0], [0], color="tab:blue", lw=3.1,
            label="deterministic PPO",
        ),
        plt.Line2D(
            [0], [0], color="tab:orange", lw=2.8,
            label="stochastic PPO",
        ),
    ]
    fig.legend(
        handles=shared_handles,
        loc="lower center",
        bbox_to_anchor=(0.5, 0.012),
        ncol=3,
        frameon=False,
        handlelength=3.0,
        columnspacing=2.4,
    )

    fig.suptitle(
        "Deterministic and stochastic PPO controls",
        fontsize=30, fontweight="bold",
    )
    # Reserve explicit bands for the suptitle and the single shared legend.
    # Figure-level legends are not accounted for reliably by
    # constrained_layout, which previously caused the legend to overlap the
    # bottom-row x labels.
    fig.subplots_adjust(
        left=0.075,
        right=0.985,
        top=0.925,
        bottom=0.145,
        hspace=0.34,
        wspace=0.20,
    )
    out = OUTPUT_DIR / "figure_1_velocity_offset.png"
    fig.savefig(out, dpi=220, bbox_inches="tight", pad_inches=0.12)
    plt.close(fig)
    return out


def plot_targets_and_paths(results: Dict[float, Dict[str, Any]]) -> Path:
    """
    Figure 2: exactly three columns.

    A single nominal target | GP-induced h0 difference by amplitude |
    deterministic executed path by amplitude.
    """
    fig = plt.figure(figsize=(19, 14), constrained_layout=True)
    grid = fig.add_gridspec(3, 3, width_ratios=(1.08, 1.0, 1.0))
    nominal_ax = fig.add_subplot(grid[:, 0])
    difference_axes = [fig.add_subplot(grid[row, 1]) for row in range(3)]
    path_axes = [fig.add_subplot(grid[row, 2]) for row in range(3)]

    nominal_target = results[AMPLITUDES[0]]["target"]
    vmin = float(np.min(nominal_target))
    vmax = float(np.max(nominal_target))

    differences = {
        # nominal h0 is the zero surface, so this is h0_GP - h0_nominal.
        amp: results[amp]["h0"]
        for amp in AMPLITUDES
    }
    difference_abs_limit = max(
        float(np.max(np.abs(difference)))
        for difference in differences.values()
    )
    # Avoid a singular colour normalization if every requested GP amplitude is 0.
    difference_abs_limit = max(difference_abs_limit, np.finfo(float).eps)

    # The nominal target is identical for all GP amplitudes, so show it once.
    _show_height(
        nominal_ax,
        nominal_target,
        "Nominal target",
        vmin,
        vmax,
    )

    for row, amp in enumerate(AMPLITUDES):
        item = results[amp]
        percentage_title = f"{100*amp:.0f}%"
        _show_h0_difference(
            difference_axes[row],
            differences[amp],
            percentage_title,
            difference_abs_limit,
        )
        draw_path_comparison(
            path_axes[row],
            item["baseline"]["segments"],
            item["deterministic"]["segments"],
            percentage_title,
        )

    # Column labels belong below the last diagrams; the diagram titles above
    # remain the perturbation levels only (0%, 5%, and 10%).
    difference_axes[-1].set_xlabel(
        r"$h_0$ difference", fontweight="bold", labelpad=12
    )
    path_axes[-1].set_xlabel(
        "Deterministic path", fontweight="bold", labelpad=12
    )

    # One shared legend, outside all axes, so it never covers the snake path.
    legend_handles, legend_labels = path_axes[0].get_legend_handles_labels()
    fig.legend(
        legend_handles,
        legend_labels,
        loc="upper center",
        bbox_to_anchor=(0.5, -0.01),
        ncol=3,
        frameon=False,
        handlelength=3.2,
        columnspacing=2.2,
    )

    fig.suptitle(
        r"Nominal target, GP-induced $h_0$ difference, and deterministic executed path",
        fontsize=24, fontweight="bold",
    )
    out = OUTPUT_DIR / "figure_2_h0_difference_path.png"
    fig.savefig(out, dpi=220, bbox_inches="tight")
    plt.close(fig)
    return out


def plot_combined_validation(results: Dict[float, Dict[str, Any]]) -> Path:
    """
    One thesis-ready vertical figure with two visually independent blocks.

    The control legend belongs only to the upper block, while the path legend
    belongs only to the lower block.  Dedicated GridSpec rows prevent either
    legend, the global title, or any axis label from overlapping another item.
    """
    fig = plt.figure(figsize=(22, 34))
    outer = fig.add_gridspec(
        5, 1,
        height_ratios=(10.0, 0.75, 0.55, 10.0, 0.85),
        left=0.070, right=0.975, top=0.945, bottom=0.030,
        hspace=0.16,
    )

    # ------------------------ upper block: controls ------------------------
    control_grid = outer[0].subgridspec(3, 2, hspace=0.36, wspace=0.22)
    control_axes = np.empty((3, 2), dtype=object)
    for row in range(3):
        for col in range(2):
            control_axes[row, col] = fig.add_subplot(control_grid[row, col])

    for row, amp in enumerate(AMPLITUDES):
        item = results[amp]
        det = item["deterministic"]
        sto = item["stochastic"]
        t = np.arange(len(det["velocity"]))

        ax = control_axes[row, 0]
        ax.plot(t, det["v_base"], "--", color="0.20", lw=3.4)
        ax.plot(t, det["velocity"], color="tab:blue", lw=3.1)
        ax.plot(
            t, sto["velocity"], color="tab:orange", lw=2.8, alpha=0.90
        )
        ax.set_title(f"{100*amp:.0f}% GP — velocity", fontweight="bold")
        ax.set_ylabel("velocity")
        if row == len(AMPLITUDES) - 1:
            ax.set_xlabel("deposition step", labelpad=10)
        ax.grid(alpha=0.25)

        ax = control_axes[row, 1]
        ax.axhline(0.0, color="0.20", lw=3.2, ls="--")
        ax.plot(t, det["offset"], color="tab:blue", lw=3.1)
        ax.plot(
            t, sto["offset"], color="tab:orange", lw=2.8, alpha=0.90
        )
        ax.set_title(f"{100*amp:.0f}% GP — offset", fontweight="bold")
        ax.set_ylabel(r"$\Delta$offset")
        if row == len(AMPLITUDES) - 1:
            ax.set_xlabel("deposition step", labelpad=10)
        ax.grid(alpha=0.25)

    control_legend_ax = fig.add_subplot(outer[1])
    control_legend_ax.axis("off")
    control_handles = [
        plt.Line2D(
            [0], [0], color="0.20", lw=3.4, ls="--",
            label=r"predefined control ($v_{\mathrm{base}}$, offset = 0)",
        ),
        plt.Line2D(
            [0], [0], color="tab:blue", lw=3.1,
            label="deterministic PPO",
        ),
        plt.Line2D(
            [0], [0], color="tab:orange", lw=2.8,
            label="stochastic PPO",
        ),
    ]
    control_legend_ax.legend(
        handles=control_handles,
        loc="center",
        ncol=3,
        frameon=False,
        fontsize=22,
        handlelength=3.0,
        columnspacing=2.4,
    )

    # A real empty row keeps the two figure blocks visually separate.
    spacer_ax = fig.add_subplot(outer[2])
    spacer_ax.axis("off")

    # ---------------- lower block: target, difference, path ----------------
    lower_grid = outer[3].subgridspec(
        3, 3, width_ratios=(1.08, 1.0, 1.0), hspace=0.36, wspace=0.28
    )
    nominal_ax = fig.add_subplot(lower_grid[:, 0])
    difference_axes = [
        fig.add_subplot(lower_grid[row, 1]) for row in range(3)
    ]
    path_axes = [fig.add_subplot(lower_grid[row, 2]) for row in range(3)]

    nominal_target = results[AMPLITUDES[0]]["target"]
    vmin = float(np.min(nominal_target))
    vmax = float(np.max(nominal_target))
    differences = {
        amp: results[amp]["h0"] for amp in AMPLITUDES
    }
    difference_abs_limit = max(
        max(float(np.max(np.abs(x))) for x in differences.values()),
        np.finfo(float).eps,
    )

    _show_height(
        nominal_ax,
        nominal_target,
        "Nominal target",
        vmin,
        vmax,
    )

    for row, amp in enumerate(AMPLITUDES):
        item = results[amp]
        percentage_title = f"{100*amp:.0f}%"
        _show_h0_difference(
            difference_axes[row],
            differences[amp],
            percentage_title,
            difference_abs_limit,
        )
        draw_path_comparison(
            path_axes[row],
            item["baseline"]["segments"],
            item["deterministic"]["segments"],
            percentage_title,
        )

    # Column labels belong below the last diagrams; the diagram titles above
    # remain the perturbation levels only (0%, 5%, and 10%).
    difference_axes[-1].set_xlabel(
        r"$h_0$ difference", fontweight="bold", labelpad=12
    )
    path_axes[-1].set_xlabel(
        "Deterministic path", fontweight="bold", labelpad=12
    )

    path_legend_ax = fig.add_subplot(outer[4])
    path_legend_ax.axis("off")
    path_handles, path_labels = path_axes[0].get_legend_handles_labels()
    path_legend_ax.legend(
        path_handles,
        path_labels,
        loc="center",
        ncol=3,
        frameon=False,
        fontsize=22,
        handlelength=3.2,
        columnspacing=2.2,
    )

    fig.suptitle(
        r"Controls, nominal target, GP-induced $h_0$ difference, "
        "and executed path",
        fontsize=32,
        fontweight="bold",
        y=0.982,
    )
    out = OUTPUT_DIR / "figure_combined_h0_gp_validation.png"
    fig.savefig(out, dpi=220, facecolor="white")
    plt.close(fig)
    return out


def save_metrics(results: Dict[float, Dict[str, Any]]) -> Path:
    out = OUTPUT_DIR / "h0_gp_validation_metrics.csv"
    rows = [
        "h0_gp_amplitude,predefined_rel_mse,deterministic_rel_mse,"
        "stochastic_rel_mse,deterministic_improvement_percent,"
        "stochastic_improvement_percent"
    ]
    for amp in AMPLITUDES:
        b = results[amp]["baseline"]["rel_mse"]
        d = results[amp]["deterministic"]["rel_mse"]
        s = results[amp]["stochastic"]["rel_mse"]
        d_imp = 100.0 * (b - d) / max(b, 1e-12)
        s_imp = 100.0 * (b - s) / max(b, 1e-12)
        rows.append(
            f"{amp:.2f},{b:.10e},{d:.10e},{s:.10e},{d_imp:.6f},{s_imp:.6f}"
        )
    out.write_text("\n".join(rows) + "\n", encoding="utf-8")
    return out


def main() -> None:
    required_paths = set(MODEL_PATHS.values()) | set(VECNORMALIZE_PATHS.values())
    missing = [path for path in sorted(required_paths, key=str) if not path.exists()]
    if missing:
        formatted = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(
            "Upload all required model/VecNormalize checkpoints:\n" + formatted
        )

    template = ColdSpray2DConfig()
    results: Dict[float, Dict[str, Any]] = {}
    loaded_models: Dict[Path, PPO] = {}

    for amp in AMPLITUDES:
        model_path = MODEL_PATHS[amp]
        vecnormalize_path = VECNORMALIZE_PATHS[amp]
        if model_path not in loaded_models:
            loaded_models[model_path] = load_checkpoint_compatible_model(model_path)
        model = loaded_models[model_path]

        print(f"\nRunning h0-GP amplitude {100*amp:.0f}% ...")
        print(f"  model: {model_path.name}")
        print(f"  VecNormalize: {vecnormalize_path.name}")
        cfg, bundle = make_fixed_h0_bundle(amp, template, VALIDATION_SEED)
        normalizer = make_normalizer(cfg, bundle, vecnormalize_path)
        validate_normalizer_compatibility(model, normalizer)

        baseline = run_rollout(
            cfg, bundle, model=None, normalizer=None,
            deterministic=True, rollout_seed=VALIDATION_SEED,
        )
        deterministic = run_rollout(
            cfg, bundle, model=model, normalizer=normalizer,
            deterministic=True, rollout_seed=VALIDATION_SEED,
        )
        stochastic = run_rollout(
            cfg, bundle, model=model, normalizer=normalizer,
            deterministic=False, rollout_seed=VALIDATION_SEED + 1000 + int(100 * amp),
        )
        results[amp] = {
            "target": bundle.target.copy(),
            "target_base": bundle.target_base.copy(),
            "h0": bundle.h0_modification.copy(),
            "baseline": baseline,
            "deterministic": deterministic,
            "stochastic": stochastic,
        }
        print(
            f"  predefined relMSE = {baseline['rel_mse']:.6e} | "
            f"deterministic PPO = {deterministic['rel_mse']:.6e} | "
            f"stochastic PPO = {stochastic['rel_mse']:.6e}"
        )
        normalizer.close()

    outputs = [plot_combined_validation(results), save_metrics(results)]
    print("\nSaved outputs:")
    for path in outputs:
        print(f"  {path}")


if __name__ == "__main__":
    main()