# -*- coding: utf-8 -*-
"""hard_compare_policies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQeOu5vKmqpftmbgJucNrEAnYaa3btTx
"""

!pip install -q stable-baselines3 gymnasium

from __future__ import annotations
import json
import math
import subprocess
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
import numpy as np
import matplotlib.pyplot as plt

AUTO_INSTALL = True

try:
    import gymnasium as gym
    from gymnasium import spaces
    from stable_baselines3 import PPO
    from stable_baselines3.common.monitor import Monitor
    from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
except Exception:  # noqa: BLE001
    if not AUTO_INSTALL:
        raise
    print("[INFO] Installing stable-baselines3 and gymnasium...")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "-q", "stable-baselines3", "gymnasium"]
    )
    import gymnasium as gym
    from gymnasium import spaces
    from stable_baselines3 import PPO
    from stable_baselines3.common.monitor import Monitor
    from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize


# =============================================================================
# 1. User settings
# =============================================================================

ORIGINAL_MODEL_ZIP = "/content/drive/MyDrive/thesis/checkpoint/best_model_3_geo.zip"
ORIGINAL_VECNORMALIZE_PKL = "/content/drive/MyDrive/thesis/checkpoint/best_model_3_geo_vecnormalize.pkl"

MODIFIED_MODEL_ZIP = "/content/drive/MyDrive/thesis/checkpoint/best_model_2_geo.zip"
MODIFIED_VECNORMALIZE_PKL = "/content/drive/MyDrive/thesis/checkpoint/best_model_2_geo_vecnormalize.pkl"

OUTPUT_DIR = "/content/demo_1d_4case_hard_shape_auto_search"
EVAL_SEED = 111

USE_TRAINED_AGENTS = True
DETERMINISTIC_ACTION = True

# Object: print a 1D part over [0, 1] with final mean height about 0.2.
# CHANGED: the old rectangle target is kept as a sanity-check option,
# but the default is now a harder sinusoidal layer target.
# Reason: a flat rectangle is too easy; slicer/original is expected to be almost perfect.
X_START = 0.0
X_END = 1.0
N_LAYERS = 10
LAYER_THICKNESS = 0.02

# CHANGED HARD-SHAPE DEMO:
# Target type for the layer-by-layer mismatch demo.
#
# Recommended for mentor demo:
#   "hard_double_bump"  -> two local features with different widths and amplitudes.
#                         This creates stronger local slopes than a sine wave,
#                         so the geometry-dependent modified kernel becomes visible.
#
# Other options:
#   "rectangle"         -> sanity check: flat layer, too easy for slicer/original.
#   "sine"              -> smooth periodic slope, moderate difficulty.
#   "bump"              -> one smooth Gaussian bump.
#   "ramp"              -> global inclined layer.
#   "smooth_step"       -> smooth transition from low to high material demand.
#   "edge_bump"         -> one bump close to an edge; useful to expose boundary errors.
#   "gp_like"           -> deterministic smooth GP-like mixture of sinusoidal modes.
#
# The target increment is normalized to keep mean(delta_h) ~= LAYER_THICKNESS.
# CHANGED AUTO-SEARCH DEMO:
# The user goal is to find a target shape where
#     relative MSE(RL / modified) < relative MSE(Slicer / original)
# and relative MSE(RL / modified) < relative MSE(Slicer / modified).
#
# Important scientific note:
# Slicer/original is an ideal reference case, so it is normally very strong.
# Therefore this file does NOT hard-code the conclusion.  Instead, it tries
# several difficult but smooth target shapes and automatically selects the one
# where RL/modified has the clearest relative-MSE advantage, if such a case exists.
AUTO_SELECT_SHAPE = False
TARGET_MODE = "rectangle"
TARGET_AMPLITUDE = 0.005
BUMP_SIGMA = 0.08
SMOOTH_STEP_K = 22.0

# Candidate search space used when AUTO_SELECT_SHAPE=True.
# These shapes are designed to expose limitations of the pointwise slicer:
# narrow local peaks, asymmetric edges, and high curvature.  They are still
# smooth enough to be physically more reasonable than discontinuous hard steps.
CANDIDATE_SHAPES = [
    ("sharp_double_peak", 0.010),
    ("sharp_double_peak", 0.014),
    ("sharp_double_peak", 0.018),
    ("sharp_double_peak", 0.022),
    ("edge_peak", 0.010),
    ("edge_peak", 0.014),
    ("edge_peak", 0.018),
    ("smooth_cliff_peak", 0.010),
    ("smooth_cliff_peak", 0.014),
    ("smooth_cliff_peak", 0.018),
    ("high_curvature_wave", 0.008),
    ("high_curvature_wave", 0.012),
    ("hard_double_bump", 0.010),
    ("hard_double_bump", 0.014),
]

# Must match trained 1D policies.
N_BINS = 256
N_STEPS = 64

SIGMA = 0.02
FEED_RATE = 2.0
V_MIN = 1e-2
V_MAX = 1.5
BASE_V = 0.5
DELTA_V_MAX = 1.0

GEOMETRY_P = 1.0
SLOPE_SMOOTHING_WINDOW = 9

# Default False because best_model_2 in compare_policies.py was trained with
# the mentor geometry-dependent kernel, not the later SOD idea.
USE_SOD_IN_MODIFIED_KERNEL = False
NOMINAL_STANDOFF_DISTANCE = 0.02
SOD_OPTIMAL_DISTANCE = 0.02
SOD_SIGMA = 0.02
SOD_ETA_MIN = 0.20


# =============================================================================
# 2. Config and mathematical helpers
# =============================================================================

@dataclass
class ColdSpray1DConfig:
    n_bins: int = N_BINS
    x_max: float = 1.0
    n_steps: int = N_STEPS

    v_min: float = V_MIN
    v_max: float = V_MAX
    base_v: float = BASE_V
    delta_v_max: float = DELTA_V_MAX

    feed_rate: float = FEED_RATE
    sigma: float = SIGMA

    use_geometry_dependent_kernel: bool = False
    geometry_kernel_p: float = GEOMETRY_P
    slope_smoothing_window: int = SLOPE_SMOOTHING_WINDOW

    use_sod_dependent_kernel: bool = USE_SOD_IN_MODIFIED_KERNEL
    nominal_standoff_distance: float = NOMINAL_STANDOFF_DISTANCE
    sod_optimal_distance: float = SOD_OPTIMAL_DISTANCE
    sod_sigma: float = SOD_SIGMA
    sod_eta_min: float = SOD_ETA_MIN

    ppo_n_steps: int = 256
    ppo_batch_size: int = 64
    ppo_gamma: float = 0.99
    ppo_gae_lambda: float = 0.95
    ppo_learning_rate: float = 1e-4
    ppo_clip_range: float = 0.1
    ppo_target_kl: float = 0.05
    ppo_n_epochs: int = 4
    ppo_ent_coef: float = 0.0
    ppo_vf_coef: float = 0.5
    ppo_max_grad_norm: float = 0.5
    ppo_log_std_init: float = -4.0


def gaussian_kernel_discrete(
    x_grid: np.ndarray,
    center: float,
    sigma: float,
    dx: float,
) -> np.ndarray:
    """
    Discrete nominal Gaussian kernel.

    K_i = K_sigma(x_i - center) * dx, so sum_i K_i is approximately one.
    """
    z = (x_grid - float(center)) / max(float(sigma), 1e-12)
    w = np.exp(-0.5 * z * z) / (float(sigma) * math.sqrt(2.0 * math.pi))
    return (w * float(dx)).astype(np.float32)


def smooth_1d_reflect(y: np.ndarray, window: int) -> np.ndarray:
    window = int(window)
    if window <= 1:
        return y.astype(np.float32, copy=True)
    if window % 2 == 0:
        window += 1
    pad = window // 2
    y_pad = np.pad(y.astype(np.float64), pad_width=pad, mode="reflect")
    kernel = np.ones(window, dtype=np.float64) / float(window)
    return np.convolve(y_pad, kernel, mode="valid").astype(np.float32)


def surface_slope(height: np.ndarray, dx: float, smoothing_window: int) -> np.ndarray:
    h_smooth = smooth_1d_reflect(height, smoothing_window)
    return np.gradient(h_smooth.astype(np.float64), float(dx)).astype(np.float32)


def geometry_efficiency_from_slope(slope: np.ndarray, p: float) -> np.ndarray:
    """eta_geom(m) = (1 + m^2)^(-p/2)."""
    m = slope.astype(np.float64)
    eta = np.power(1.0 + m * m, -0.5 * float(p))
    return eta.astype(np.float32)


def sod_efficiency_from_height(
    height: np.ndarray,
    nominal_standoff_distance: float,
    sod_optimal_distance: float,
    sod_sigma: float,
    sod_eta_min: float,
) -> np.ndarray:
    """Optional SOD factor for future experiments."""
    sigma_d = max(float(sod_sigma), 1e-12)
    eta_min = float(np.clip(sod_eta_min, 0.0, 1.0))
    d_local = float(nominal_standoff_distance) - height.astype(np.float64)
    z = (d_local - float(sod_optimal_distance)) / sigma_d
    eta = eta_min + (1.0 - eta_min) * np.exp(-0.5 * z * z)
    return np.clip(eta, eta_min, 1.0).astype(np.float32)


def execution_kernel(
    x_grid: np.ndarray,
    center: float,
    height_for_geometry: np.ndarray,
    cfg: ColdSpray1DConfig,
    dx: float,
) -> np.ndarray:
    """
    Original:
        K_exec = K_sigma

    Modified:
        K_exec = eta_geom(dh/dx) * K_sigma

    Optional SOD:
        K_exec = eta_geom(dh/dx) * eta_sod(d) * K_sigma

    The Gaussian footprint is not widened and is not re-normalized.
    """
    k = gaussian_kernel_discrete(x_grid, center, cfg.sigma, dx)

    if not cfg.use_geometry_dependent_kernel:
        return k

    slope = surface_slope(height_for_geometry, dx, cfg.slope_smoothing_window)
    eta_geom = geometry_efficiency_from_slope(slope, cfg.geometry_kernel_p)

    if cfg.use_sod_dependent_kernel:
        eta_sod = sod_efficiency_from_height(
            height=height_for_geometry,
            nominal_standoff_distance=cfg.nominal_standoff_distance,
            sod_optimal_distance=cfg.sod_optimal_distance,
            sod_sigma=cfg.sod_sigma,
            sod_eta_min=cfg.sod_eta_min,
        )
    else:
        eta_sod = np.ones_like(k, dtype=np.float32)

    return (eta_geom * eta_sod * k).astype(np.float32)


def profile_metrics(height: np.ndarray, target: np.ndarray) -> Dict[str, float]:
    h = height.astype(np.float64)
    t = target.astype(np.float64)
    err = h - t
    ov = np.maximum(err, 0.0)
    uf = np.maximum(-err, 0.0)
    mse = float(np.mean(err ** 2))
    mean_t = float(np.mean(np.abs(t)))
    rel_mse = mse / max(mean_t * mean_t, 1e-12)
    return {
        "mse": mse,
        "rel_mse": rel_mse,
        "mae": float(np.mean(np.abs(err))),
        "max_abs_error": float(np.max(np.abs(err))),
        "max_overshoot": float(np.max(ov)),
        "mean_overshoot": float(np.mean(ov)),
        "max_underfill": float(np.max(uf)),
        "mean_underfill": float(np.mean(uf)),
    }


# =============================================================================
# 3. Dummy environment for loading VecNormalize and PPO
# =============================================================================

class DummyColdSprayBoxEnv(gym.Env):
    """
    Dummy environment with the same observation shape as the 1D training files:
        [height(256), height-target(256), x_norm, remaining, velocity, local_base_v]
        dimension = 2*n_bins + 4 = 516.
    """
    metadata = {"render_modes": []}

    def __init__(self, cfg: ColdSpray1DConfig):
        super().__init__()
        obs_dim = 2 * int(cfg.n_bins) + 4
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(obs_dim,),
            dtype=np.float32,
        )
        self.action_space = spaces.Box(
            low=np.array([-1.0], dtype=np.float32),
            high=np.array([1.0], dtype=np.float32),
            dtype=np.float32,
        )

    def reset(self, seed: Optional[int] = None, options: Optional[dict] = None):
        return np.zeros(self.observation_space.shape, dtype=np.float32), {}

    def step(self, action):
        obs = np.zeros(self.observation_space.shape, dtype=np.float32)
        return obs, 0.0, False, True, {}


def make_dummy_vec_env(cfg: ColdSpray1DConfig) -> DummyVecEnv:
    return DummyVecEnv([lambda: Monitor(DummyColdSprayBoxEnv(cfg))])


def load_vecnormalize(path: str, cfg: ColdSpray1DConfig) -> Optional[VecNormalize]:
    p = Path(path)
    if not p.exists():
        print(f"[WARN] VecNormalize not found: {p}")
        return None
    dummy = make_dummy_vec_env(cfg)
    vec = VecNormalize.load(str(p), dummy)
    vec.training = False
    vec.norm_reward = False
    print(f"[OK] Loaded VecNormalize: {p}")
    return vec


def load_ppo(path: str) -> Optional[PPO]:
    p = Path(path)
    if not p.exists():
        print(f"[WARN] PPO model not found: {p}")
        return None
    model = PPO.load(str(p), device="cpu")
    print(f"[OK] Loaded PPO model: {p}")
    return model


def normalize_obs(obs: np.ndarray, vecnorm: Optional[VecNormalize]) -> np.ndarray:
    obs_batch = obs[None, :].astype(np.float32)
    if vecnorm is None:
        return obs_batch
    return vecnorm.normalize_obs(obs_batch)


# =============================================================================
# 4. Slicer and rollout logic
# =============================================================================

def build_x_grid(cfg: ColdSpray1DConfig) -> Tuple[np.ndarray, float, float]:
    x_grid = np.linspace(0.0, cfg.x_max, cfg.n_bins, dtype=np.float32)
    dx = float(x_grid[1] - x_grid[0])
    ds = float(cfg.x_max / cfg.n_steps)
    return x_grid, dx, ds


def layer_increment_target(x_grid: np.ndarray) -> np.ndarray:
    """
    CHANGED HARD-SHAPE TARGET GENERATOR.

    The old rectangle target is kept as a sanity check, but the default target
    is now "hard_double_bump".  The reason is important for the mentor demo:

        rectangle  -> slicer/original is almost perfect; no correction needed.
        hard shape -> stronger slopes and local curvature; the modified
                      geometry-dependent execution kernel creates visible
                      mismatch; RL correction has something meaningful to fix.

    We build a one-layer target increment Delta h(x), then normalize its mean
    over the active region to LAYER_THICKNESS.  Therefore after 10 layers the
    average final height is still approximately 0.2.
    """
    left = min(float(X_START), float(X_END))
    right = max(float(X_START), float(X_END))
    mask = (x_grid >= left) & (x_grid <= right)

    target = np.zeros_like(x_grid, dtype=np.float32)
    x = x_grid.astype(np.float64)

    # Helper: normalize any positive raw profile so that mean over the active
    # print region equals LAYER_THICKNESS.  This keeps all target modes
    # comparable in total deposited material.
    def _normalize_increment(raw: np.ndarray) -> np.ndarray:
        raw = np.asarray(raw, dtype=np.float64)
        raw = np.maximum(raw, 1e-4)
        active_mean = float(np.mean(raw[mask])) if np.any(mask) else float(np.mean(raw))
        return raw * (float(LAYER_THICKNESS) / max(active_mean, 1e-12))

    if TARGET_MODE == "rectangle":
        raw = np.full_like(x, float(LAYER_THICKNESS), dtype=np.float64)

    elif TARGET_MODE == "sine":
        # Smooth single-frequency target. Moderate difficulty.
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * np.sin(2.0 * np.pi * x)

    elif TARGET_MODE == "bump":
        # One centered Gaussian bump. Good simple local feature.
        bump = np.exp(-0.5 * ((x - 0.50) / max(float(BUMP_SIGMA), 1e-12)) ** 2)
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * bump

    elif TARGET_MODE == "hard_double_bump":
        # CHANGED DEFAULT:
        # Two asymmetric bumps with different widths, plus a shallow valley.
        # This creates local slopes and curvature while staying smooth enough
        # for a Gaussian deposition model.  It is harder than sine and better
        # for showing geometry-dependent model mismatch.
        bump1 = np.exp(-0.5 * ((x - 0.28) / 0.075) ** 2)
        bump2 = 0.75 * np.exp(-0.5 * ((x - 0.72) / 0.120) ** 2)
        valley = 0.45 * np.exp(-0.5 * ((x - 0.50) / 0.110) ** 2)
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (bump1 + bump2 - valley)

    elif TARGET_MODE == "sharp_double_peak":
        # CHANGED: hard target intended to make the pointwise slicer less ideal.
        # Two narrow smooth peaks plus a small valley create high local curvature.
        # Because the slicer uses a very simple local inverse while execution is
        # a convolution with a finite Gaussian footprint, this target can produce
        # visible model/planning error even for Slicer/original.
        peak1 = 1.00 * np.exp(-0.5 * ((x - 0.27) / 0.040) ** 2)
        peak2 = 0.85 * np.exp(-0.5 * ((x - 0.68) / 0.050) ** 2)
        valley = 0.55 * np.exp(-0.5 * ((x - 0.48) / 0.080) ** 2)
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (peak1 + peak2 - valley)

    elif TARGET_MODE == "edge_peak":
        # CHANGED: a narrow feature near the boundary.
        # Boundary effects are difficult for a Gaussian footprint and can make
        # Slicer/original less perfect, while the RL correction may compensate
        # by changing velocity locally.
        peak = 1.15 * np.exp(-0.5 * ((x - 0.88) / 0.045) ** 2)
        shoulder = 0.45 * np.exp(-0.5 * ((x - 0.34) / 0.130) ** 2)
        valley = 0.35 * np.exp(-0.5 * ((x - 0.62) / 0.090) ** 2)
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (peak + shoulder - valley)

    elif TARGET_MODE == "smooth_cliff_peak":
        # CHANGED: smooth step + local peak.
        # This creates a high-slope transition region without using a
        # discontinuous, physically unrealistic hard step.
        step = np.tanh(float(SMOOTH_STEP_K) * (x - 0.54))
        peak = np.exp(-0.5 * ((x - 0.30) / 0.055) ** 2)
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (0.50 * step + 0.90 * peak)

    elif TARGET_MODE == "high_curvature_wave":
        # CHANGED: deterministic multi-frequency wave.
        # Compared with a simple sine, this has higher curvature and several
        # local extrema, which makes the pointwise slicer less accurate.
        raw = (
            float(LAYER_THICKNESS)
            + float(TARGET_AMPLITUDE) * (
                0.75 * np.sin(2.0 * np.pi * x + 0.20)
                + 0.45 * np.sin(6.0 * np.pi * x - 0.60)
                + 0.25 * np.cos(10.0 * np.pi * x + 0.90)
            )
        )

    elif TARGET_MODE == "edge_bump":
        # A bump close to the right boundary. This is useful because boundary
        # effects plus local slope often make slicer-only execution worse.
        bump = np.exp(-0.5 * ((x - 0.83) / 0.070) ** 2)
        shoulder = 0.55 * np.exp(-0.5 * ((x - 0.35) / 0.16) ** 2)
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (bump + 0.4 * shoulder)

    elif TARGET_MODE == "ramp":
        # Global inclined layer. Useful for testing slope-dependent deposition.
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (x - 0.5)

    elif TARGET_MODE == "smooth_step":
        # Smooth low-to-high transition. This is more physical than a hard step
        # and creates a localized high-slope transition region.
        step = 1.0 / (1.0 + np.exp(-float(SMOOTH_STEP_K) * (x - 0.52)))
        raw = float(LAYER_THICKNESS) + float(TARGET_AMPLITUDE) * (step - np.mean(step[mask]))

    elif TARGET_MODE == "gp_like":
        # Deterministic smooth GP-like target: mixture of low-frequency modes.
        # This is useful as a robustness target without using random sampling.
        raw = (
            float(LAYER_THICKNESS)
            + float(TARGET_AMPLITUDE) * (
                0.75 * np.sin(2.0 * np.pi * x + 0.30)
                + 0.40 * np.sin(4.0 * np.pi * x - 0.80)
                + 0.25 * np.cos(6.0 * np.pi * x + 0.50)
            )
        )

    else:
        raise ValueError(
            f"Unknown TARGET_MODE={TARGET_MODE!r}. Use 'rectangle', 'sine', 'bump', "
            f"'hard_double_bump', 'edge_bump', 'ramp', 'smooth_step', or 'gp_like'."
        )

    inc = _normalize_increment(raw)
    target[mask] = inc[mask].astype(np.float32)
    return target


def cumulative_target(x_grid: np.ndarray, layer_index: int) -> np.ndarray:
    return float(layer_index) * layer_increment_target(x_grid)


def slicer_base_velocity_profile(
    x_grid: np.ndarray,
    layer_target_increment: np.ndarray,
    cfg: ColdSpray1DConfig,
    dx: float,
) -> np.ndarray:
    """
    Simple nominal slicer velocity profile.

    The nominal relation from the training setup is approximately:
        desired_increment(x) = feed_rate * dx / v_base(x)

    Hence:
        v_base(x) = feed_rate * dx / desired_increment(x)

    Outside the object region the simplified model has no spray on/off command,
    so the slicer uses maximum velocity to minimize unwanted deposition.
    """
    eps = 1e-12
    v = np.full_like(x_grid, fill_value=float(cfg.v_max), dtype=np.float32)
    mask = layer_target_increment > eps
    v[mask] = float(cfg.feed_rate) * float(dx) / np.maximum(layer_target_increment[mask], eps)
    return np.clip(v, cfg.v_min, cfg.v_max).astype(np.float32)


def x_to_idx(x_grid: np.ndarray, x: float) -> int:
    return int(np.clip(np.searchsorted(x_grid, x, side="left"), 0, len(x_grid) - 1))


def value_at_x(x_grid: np.ndarray, values: np.ndarray, x: float) -> float:
    return float(values[x_to_idx(x_grid, x)])


def make_policy_observation(
    layer_height: np.ndarray,
    layer_target_increment: np.ndarray,
    x_norm: float,
    velocity: float,
    local_base_v: float,
) -> np.ndarray:
    """
    Observation for trained 1D PPO policies.

    For layer-by-layer application, the policy sees the current layer in local
    coordinates:
        layer_height = global_height - height_at_start_of_current_layer

    This avoids feeding cumulative heights up to 0.2 into a policy trained on
    one-layer profiles around 0.02. The physical kernel is still evaluated on
    the global height profile.
    """
    delta = (layer_height - layer_target_increment).astype(np.float32)
    remaining = np.float32(1.0 - x_norm)
    obs = np.concatenate(
        [
            layer_height.astype(np.float32),
            delta,
            np.array([x_norm, remaining, velocity, local_base_v], dtype=np.float32),
        ],
        axis=0,
    )
    return obs.astype(np.float32)


@dataclass
class CaseSpec:
    name: str
    short_name: str
    cfg: ColdSpray1DConfig
    model: Optional[PPO] = None
    vecnorm: Optional[VecNormalize] = None
    use_agent: bool = False


def simulate_case(case: CaseSpec, eval_seed: int = EVAL_SEED) -> Dict[str, Any]:
    _ = np.random.default_rng(eval_seed)  # reserved for future noise switches

    cfg = case.cfg
    x_grid, dx, ds = build_x_grid(cfg)

    height = np.zeros_like(x_grid, dtype=np.float32)
    one_layer_target = layer_increment_target(x_grid)

    layer_heights: List[np.ndarray] = []
    layer_targets: List[np.ndarray] = []
    layer_metrics: List[Dict[str, float]] = []
    all_velocities: List[List[float]] = []
    all_actions: List[List[float]] = []
    # CHANGED: store what the agent actually does.
    # v_base comes from the slicer, dv is the RL correction, and v = v_base + dv.
    all_base_velocities: List[List[float]] = []
    all_dvs: List[List[float]] = []
    # CHANGED: adaptive slicer. Store the full v_base profile planned at the
    # beginning of each layer, because v_base is no longer the same for all layers.
    all_v_base_profiles: List[np.ndarray] = []
    all_desired_layer_increments: List[np.ndarray] = []

    for layer in range(1, N_LAYERS + 1):
        h_start_layer = height.copy()

        # CHANGED: adaptive slicer planning is done ONCE PER LAYER.
        # The old code computed
        #     v_base_vec = slicer_base_velocity_profile(one_layer_target)
        # once before the layer loop and reused it for all layers.
        # Now the slicer looks at the current accumulated height at the start
        # of this layer and asks: "how much material is still needed to reach
        # the cumulative target after this layer?"
        #
        # target_after_layer(x) = layer * Delta h_target(x)
        # desired_increment_this_layer(x) = target_after_layer(x) - h_start_layer(x)
        # Negative values mean the point is already overfilled, so the slicer
        # requests zero additional material there, which maps to v_max.
        target_after_layer = cumulative_target(x_grid, layer)
        desired_increment_this_layer = np.maximum(
            target_after_layer.astype(np.float32) - h_start_layer.astype(np.float32),
            0.0,
        ).astype(np.float32)

        # CHANGED: v_base_vec is now recomputed for this layer only.
        v_base_vec = slicer_base_velocity_profile(
            x_grid=x_grid,
            layer_target_increment=desired_increment_this_layer,
            cfg=cfg,
            dx=dx,
        )
        all_v_base_profiles.append(v_base_vec.copy())
        all_desired_layer_increments.append(desired_increment_this_layer.copy())

        velocities_this_layer: List[float] = []
        actions_this_layer: List[float] = []
        base_velocities_this_layer: List[float] = []
        dvs_this_layer: List[float] = []

        nozzle_x = 0.0
        prev_velocity = value_at_x(x_grid, v_base_vec, 0.0)

        for _step in range(cfg.n_steps):
            x_prev = nozzle_x
            ds_eff = float(min(ds, cfg.x_max - nozzle_x))
            x_next = float(min(cfg.x_max, nozzle_x + ds_eff))

            x_mid = x_prev + 0.5 * ds_eff
            x_norm = np.float32(x_prev / cfg.x_max)
            local_base_v = value_at_x(x_grid, v_base_vec, x_mid)

            if case.use_agent and case.model is not None:
                layer_height = (height - h_start_layer).astype(np.float32)
                obs = make_policy_observation(
                    layer_height=layer_height,
                    # CHANGED: the policy receives the adaptive per-layer
                    # target increment, not the fixed nominal one_layer_target.
                    layer_target_increment=desired_increment_this_layer,
                    x_norm=float(x_norm),
                    velocity=float(prev_velocity),
                    local_base_v=float(local_base_v),
                )
                obs_model = normalize_obs(obs, case.vecnorm)
                action, _ = case.model.predict(obs_model, deterministic=DETERMINISTIC_ACTION)
                action_scalar = float(np.asarray(action).reshape(-1)[0])
                dv = float(np.clip(action_scalar, -1.0, 1.0)) * cfg.delta_v_max
            else:
                action_scalar = 0.0
                dv = 0.0

            v = float(np.clip(local_base_v + dv, cfg.v_min, cfg.v_max))
            velocities_this_layer.append(v)
            actions_this_layer.append(action_scalar)
            # CHANGED: log adaptive slicer velocity and RL velocity correction.
            base_velocities_this_layer.append(float(local_base_v))
            dvs_this_layer.append(float(dv))

            # Average a few kernel samples inside the segment, following the training-file style.
            L = ds_eff
            n_q = max(2, int(np.ceil(L / dx))) if L > 0.0 else 2
            h_old_for_kernel = height.copy()
            k_acc = np.zeros_like(height, dtype=np.float32)

            for j in range(n_q):
                s_j = (j + 0.5) * L / n_q
                x_j = x_prev + s_j
                k_acc += execution_kernel(
                    x_grid=x_grid,
                    center=x_j,
                    height_for_geometry=h_old_for_kernel,
                    cfg=cfg,
                    dx=dx,
                )

            k_seg = k_acc / float(n_q)
            dt_step = ds_eff / max(v, 1e-12)
            m_step = cfg.feed_rate * dt_step
            height = (height + (m_step * k_seg).astype(np.float32)).astype(np.float32)

            nozzle_x = x_next
            prev_velocity = v

        layer_heights.append(height.copy())
        layer_targets.append(target_after_layer.copy())
        layer_metrics.append(profile_metrics(height, target_after_layer))
        all_velocities.append(velocities_this_layer)
        all_actions.append(actions_this_layer)
        all_base_velocities.append(base_velocities_this_layer)
        all_dvs.append(dvs_this_layer)

    final_target = cumulative_target(x_grid, N_LAYERS)
    return {
        "name": case.name,
        "short_name": case.short_name,
        "cfg": asdict(cfg),
        "kernel_mode": "modified" if cfg.use_geometry_dependent_kernel else "original",
        "uses_sod": bool(cfg.use_sod_dependent_kernel),
        "use_agent": bool(case.use_agent and case.model is not None),
        "x_grid": x_grid,
        "one_layer_target": one_layer_target,
        # CHANGED: old scripts expected v_base_vec. Keep a backward-compatible
        # representative profile, but the real adaptive data is v_base_profiles.
        "v_base_vec": all_v_base_profiles[0].copy(),
        "v_base_profiles": np.stack(all_v_base_profiles, axis=0),
        "desired_layer_increments": np.stack(all_desired_layer_increments, axis=0),
        "layer_heights": np.stack(layer_heights, axis=0),
        "layer_targets": np.stack(layer_targets, axis=0),
        "layer_metrics": layer_metrics,
        "velocities": np.array(all_velocities, dtype=np.float32),
        "actions": np.array(all_actions, dtype=np.float32),
        # CHANGED: these arrays are needed to answer the mentor's question
        # "what does the agent actually do?"
        "base_velocities": np.array(all_base_velocities, dtype=np.float32),
        "dvs": np.array(all_dvs, dtype=np.float32),
        "final_height": layer_heights[-1],
        "final_target": final_target,
        "final_metrics": profile_metrics(layer_heights[-1], final_target),
    }


# =============================================================================
# 5. Plotting
# =============================================================================

# Thesis-ready typography.  The figures are intentionally large because they
# are normally reduced to page width when inserted into the thesis.
FIGURE_TITLE_SIZE = 24
PANEL_TITLE_SIZE = 18
AXIS_LABEL_SIZE = 17
TICK_LABEL_SIZE = 15
LEGEND_SIZE = 14
ANNOTATION_SIZE = 17
LINE_WIDTH = 2.6
MARKER_SIZE = 8


def style_axis(ax: Any) -> None:
    """Apply one consistent, readable thesis style to a Matplotlib axis."""
    ax.tick_params(axis="both", which="major", labelsize=TICK_LABEL_SIZE)
    ax.grid(alpha=0.25)

def ensure_output_dir() -> Path:
    out_dir = Path(OUTPUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir


def plot_target_shape(out_dir: Path) -> Path:
    """
    CHANGED: save a small figure showing the selected target shape.
    This helps explain to the mentor why this target is harder than a rectangle.
    """
    cfg_tmp = ColdSpray1DConfig(use_geometry_dependent_kernel=False)
    x_grid, _, _ = build_x_grid(cfg_tmp)
    one_layer = layer_increment_target(x_grid)
    final_target = float(N_LAYERS) * one_layer

    fig, axes = plt.subplots(1, 2, figsize=(12, 3.2))
    axes[0].plot(x_grid, one_layer, linewidth=2.0)
    axes[0].axhline(LAYER_THICKNESS, linestyle="--", linewidth=1.2, alpha=0.8, label="mean layer thickness")
    axes[0].set_title(f"One-layer target increment: {TARGET_MODE}")
    axes[0].set_xlabel("x")
    axes[0].set_ylabel(r"$\Delta h^*(x)$")
    axes[0].grid(alpha=0.25)
    axes[0].legend(fontsize=8)

    axes[1].plot(x_grid, final_target, linewidth=2.0)
    axes[1].axhline(N_LAYERS * LAYER_THICKNESS, linestyle="--", linewidth=1.2, alpha=0.8, label="mean final height")
    axes[1].set_title("Final target after all layers")
    axes[1].set_xlabel("x")
    axes[1].set_ylabel(r"$h^*(x)$")
    axes[1].grid(alpha=0.25)
    axes[1].legend(fontsize=8)

    fig.tight_layout()
    out_path = out_dir / "00_target_shape_preview.png"
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.show()
    plt.close(fig)
    return out_path


def plot_prof_summary(results: List[Dict[str, Any]], out_dir: Path) -> Path:
    fig, axes = plt.subplots(2, 2, figsize=(22, 14))
    ax_final, ax_mae, ax_max_ov, ax_mean_ov = axes.ravel()

    x = results[0]["x_grid"]
    final_target = results[0]["final_target"].copy()
    final_target_plot = final_target.copy()
    final_target_plot[final_target_plot <= 0.0] = np.nan

    ax_final.plot(x, final_target_plot, "k--", linewidth=3.2, label="target")
    for r in results:
        m = r["final_metrics"]
        ax_final.plot(
            x,
            r["final_height"],
            linewidth=LINE_WIDTH,
            label=f"{r['short_name']} | RelMSE={m['rel_mse']:.3e}, maxOv={m['max_overshoot']:.3e}",
        )
    ax_final.set_title("Final height after all layers", fontsize=PANEL_TITLE_SIZE, pad=12)
    ax_final.set_xlabel("x", fontsize=AXIS_LABEL_SIZE)
    ax_final.set_ylabel("height", fontsize=AXIS_LABEL_SIZE)
    style_axis(ax_final)
    # Keep the legend fully INSIDE the diagram without covering the profiles.
    # A lower blank band is created dynamically, so this also remains valid for
    # the other available target shapes instead of relying on rectangle-only limits.
    final_curves = [final_target_plot] + [r["final_height"] for r in results]
    finite_values = np.concatenate([curve[np.isfinite(curve)] for curve in final_curves])
    data_min = float(np.min(finite_values))
    data_max = float(np.max(finite_values))
    data_span = max(data_max - data_min, 1e-6)
    ax_final.set_ylim(data_min - 0.72 * data_span, data_max + 0.08 * data_span)
    ax_final.legend(
        fontsize=LEGEND_SIZE,
        loc="lower center",
        frameon=True,
        framealpha=0.96,
        borderaxespad=0.8,
    )

    layers = np.arange(1, N_LAYERS + 1)
    for r in results:
        rel_mse = [m["rel_mse"] for m in r["layer_metrics"]]
        max_ov = [m["max_overshoot"] for m in r["layer_metrics"]]
        mean_ov = [m["mean_overshoot"] for m in r["layer_metrics"]]
        ax_mae.plot(layers, rel_mse, marker="o", markersize=MARKER_SIZE, linewidth=LINE_WIDTH, label=r["short_name"])
        ax_max_ov.plot(layers, max_ov, marker="o", markersize=MARKER_SIZE, linewidth=LINE_WIDTH, label=r["short_name"])
        ax_mean_ov.plot(layers, mean_ov, marker="o", markersize=MARKER_SIZE, linewidth=LINE_WIDTH, label=r["short_name"])

    ax_mae.set_title("Relative MSE over layers", fontsize=PANEL_TITLE_SIZE, pad=12)
    ax_mae.set_xlabel("layer", fontsize=AXIS_LABEL_SIZE)
    ax_mae.set_ylabel("relative MSE", fontsize=AXIS_LABEL_SIZE)
    style_axis(ax_mae)
    ax_mae.legend(fontsize=LEGEND_SIZE)

    ax_max_ov.set_title("Maximum overshoot over layers", fontsize=PANEL_TITLE_SIZE, pad=12)
    ax_max_ov.set_xlabel("layer", fontsize=AXIS_LABEL_SIZE)
    ax_max_ov.set_ylabel("max overshoot", fontsize=AXIS_LABEL_SIZE)
    style_axis(ax_max_ov)
    ax_max_ov.legend(fontsize=LEGEND_SIZE)

    ax_mean_ov.set_title("Mean overshoot over layers", fontsize=PANEL_TITLE_SIZE, pad=12)
    ax_mean_ov.set_xlabel("layer", fontsize=AXIS_LABEL_SIZE)
    ax_mean_ov.set_ylabel("mean overshoot", fontsize=AXIS_LABEL_SIZE)
    style_axis(ax_mean_ov)
    ax_mean_ov.legend(fontsize=LEGEND_SIZE)

    fig.suptitle(
        f"1D 3-case demo: TARGET_MODE={TARGET_MODE} | slicer/original, slicer/modified, RL/modified",
        fontsize=FIGURE_TITLE_SIZE,
        y=0.995,
    )
    fig.subplots_adjust(top=0.91, bottom=0.12, hspace=0.48, wspace=0.25)
    out_path = out_dir / "rectangle_layer_metrics.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.show()
    plt.close(fig)
    return out_path


def plot_selected_layer_snapshots(results: List[Dict[str, Any]], out_dir: Path) -> Path:
    selected_layers = [1, max(1, N_LAYERS // 2), N_LAYERS]
    n_rows = len(selected_layers)
    n_cols = len(results)

    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(7.0 * n_cols, 4.7 * n_rows),
        sharex=True,
        sharey=True,
    )

    if n_rows == 1:
        axes = axes[None, :]
    if n_cols == 1:
        axes = axes[:, None]

    for row, layer in enumerate(selected_layers):
        for col, r in enumerate(results):
            ax = axes[row, col]
            x = r["x_grid"]
            h = r["layer_heights"][layer - 1]
            t = r["layer_targets"][layer - 1].copy()
            t[t <= 0.0] = np.nan

            ax.fill_between(x, 0, h, alpha=0.35)
            ax.plot(x, h, linewidth=LINE_WIDTH, label="height")
            ax.plot(x, t, "k--", linewidth=2.2, label="target")
            ax.set_xlim(0.0, 1.0)
            ax.set_ylim(0.0, N_LAYERS * LAYER_THICKNESS * 1.18)
            style_axis(ax)

            m = r["layer_metrics"][layer - 1]
            if row == 0:
                ax.set_title(r["short_name"], fontsize=PANEL_TITLE_SIZE, pad=12)

            # Keep every metrics box inside its diagram.  Layers 1 and 5 have
            # free space above their low profiles; layer 10 uses the lower-left
            # corner as requested.  The larger font is thesis-readable.
            box_at_bottom = layer == N_LAYERS
            ax.text(
                0.02,
                0.04 if box_at_bottom else 0.96,
                f"L{layer}: RelMSE={m['rel_mse']:.3e}\nmaxOv={m['max_overshoot']:.3e}\nmeanOv={m['mean_overshoot']:.3e}",
                transform=ax.transAxes,
                ha="left",
                va="bottom" if box_at_bottom else "top",
                fontsize=ANNOTATION_SIZE,
                bbox=dict(boxstyle="round", facecolor="white", edgecolor="0.35", alpha=0.97),
                zorder=10,
            )

            if col == 0:
                ax.set_ylabel(f"layer {layer}\nheight", fontsize=AXIS_LABEL_SIZE)
            if row == n_rows - 1:
                ax.set_xlabel("x", fontsize=AXIS_LABEL_SIZE)

    handles, labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="upper center", bbox_to_anchor=(0.5, 0.945), ncol=2, fontsize=LEGEND_SIZE)
    fig.suptitle("Selected layer snapshots", fontsize=FIGURE_TITLE_SIZE, y=0.995)
    fig.subplots_adjust(top=0.87, bottom=0.08, hspace=0.34, wspace=0.10)
    out_path = out_dir / "rectangle_layer_snapshots.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.show()
    plt.close(fig)
    return out_path


def plot_velocity_heatmaps(results: List[Dict[str, Any]], out_dir: Path) -> Path:
    n_cols = len(results)
    fig, axes = plt.subplots(1, n_cols, figsize=(4.5 * n_cols, 4.2), sharey=True)

    if n_cols == 1:
        axes = [axes]

    for ax, r in zip(axes, results):
        im = ax.imshow(
            r["velocities"],
            aspect="auto",
            origin="lower",
            interpolation="nearest",
            extent=[0, N_STEPS - 1, 1, N_LAYERS],
        )
        ax.set_title(r["short_name"])
        ax.set_xlabel("step")
        ax.set_ylabel("layer")
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="velocity")

    fig.suptitle("Velocity command per layer and step", fontsize=15)
    fig.tight_layout()
    out_path = out_dir / "03_velocity_heatmaps.png"
    fig.savefig(out_path, dpi=220, bbox_inches="tight")
    plt.show()
    plt.close(fig)
    return out_path



def plot_velocity_corrections(results: List[Dict[str, Any]], out_dir: Path) -> Path:
    """
    CHANGED: explicit plot of what the agent actually does.

    For every selected layer and every case, this plot shows:
        v_base : velocity computed by the slicer
        dv     : RL correction, zero for slicer-only cases
        v      : final executed velocity after correction

    This is the most important plot for the mentor question:
    "what does the agent actually do?"
    """
    selected_layers = [1, max(1, N_LAYERS // 2), N_LAYERS]
    n_rows = len(results)
    n_cols = len(selected_layers)

    fig, axes = plt.subplots(
        n_rows,
        n_cols,
        figsize=(7.0 * n_cols, 4.6 * n_rows),
        sharex=True,
    )
    if n_rows == 1:
        axes = axes[None, :]
    if n_cols == 1:
        axes = axes[:, None]

    steps = np.arange(N_STEPS)
    for row, r in enumerate(results):
        for col, layer in enumerate(selected_layers):
            ax = axes[row, col]
            idx = layer - 1
            v_base = r["base_velocities"][idx]
            dv = r["dvs"][idx]
            v = r["velocities"][idx]

            ax.plot(steps, v_base, linestyle="--", linewidth=2.4, label=r"$v^{base}$")
            ax.plot(steps, v, linewidth=LINE_WIDTH, label=r"$v=v^{base}+\delta v$")
            ax2 = ax.twinx()
            ax2.plot(steps, dv, linewidth=2.0, alpha=0.80, label=r"$\delta v$")
            ax2.axhline(0.0, linewidth=0.8, alpha=0.5)

            ax.set_title(f"{r['short_name']} | layer {layer}", fontsize=PANEL_TITLE_SIZE, pad=11)
            ax.set_xlabel("step", fontsize=AXIS_LABEL_SIZE)
            # Place axis names only on the two outside edges of the full grid.
            # Inner columns keep their numerical ticks, but no overlapping names.
            if col == 0:
                ax.set_ylabel("velocity", fontsize=AXIS_LABEL_SIZE)
            else:
                ax.set_ylabel("")
            if col == n_cols - 1:
                ax2.set_ylabel(r"$\delta v$", fontsize=AXIS_LABEL_SIZE)
            else:
                ax2.set_ylabel("")
            style_axis(ax)
            ax2.tick_params(axis="y", which="major", labelsize=TICK_LABEL_SIZE)

            if row == 0 and col == 0:
                lines1, labels1 = ax.get_legend_handles_labels()
                lines2, labels2 = ax2.get_legend_handles_labels()
                # A figure-level legend is added below; never cover plotted lines.
                velocity_legend = (lines1 + lines2, labels1 + labels2)

    if 'velocity_legend' in locals():
        fig.legend(*velocity_legend, loc="upper center", bbox_to_anchor=(0.5, 0.955), ncol=3, fontsize=LEGEND_SIZE)
    fig.suptitle("What the agent actually does: slicer velocity, correction, executed velocity", fontsize=FIGURE_TITLE_SIZE, y=0.995)
    fig.subplots_adjust(top=0.90, bottom=0.07, hspace=0.38, wspace=0.34)
    out_path = out_dir / "rectangle_velocity_correction.png"
    fig.savefig(out_path, dpi=300, bbox_inches="tight", facecolor="white")
    plt.show()
    plt.close(fig)
    return out_path

def save_summary_json(results: List[Dict[str, Any]], out_dir: Path) -> Path:
    summary: Dict[str, Any] = {
        "experiment_claim": "Compare the ideal slicer reference, the modified-kernel mismatch baseline, and RL correction under the modified execution kernel.",
        "target_mode": TARGET_MODE,
        "target_amplitude": TARGET_AMPLITUDE,
        "cases_explanation": {
            "Slicer / original": "ideal reference: K_slicer = K_execution = original Gaussian",
            "Slicer / modified": "mismatch baseline: K_slicer = original Gaussian, K_execution = modified geometry-dependent kernel",
            "RL / modified": "agent correction: v = v_base + delta_v, K_execution = modified geometry-dependent kernel",
        },
        "results": {},
    }
    for r in results:
        summary["results"][r["short_name"]] = {
            "name": r["name"],
            "kernel_mode": r["kernel_mode"],
            "uses_sod": r["uses_sod"],
            "use_agent": r["use_agent"],
            "final_metrics": r["final_metrics"],
            "layer_metrics": r["layer_metrics"],
        }

    out_path = out_dir / "metrics_summary.json"
    out_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    return out_path


def print_final_table(results: List[Dict[str, Any]]) -> None:
    print("\n" + "=" * 120)
    print("FINAL METRICS AFTER ALL LAYERS")
    print("=" * 120)
    print(
        f"{'case':<34} {'kernel':<10} {'agent':<8} {'RelMSE':>12} {'max_ov':>12} "
        f"{'mean_ov':>12} {'max_abs':>12} {'mean_uf':>12}"
    )
    print("-" * 120)

    for r in results:
        m = r["final_metrics"]
        print(
            f"{r['short_name']:<34} {r['kernel_mode']:<10} {str(r['use_agent']):<8} "
            f"{m['rel_mse']:>12.5e} {m['max_overshoot']:>12.5e} "
            f"{m['mean_overshoot']:>12.5e} {m['max_abs_error']:>12.5e} "
            f"{m['mean_underfill']:>12.5e}"
        )
    print("=" * 120 + "\n")



def select_best_shape_by_rel_mse(cases: List[CaseSpec], out_dir: Path) -> Tuple[str, float, List[Dict[str, Any]], List[Dict[str, Any]]]:
    """
    CHANGED: automatically search a small set of difficult target shapes.

    Why this exists:
    - The user wants a plot where RL/modified has lower relative MSE than both slicer
      baselines.
    - Since this depends on the trained checkpoint, we should not assume it.
      The script evaluates candidate shapes using the actual loaded PPO model
      and selects the best one according to:

          score = max(RelMSE_slicer_original - RelMSE_RL_modified,
                      RelMSE_slicer_modified - RelMSE_RL_modified)

      but only a "strict win" candidate satisfies:
          RelMSE_RL_modified < RelMSE_slicer_original
          RelMSE_RL_modified < RelMSE_slicer_modified

    If no strict win exists, we still choose the candidate with the best
    improvement over Slicer/modified and print a clear warning.
    """
    global TARGET_MODE, TARGET_AMPLITUDE

    original_mode = TARGET_MODE
    original_amp = TARGET_AMPLITUDE

    search_rows: List[Dict[str, Any]] = []
    best_results: Optional[List[Dict[str, Any]]] = None
    best_mode = original_mode
    best_amp = original_amp
    best_score = -1e99
    best_strict = False

    print("\n" + "=" * 120)
    print("AUTO-SEARCH TARGET SHAPES")
    print("=" * 120)
    print("Goal: find a shape where relative MSE(RL/modified) is lower than both slicer baselines.")
    print("-" * 120)

    for mode, amp in CANDIDATE_SHAPES:
        TARGET_MODE = mode
        TARGET_AMPLITUDE = float(amp)

        try:
            results = [simulate_case(case, eval_seed=EVAL_SEED) for case in cases]
        except Exception as exc:  # noqa: BLE001
            print(f"[WARN] candidate failed: mode={mode}, amp={amp}: {exc}")
            continue

        by_name = {r["short_name"]: r for r in results}
        if not all(k in by_name for k in ["Slicer / original", "Slicer / modified", "RL / modified"]):
            continue

        rel_mse_so = by_name["Slicer / original"]["final_metrics"]["rel_mse"]
        rel_mse_sm = by_name["Slicer / modified"]["final_metrics"]["rel_mse"]
        rel_mse_rl = by_name["RL / modified"]["final_metrics"]["rel_mse"]

        improve_vs_orig = rel_mse_so - rel_mse_rl
        improve_vs_mod = rel_mse_sm - rel_mse_rl
        strict_win = (rel_mse_rl < rel_mse_so) and (rel_mse_rl < rel_mse_sm)

        # Prefer strict-win candidates. Among them maximize the smaller margin.
        # If none is strict, select the case with strongest improvement over
        # Slicer/modified while not being catastrophically worse than original.
        if strict_win:
            score = min(improve_vs_orig, improve_vs_mod)
        else:
            score = improve_vs_mod - 0.25 * max(rel_mse_rl - rel_mse_so, 0.0)

        row = {
            "mode": mode,
            "amplitude": float(amp),
            "rel_mse_slicer_original": float(rel_mse_so),
            "rel_mse_slicer_modified": float(rel_mse_sm),
            "rel_mse_rl_modified": float(rel_mse_rl),
            "improve_vs_slicer_original": float(improve_vs_orig),
            "improve_vs_slicer_modified": float(improve_vs_mod),
            "strict_win": bool(strict_win),
            "score": float(score),
        }
        search_rows.append(row)

        print(
            f"{mode:<22} A={amp:<7.4f} | "
            f"RelMSE SO={rel_mse_so:.4e}, SM={rel_mse_sm:.4e}, RL={rel_mse_rl:.4e} | "
            f"strict_win={strict_win}"
        )

        should_replace = False
        if strict_win and not best_strict:
            should_replace = True
        elif strict_win == best_strict and score > best_score:
            should_replace = True

        if should_replace:
            best_results = results
            best_mode = mode
            best_amp = float(amp)
            best_score = score
            best_strict = strict_win

    if best_results is None:
        # Fallback to original setting.
        TARGET_MODE = original_mode
        TARGET_AMPLITUDE = original_amp
        best_results = [simulate_case(case, eval_seed=EVAL_SEED) for case in cases]
        best_mode = TARGET_MODE
        best_amp = TARGET_AMPLITUDE

    # Restore selected candidate globally so all plots and JSON use the selected shape.
    TARGET_MODE = best_mode
    TARGET_AMPLITUDE = best_amp

    print("-" * 120)
    print(f"[SELECTED] TARGET_MODE={best_mode}, TARGET_AMPLITUDE={best_amp}, strict_win={best_strict}")
    if not best_strict:
        print("[NOTE] No candidate made RL/modified beat both slicer baselines.")
        print("       This is scientifically possible because Slicer/original is an ideal reference.")
        print("       The selected shape is the best available candidate in this sweep. RL/original is also plotted for reference.")
    print("=" * 120 + "\n")

    search_path = out_dir / "target_shape_search_results_rel_mse.json"
    search_path.write_text(json.dumps(search_rows, indent=2), encoding="utf-8")
    print("[SAVED] search results:", search_path)

    return best_mode, best_amp, best_results, search_rows



# =============================================================================
# 6. Main
# =============================================================================

def main() -> None:
    out_dir = ensure_output_dir()

    cfg_original = ColdSpray1DConfig(use_geometry_dependent_kernel=False)
    cfg_modified = ColdSpray1DConfig(
        use_geometry_dependent_kernel=True,
        use_sod_dependent_kernel=USE_SOD_IN_MODIFIED_KERNEL,
    )

    print("[INFO] Output directory:", out_dir)
    print("[INFO] Target mode:", TARGET_MODE)
    print("[INFO] Object region:", (X_START, X_END), "approx final mean height =", N_LAYERS * LAYER_THICKNESS)
    print("[INFO] Layers:", N_LAYERS, "x", LAYER_THICKNESS)
    print("[INFO] Modified kernel uses geometry:", cfg_modified.use_geometry_dependent_kernel)
    print("[INFO] Modified kernel uses SOD:", cfg_modified.use_sod_dependent_kernel)

    modified_model = None
    modified_vecnorm = None

    if USE_TRAINED_AGENTS:
        # Thesis 3-case comparison (matching the three reference figures):
        #   A) Slicer / original   : v = v_base,                 K_execution = K_sigma
        #   B) Slicer / modified   : v = v_base,                 K_execution = K_modified
        #   C) RL / modified       : v = v_base + delta_v,       K_execution = K_modified
        modified_model = load_ppo(MODIFIED_MODEL_ZIP)
        modified_vecnorm = load_vecnormalize(MODIFIED_VECNORMALIZE_PKL, cfg_modified)

    cases = [
        CaseSpec(
            name="Case A: slicer-only executed with original Gaussian kernel",
            short_name="Slicer / original",
            cfg=cfg_original,
            use_agent=False,
        ),
    ]

    cases.append(
        CaseSpec(
            name="Case B: slicer-only executed with modified geometry-dependent kernel",
            short_name="Slicer / modified",
            cfg=cfg_modified,
            use_agent=False,
        )
    )

    if USE_TRAINED_AGENTS and modified_model is not None:
        cases.append(
            CaseSpec(
                name="Case C: trained PPO correction executed with modified geometry-dependent kernel",
                short_name="RL / modified",
                cfg=cfg_modified,
                model=modified_model,
                vecnorm=modified_vecnorm,
                use_agent=True,
            )
        )
    else:
        print("[WARN] Modified trained PPO is not available, so RL / modified is skipped.")

    # CHANGED: optionally select a hard target shape automatically.
    # This is useful because the desired claim depends on the actual PPO weights.
    if AUTO_SELECT_SHAPE and USE_TRAINED_AGENTS and modified_model is not None:
        selected_mode, selected_amp, results, search_rows = select_best_shape_by_rel_mse(cases, out_dir)
        print(f"[INFO] Using selected target: {selected_mode} with amplitude {selected_amp}")
    else:
        results = [simulate_case(case, eval_seed=EVAL_SEED) for case in cases]

    print_final_table(results)

    json_path = save_summary_json(results, out_dir)
    fig0 = plot_target_shape(out_dir)
    fig1 = plot_prof_summary(results, out_dir)
    fig2 = plot_selected_layer_snapshots(results, out_dir)
    fig3 = plot_velocity_heatmaps(results, out_dir)
    fig4 = plot_velocity_corrections(results, out_dir)

    print("[SAVED]")
    print(" metrics:", json_path)
    print(" figure :", fig0)
    print(" figure :", fig1)
    print(" figure :", fig2)
    print(" figure :", fig3)
    print(" figure :", fig4)


if __name__ == "__main__":
    main()