# -*- coding: utf-8 -*-
"""(SB3) cold_spray_generalized_gaussian_PPO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oEdrGq640buLjpz6CgT2GgfOAo-MkZcH
"""

#!pip install "stable-baselines3[extra]" torch gymnasium

from dataclasses import dataclass
from typing import *
from IPython.display import HTML, display
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  (for older Matplotlib back-compat)

import gymnasium as gym
import numpy as np
from math import gamma
from gymnasium import *
import matplotlib.pyplot as plt
from matplotlib import animation
import os

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions import Normal
from collections import deque
from tqdm.auto import tqdm

from stable_baselines3 import PPO
from stable_baselines3.common.policies import ActorCriticPolicy
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.callbacks import BaseCallback

LOG_FILE = open("training_debug_log_ppo.txt", "w", encoding="utf-8")
def log(*args):
    LOG_FILE.write(" ".join(str(x) for x in args) + "\n")
    LOG_FILE.flush()

@dataclass(frozen=True)
class ColdSprayConfig:
    grid_n: int = 128
    dx_max: float = 0.05
    dy_max: float = 0.05
    #df_max: float = 0.10
    dt: float = 0.05
    max_steps: int = 4000
    seed: Optional[int] = None

    sigma: float = 0.02 #footprint radius
    beta: float = 2.0
    eta: float = 1.0 #adhesive strength
    rho_m: float = 1.0 #material density
    samples_per_pixel: float = 1.0
    A_amp: float = 1.0 #footprint size
    target_height: float = 0.2
    overfill_ratio: float = 1.01

class DepositionModel:
    def __init__(self, grid_n: int, sigma: float = 0.02, beta: float = 2.0, eta: float = 1.0, rho_m: float = 1.0, samples_per_pixel: float = 1.0,
                 A_amp: float = 1.0, overfill_ratio: float = 1.02, target_height: float = 0.2) -> None:
        self.n = int(grid_n)
        self.sigma = float(sigma)
        self.beta = float(beta)
        self.eta = float(eta)
        self.rho_m = float(rho_m)
        self.spp = float(samples_per_pixel)
        self.A_amp = A_amp
        self.overfill_ratio = float(overfill_ratio)
        self.target_height = float(target_height)

        self._C = self.beta / (2.0 * np.pi * (self.sigma**2) * gamma(2.0 / self.beta))
        grid = (np.arange(self.n, dtype=np.float32) + 0.5) / self.n
        self.X, self.Y = np.meshgrid(grid, grid, indexing="ij") #indexing="xy"
        self._pix_area = (1.0 / self.n) ** 2

    def _kernel(self, r: np.ndarray) -> np.ndarray:
        # Compute the generalized Gaussian spray footprint at radius r.
        # A_amp   = amplitude (maximum spray intensity)
        # self._C = normalization constant ensuring the kernel integrates to 1
        # exp(-(r/sigma)^beta) controls footprint shape:
        #   sigma = spread radius, beta = sharpness (β=2 → Gaussian)
        #return self.A_amp * self._C * np.exp(- (r / self.sigma) ** self.beta)
        return self.A_amp * np.exp(- (r / self.sigma) ** self.beta)

    def apply(self, height, x0, y0, x1, y1, f, dt, target_height):
        overfill_ratio = self.overfill_ratio 
        # Compute movement vector and its length
        dx, dy = float(x1 - x0), float(y1 - y0)
        L = float(np.hypot(dx, dy))  # path length between (x0,y0) → (x1,y1)

        # If tool did not move or deposition intensity/time is zero → no height change
        if f <= 0.0 or dt <= 0.0: #L < 1e-12
            return np.zeros_like(height, dtype=np.float32)

        log(f"[LENGTH] dx={dx:.4f}, dy={dy:.4f}, L={L:.6f}")

        # Tool scanning speed along the path
        v = L / dt

        # Effective material deposition rate = η * f / v
        lam = (self.eta * float(f)) / (v+1e-6)  # avoid div-by-zero

        # Desired spacing between deposition samples along the tool path
        ds_target = 0.001 #self.sigma * 0.25 #(1.0 / self.n) / max(self.spp, 1e-6)

        # Number of sampling points along the path (at least 1)
        S = max(1, int(np.ceil(L / ds_target)))

        log(f"[DEBUG] v={v:.6f}, f={f:.4f}, lam={lam:.6f}")

        # Parametric sample positions along the path (midpoints)
        s = (np.arange(S, dtype=np.float32) + 0.5) * (L / S)
        xs = x0 + (dx / (L+1e-6)) * s  # x-coordinates of sampled spray centers
        ys = y0 + (dy / (L+1e-6)) * s  # y-coordinates of sampled spray centers

        # Accumulate footprint contributions into delta_h
        delta_h = np.zeros_like(height, dtype=np.float32)

        for k in range(S):
            # Distance field from the spray center to every pixel
            r = np.hypot(self.X - xs[k], self.Y - ys[k])

            # Add generalized Gaussian footprint for this sample
            delta_h += self._kernel(r)

        # Convert raw kernel sum into physical height increase
        # Factor includes:
        #   lam        = effective deposition rate
        #   rho_m      = material density
        #   pix_area   = pixel area in physical coordinates
        #   (L/S)      = spacing between sample points
        factor = (lam / (self.rho_m * self._pix_area)) * (L / S)
        delta_h *= factor

        # ------------------ Predictive Safety Layer ------------------
        # If the current height already reaches the target height map,
        # we block any further material deposition at that pixel.
        # This prevents runaway overfill and stabilizes learning.
        target_mask = (height >= target_height).astype(np.float32)
        delta_h *= (1.0 - target_mask)

        # Return the resulting height increment
        return delta_h.astype(np.float32, copy=False)

class ColdSprayEnv(gym.Env):
    metadata = {"render_modes": []}

    def __init__(self, config: Optional[ColdSprayConfig] = None) -> None:
        super().__init__()
        self.cfg = config or ColdSprayConfig()
        self._rng = np.random.default_rng(self.cfg.seed)

        N = self.cfg.grid_n
        self.height = np.zeros((N, N), dtype=np.float32)

        #self.x, self.y, self.f = 0.5, 0.5, 0.0
        self.x, self.y = 0.5, 0.5; self.f = 0.1      #fixed feed rate
        self._steps = 0

        low_state = np.array([0.0, 0.0], dtype=np.float32) #low_state = np.array([0.0, 0.0, 0.0], dtype=np.float32)
        high_state = np.array([1.0, 1.0], dtype=np.float32) #high_state = np.array([1.0, 1.0, 1.0], dtype=np.float32)

        self.observation_space = spaces.Dict({
            "height": spaces.Box(low=-np.inf, high=np.inf, shape=(N, N), dtype=np.float32),
            "state": spaces.Box(low=low_state, high=high_state, shape=(2,), dtype=np.float32),
            "target_map": spaces.Box(low=0.0, high=1.0, shape=(N, N), dtype=np.float32),
        }) #shape=(3,)
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(2,), dtype=np.float32) #shape=(3,)

        self.deposition = DepositionModel(
            grid_n=N, sigma=self.cfg.sigma, beta=self.cfg.beta,
            eta=self.cfg.eta, rho_m=self.cfg.rho_m,
            samples_per_pixel=self.cfg.samples_per_pixel, A_amp=self.cfg.A_amp,
            target_height=self.cfg.target_height, overfill_ratio=self.cfg.overfill_ratio)

    def reset(self, *, seed=None, options=None):
        if seed is not None:
            self._rng = np.random.default_rng(seed)
        self._steps = 0
        self.prev_min_h = None
        #self.x, self.y, self.f = 0.5, 0.5, 0.0
        self.x, self.y = 0.5, 0.5; self.f = 0.1 #fixed feed rate

        if options is not None and "height0" in options and options["height0"] is not None:
            h0 = np.asarray(options["height0"])
            assert h0.shape == self.height.shape
            self.height = h0.astype(np.float32, copy=True)
        else:
            self.height.fill(0.0)

        # 2D target map
        BOX_MIN = 0.25; BOX_MAX = 0.75
        N = self.height.shape[0]

        self.H_target_map = np.zeros((N, N), dtype=np.float32)
        ix0 = int(BOX_MIN * N)
        ix1 = int(BOX_MAX * N)
        iy0 = int(BOX_MIN * N)
        iy1 = int(BOX_MAX * N)

        self.H_target_map[iy0:iy1, ix0:ix1] = self.cfg.target_height # pixel in box = target = 0.2
        self.H_over_map = self.H_target_map * self.cfg.overfill_ratio # map overfill

        #obs = {"height": self.height.copy(), "state": np.array([self.x, self.y, self.f], dtype=np.float32)}
        obs = {"height": self.height.copy(), "state": np.array([self.x, self.y], dtype=np.float32), "target_map": self.H_target_map.copy()}
        info = {}
        return obs, info

    def step(self, action):
        reward = 0.0
        terminated = False
        self._steps += 1 #step counter
        N = self.height.shape[0]

        # ============================
        # 1) Unpack state & action
        # ============================
        x0, y0 = self.x, self.y #x0, y0, f0 = self.x, self.y, self.f #current tool state
        dx, dy = np.asarray(action, dtype=np.float32) #dx, dy, df = np.asarray(action, dtype=np.float32)
        f0 = 0.1; f1 = 0.1 #fixed feed rate
        #log(f"[RAW_ACT] dx={action[0]:.4f} dy={action[1]:.4f} df={action[2]:.4f}")
        #log(f"[RAW_ACT] dx={action[0]:.4f} dy={action[1]:.4f}") 
        #log(f"[ACT_DELTA] dx={dx:.4f}, dy={dy:.4f}, df={df:.4f}, f0={f0:.4f}") 
        log(f"[ACT_DELTA] dx={dx:.4f}, dy={dy:.4f}, f0={f0:.4f}") #action before clipping

        # Clip action to limits
        dx = float(np.clip(dx, -self.cfg.dx_max, self.cfg.dx_max)) #clip actions to physical bounds
        dy = float(np.clip(dy, -self.cfg.dy_max, self.cfg.dy_max))
        #df = float(np.clip(df, -self.cfg.df_max, self.cfg.df_max))

        #no hard-clipping constraints, using OOB termination instead
        x1 = x0 + dx #float(np.clip(x0 + dx, 0.0, 1.0)) #compute next tool position
        y1 = y0 + dy #float(np.clip(y0 + dy, 0.0, 1.0))

        if x1 < 0 or x1 > 1 or y1 < 0 or y1 > 1:
            print("TERMINATE: OOB")
            obs = {
                "height": self.height.copy(),
                "state": np.array([self.x, self.y], dtype=np.float32),
                "target_map": self.H_target_map.copy(),
            }
            return obs, -10.0, True, False, {"reason": "out_of_bounds"}

        f1 = 0.1 #fixed feed rate #float(np.clip(f0 + df, 0.0, 0.05))
        # ===== APPLY deposition: chuyển s_t -> s_{t+1} =====

        delta_h = self.deposition.apply(self.height, x0, y0, x1, y1, f1, self.cfg.dt, target_height=self.H_target_map)
        self.height = (self.height + delta_h).astype(np.float32, copy=False)
        self.x, self.y, self.f = x1, y1, f1

        #mse reward
        H_target = self.H_target_map      # full 2D target map (0.2 in box, 0 elsewhere)
        h = self.height

        # Underfill error everywhere
        under = np.maximum(0.0, H_target - h)
        MSE_under = float(np.mean(under ** 2))

        # Overfill error everywhere
        over = np.maximum(0.0, h - H_target)
        MSE_over  = float(np.mean(over ** 2))

        # Weights
        w_under = 1.0
        w_over  = 1.0

        # Reward = negative loss
        reward = -(w_under * MSE_under + w_over * MSE_over)

        log(f"[REWARD] r_underfill={MSE_under:.6e}, r_overfill={MSE_over:.6e}")
        log(f"[STEP {self._steps}] reward={reward:.4f}")

        info = {"MSE_under": MSE_under, "MSE_over": MSE_over, "reward": float(reward),}

        #obs = {"height": self.height.copy(), "state": np.array([self.x, self.y, self.f], dtype=np.float32),}
        obs = {"height": self.height.copy(), "state": np.array([self.x, self.y], dtype=np.float32), "target_map": self.H_target_map.copy(),}
        terminated = False
        truncated = self._steps >= self.cfg.max_steps
        return obs, float(reward), bool(terminated), bool(truncated), info

class ColdSprayExtractor(BaseFeaturesExtractor):
    """
    Feature extractor used by PPO.
    Combines:
        - A CNN for spatial information from the height map + target map
        - An MLP for local (x, y) + local target height at the nozzle
    Output: 64-dim feature vector
    """

    def __init__(self, observation_space, features_dim=64, overfill_ratio=1.01):
        super().__init__(observation_space, features_dim)
        n = observation_space['height'].shape[0] #resolution of N×N maps

        # Conv2d input has 2 channels: channel 0: current height map; channel 1: target map (0.2 inside box, 0.0 outside)
        self.conv1 = nn.Conv2d(2, 32, kernel_size=5, stride=2, padding=2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, stride=2, padding=1) #downsampling
        self.gap   = nn.AdaptiveAvgPool2d(1) #collapses spatial dimensions into single vector
        self.cnn_fc = nn.Linear(64, 64) #convert CNN features into 64-dim embedding

        # MLP 
        self.mlp_fc = nn.Linear(3, 64)
        #CNN branch (64) and MLP branch (64), vectors are concatenated into a 128-dim feature, then projected to final 64-dim vector.
        self.shared = nn.Linear(128, 64)
        self.ln = nn.LayerNorm(128)
        self._features_dim = 64  # output features dim

    def forward(self, obs):
        # create a 2-channel tensor from height map and target map (batch, 2, N, N)
        h = torch.stack([obs["height"], obs["target_map"]], dim=1)
        h = F.relu(self.conv1(h))
        h = F.relu(self.conv2(h))

        # Compress spatial dimensions to (B, 64)
        h = self.gap(h).flatten(1)

        # 64-dim feature
        h = F.relu(self.cnn_fc(h))

        # extract (x,y) nozzle position from observation
        xy = obs["state"]        # shape (B, 2)
        B = xy.size(0)           # batch size
        N = obs["target_map"].size(-1)  # map resolution

        # convert (x, y) in [0,1] to pixel indices (0..N-1)
        tx = (xy[:,0] * N).long().clamp(0, N-1)
        ty = (xy[:,1] * N).long().clamp(0, N-1)

        # 0.2 inside the spray box and 0.0 outside.
        target_at_xy = obs["target_map"][torch.arange(B), ty, tx].unsqueeze(1)

        # MLP input vector = [x_position, y_position, local_target_height]
        mlp_in = torch.cat([xy, target_at_xy], dim=1)

        # process local information into 64-dim representation
        s = F.relu(self.mlp_fc(mlp_in))

        # Concatenate global CNN features and local MLP features to 128 dims
        z = torch.cat([h, s], dim=1)

        # Normalize combined features to stabilize PPO training
        z = self.ln(z)

        # Final shared layer → 64-dim output for PPO policy + value networks
        z = F.relu(self.shared(z))
        return z
    
class NozzleTrajectoryCallback(BaseCallback):
    """
    Callback for visualizing the full nozzle trajectory during PPO training
    Each PPO rollout consists of `n_steps` environment steps
    """
    def __init__(self, save_dir="train_rollouts", verbose=1):
        super().__init__(verbose)
        self.save_dir = save_dir
        os.makedirs(save_dir, exist_ok=True)
        self.path_xy = []

    # ------------------------------------------------
    def _on_rollout_start(self):
        """Reset the trajectory buffer at the beginning of each PPO rollout"""
        self.path_xy = []
        x = self.training_env.get_attr("x")[0]
        y = self.training_env.get_attr("y")[0]
        self.path_xy.append((x, y))
        return True

    # ------------------------------------------------
    def _on_step(self):
        """Record (x, y) at every environment step inside the rollout"""
        x = self.training_env.get_attr("x")[0]
        y = self.training_env.get_attr("y")[0]
        self.path_xy.append((x, y))
        return True

    # ------------------------------------------------
    def _on_rollout_end(self):
        """
        After PPO finishes collecting `n_steps`, the rollout ends. This function plots and saves the nozzle trajectory.
        """
        xs, ys = zip(*self.path_xy)

        fig = plt.figure(figsize=(5,5))
        plt.plot(xs, ys, '-', lw=1.5)
        plt.scatter(xs[0], ys[0], c="green", s=50, label="Start")
        plt.scatter(xs[-1], ys[-1], c="red", s=50, label="End")
        plt.legend()
        plt.xlim(0,1); plt.ylim(0,1)
        plt.gca().set_aspect("equal")
        plt.grid(alpha=0.3)
        plt.title(f"Training Rollout – step={self.num_timesteps}")

        fname = f"{self.save_dir}/rollout_{self.num_timesteps}.png"
        plt.savefig(fname, dpi=150)
        plt.close()

        if self.verbose: print(f"✓ Saved training rollout: {fname}")
        return True
    
class TrajectoryBuffer:
    def __init__(self):
        self.obs = []
        self.actions = []
        self.logps = []
        self.rewards = []
        self.values = []
        self.dones = []

    def store(self, obs, act, rew, logp, val, done):
        self.obs.append(obs)
        self.actions.append(act)
        self.rewards.append(rew)
        self.logps.append(logp)
        self.values.append(val)
        self.dones.append(done)

    def clear(self):
        self.__init__()

def rollout_stochastic(env, model, T):
    obs, _ = env.reset()
    path_xy = [(float(obs["state"][0]), float(obs["state"][1]))]
    rewards = []

    for t in range(T):
        a_sto, _ = model.predict(obs, deterministic=False)
        obs, r, terminated, truncated, _ = env.step(a_sto)
        rewards.append(r)
        path_xy.append((float(obs["state"][0]), float(obs["state"][1])))

        if terminated or truncated:
            break
    return path_xy, rewards

#deterministic rollout for evaluation
def rollout_deterministic_sb3(env, model, T):
    obs, _ = env.reset()
    path_xy = [(float(obs["state"][0]), float(obs["state"][1]))]
    rewards = []

    for t in range(T):
        a_det, _ = model.predict(obs, deterministic=True)
        obs, r, terminated, truncated, _ = env.step(a_det)
        rewards.append(r)
        path_xy.append((float(obs["state"][0]), float(obs["state"][1])))

        if terminated or truncated:
            break

    return path_xy, rewards, env.height.copy()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

cfg = ColdSprayConfig(grid_n=128, rho_m=6500.0, eta=0.4, target_height=0.2,
                      overfill_ratio=1.01, dx_max=0.1, dy_max=0.1, dt=0.2,
                      max_steps=500000, sigma=0.01, beta=2.0, seed=None)

def _make_env():
    return Monitor(ColdSprayEnv(cfg))

venv = make_vec_env(_make_env, n_envs=2ls)

policy_kwargs = dict(
    features_extractor_class=ColdSprayExtractor,
    features_extractor_kwargs=dict(features_dim=64, overfill_ratio=cfg.overfill_ratio),
    net_arch=dict(
        pi=[128,128],    
        vf=[128,128]     
    ),
    log_std_init=-3.0,      
)

model = PPO(
    policy="MultiInputPolicy",
    env=venv,
    policy_kwargs=policy_kwargs,
    learning_rate=1e-3,     
    n_steps=50000,           
    batch_size=25000,         
    n_epochs=10,            
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.2,
    ent_coef=0.0,           
    vf_coef=0.5,
    max_grad_norm=0.5,
    verbose=0,
    device=device,)

def save_exploration_vs_deterministic(
        epoch: int, 
        det_path_xy, 
        sto_path_xy, 
        det_rewards, 
        sto_rewards,
        det_height_map,
        outdir="pics-ppo"
    ):
    if not os.path.exists(outdir):
        os.makedirs(outdir)

    xs_det, ys_det = zip(*det_path_xy)
    xs_sto, ys_sto = zip(*sto_path_xy)

    fig, axs = plt.subplots(1, 3, figsize=(16, 5))

    # ======== 1) deterministic path ========
    axs[0].plot(xs_det, ys_det, "-", lw=2, color="blue")
    axs[0].scatter(xs_det[0], ys_det[0], c="green", s=60)
    axs[0].scatter(xs_det[-1], ys_det[-1], c="red", s=60)
    axs[0].set_title(f"Deterministic (mean) – epoch {epoch}")
    axs[0].set_xlim(0, 1); axs[0].set_ylim(0, 1)
    axs[0].set_aspect("equal")
    axs[0].grid(alpha=0.3)

    # ======== 2) stochastic path ========
    axs[1].plot(xs_sto, ys_sto, "--", lw=1.6, color="orange")
    axs[1].scatter(xs_sto[0], ys_sto[0], c="green", s=60)
    axs[1].scatter(xs_sto[-1], ys_sto[-1], c="red", s=60)
    axs[1].set_title(f"Exploration (sampling) – epoch {epoch}")
    axs[1].set_xlim(0, 1); axs[1].set_ylim(0, 1)
    axs[1].set_aspect("equal")
    axs[1].grid(alpha=0.3)

    # ======== 3) height map after deterministic rollout ========
    hm = axs[2].imshow(det_height_map, cmap="viridis", origin="upper")
    axs[2].set_title("Height map after deterministic rollout")
    fig.colorbar(hm, ax=axs[2], fraction=0.046, pad=0.04)

    plt.tight_layout()
    savefile = f"{outdir}/rollout_epoch_{epoch}.png"
    plt.savefig(savefile, dpi=150)
    plt.close()
    print(f"✓ Saved: {savefile}")

    # =============================
    # === Reward curves over T ===
    # =============================
    plt.figure(figsize=(7,4))
    plt.plot(det_rewards, label="Deterministic", lw=2)
    plt.plot(sto_rewards, label="Stochastic", lw=1.5, alpha=0.7)
    plt.xlabel("Time step")
    plt.ylabel("Reward")
    plt.title(f"Reward curves – epoch {epoch}")
    plt.legend()
    plt.grid(alpha=0.3)

    savefile2 = f"{outdir}/reward_curve_epoch_{epoch}.png"
    plt.savefig(savefile2, dpi=150)
    plt.close()
    print(f"✓ Saved: {savefile2}")

def train_sb3(env_cfg, model, N_epochs=10, visualize_every=20, log_path="training_log_ppo.txt"):
    eval_env = ColdSprayEnv(env_cfg); eval_env.reset()

    #H_target = np.ones((eval_env.height.shape[0], eval_env.height.shape[1]), dtype=np.float32) * 0.2
    H_target = eval_env.H_target_map.copy()
    rmse_history, reward_history = [], []
    global_path_xy = []
    best_rmse = float("inf")
    best_epoch = -1

    lr = model.lr_schedule(1)
    last_improvement_epoch = 0

    if os.path.exists(log_path):
        os.remove(log_path)
    log_file = open(log_path, "w", encoding="utf-8")
    log_file.write("Epoch\tRMSE\tMinH\tMaxH\tMeanH\n")

    # not reset timestep
    n_steps_chunk = model.n_steps * model.n_epochs

    for epoch in range(N_epochs):
        print(f"\n🚀 Epoch {epoch}/{N_epochs} ...")
        callback = NozzleTrajectoryCallback(save_dir="/home/nham/train_ppo_rollouts")
        model.learn(total_timesteps=n_steps_chunk, callback=callback, reset_num_timesteps=False, progress_bar=False)
        print("✅ done")
        obs, _ = eval_env.reset(options=None)

        # rollout deterministic on eval_env
        path_xy, det_rewards, det_height_map = rollout_deterministic_sb3(eval_env, model, T=env_cfg.max_steps)
        global_path_xy.extend(path_xy)
        total_reward = float(sum(det_rewards))
        log(f"[Epoch {epoch:04d}] Total deterministic reward = {total_reward:.4f}")

        H_t = eval_env.height.copy()

        rmse = float(np.sqrt(np.mean((H_t - H_target)**2)))

        rmse_history.append(rmse)
        reward_history.append(np.nan) 

        min_h, max_h, mean_h = float(np.min(H_t)), float(np.max(H_t)), float(np.mean(H_t))
        log_file.write(f"{epoch}\t{rmse:.6f}\t{min_h:.6f}\t{max_h:.6f}\t{mean_h:.6f}\n")
        log_file.flush()

        log(f"[Epoch {epoch:04d}] RMSE={rmse:.6f}  MinH={min_h:.4f}  MaxH={max_h:.4f}  MeanH={mean_h:.4f}")

        if rmse < best_rmse:
            best_rmse = rmse
            best_epoch = epoch
            last_improvement_epoch = epoch

            print(f"\n📉 New best RMSE ({rmse:.6f}) at epoch {epoch}. Saving visualization...")

            det_path_xy, det_rewards, det_height_map = rollout_deterministic_sb3(eval_env, model, T=50000)
            sto_path_xy, sto_rewards = rollout_stochastic(eval_env, model, T=50000)

            save_exploration_vs_deterministic(
                epoch=epoch,
                det_path_xy=det_path_xy,
                sto_path_xy=sto_path_xy,
                det_rewards=det_rewards,
                sto_rewards=sto_rewards,
                det_height_map=det_height_map,
                outdir="pics-ppo"
            )

        # reduce learning rate if no improvement for 50 epochs
        if (epoch - last_improvement_epoch) >= 50:
            new_lr = lr * 0.5
            new_lr = max(new_lr, 1e-5)  
            print(f"⚠️ No improvement for 50 epochs → reducing LR: {lr:.2e} → {new_lr:.2e}")

            model.learning_rate = new_lr
            model.lr_schedule = lambda _: new_lr  

            lr = new_lr
            last_improvement_epoch = epoch        

    log_file.close()
    print(f"\n✅ Training complete. Log saved to: {os.path.abspath(log_path)}")

if __name__ == "__main__":
    print("Training SB3-PPO on ColdSprayEnv ...")
    train_sb3(cfg, model, N_epochs=200, visualize_every=10, log_path="training_log_ppo.txt")